### ISSUE TITLE
[question]: 

### ISSUE THREAD

**Issue by emmataobao** [towhee-io/towhee#1008]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

>>> embedding_pipeline = pipeline('image-embedding')
>>> embedding = embedding_pipeline('https://docs.towhee.io/img/logo.png')

https://docs.towhee.io/img/logo.png
Does the path support S3?

**Comment by fzliu** [comment]
Towhee supports any http-based URL, including S3 path-style URLs e.g. `https://s3.us-west-2.amazonaws.com/mybucket/puppy.jpg`. However, we do not yet support links that begin with `S3://`.

**Comment by emmataobao** [comment]
thank you

**Comment by fzliu** [comment]
You're very welcome - if you have further questions, feel free to join our [Slack](https://slack.towhee.io). You'll get a quicker response from us and I'll be able to loop in more team members to help you with any issues you're facing.
