### ISSUE TITLE
[Feature]: Add towhee.dc for easy DataCollection creation.

### ISSUE THREAD

**Issue by GuoRentong** [towhee-io/towhee#1013]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

The reasons why we need a convenience function `towhee.dc` for DataCollection creation
* The name towhee.DataCollection is too long for a frequent used interface
* Adding a light layer above towhee.DataCollection will offer the space for developing syntactic suger to simplify DataCollection constructions.

**Comment by filip-halt** [comment]
I believe we currently allow using just towhee.glob(), towhee.range(), etc. without the DataCollection.
