### ISSUE TITLE
[Bug]: Version inconsistency test error

### ISSUE THREAD

**Issue by emmataobao** [towhee-io/towhee#1015]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

towhee version 0.2.0 no problem ，but An exception occurs when switching to the latest version。
![image](https://user-images.githubusercontent.com/46233536/161886775-f1cdbdb7-8890-4f1c-b52b-82a714aebac1.png)
Error with extracting feature from image 'float' object is not subscriptable

![image](https://user-images.githubusercontent.com/46233536/161886875-8bfbd59a-9c1a-4bdd-8244-c6c2cf477949.png)
towhee version ==0.2.0
![image](https://user-images.githubusercontent.com/46233536/161887125-9a3b6f43-e6a7-4b4a-b9f5-7350e0eb5206.png)

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.5
- OS(Ubuntu or CentOS):windows
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jaelgu** [comment]
@emmataobao The image-embedding pipelines have been optimized and changed to adapt new versions since towhee 0.4. Here are solution options:
1. If you want to use towhee>0.2, then you need to update the local pipelines & operators:
    1. Remove local directory of towhee pipelines & operators
       `rm ~/.towhee`
    2. Modify your code to adapt new pipeline output (You should just remove [0][0] to get the vector)
        `norm_feat.to_list()`
2. If you don't want to modify your code or update local pipelines/operators, then you can just use towhee0.2 for now.

Btw, is your issue from Milvus Bootcamp? If so, you can log issue there and we will update towhee-related code in Bootcamp examples.

**Comment by emmataobao** [comment]
@jaelgu  yes，issue from Milvus Bootcamp。
But I found that the two versions produce very different vectors。
towhee =0.2

**Comment by emmataobao** [comment]
@jaelgu yes， issue from Milvus Bootcamp。
But I found that the two versions produce very different vectors, embedding_pipeline = pipeline('image-embedding')
towhee =0.2
![image](https://user-images.githubusercontent.com/46233536/161889698-49553c68-31f4-4b5a-ac3b-9b952a6eb47d.png)
towhee =0.5 
![image](https://user-images.githubusercontent.com/46233536/161889830-6c2c4f29-974e-42b4-8365-6283b0c86e15.png)

**Comment by fzliu** [comment]
With Towhee 0.5, we used the post-activation embeddings, which means that approximately half of the values in your resultant vector will be 0 since Resnet50 uses ReLU.

The result you are getting is normal.
