### ISSUE TITLE
[Bug]:  Can not get audio_decode.ffmpeg's results.

### ISSUE THREAD

**Issue by junjiejiangjjj** [towhee-io/towhee#1022]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![UlKAYjHFIu](https://user-images.githubusercontent.com/14136703/161933665-8b2d7896-f765-47c2-ace8-4b15efc23267.png)

The operator `audio-decode/ffmpeg`  returns a generator, when using `dc` to call this operator, it can not return the real result of this op.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by reiase** [comment]
you can unwrap the generator with `flaten`:
```python
dc.flaten()
```

**Comment by junjiejiangjjj** [comment]
Another problem:
![image](https://user-images.githubusercontent.com/14136703/161960364-fbbf9938-1cfd-4ae7-a19e-a1318c404d57.png)
![image](https://user-images.githubusercontent.com/14136703/161960396-b9c4236b-e7e9-4414-a4f4-a8c802bde491.png)
