### ISSUE TITLE
[Bug]: 404 https://hub.towhee.io/api/v1/repos/shiyu/img_object_embedding_pytorch_yolov5_resnet50

### ISSUE THREAD

**Issue by lilianfan** [towhee-io/towhee#1036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

404  https://hub.towhee.io/api/v1/repos/shiyu/img_object_embedding_pytorch_yolov5_resnet50

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by fzliu** [comment]
Hey @lilianfan, welcome to the Towhee community.  We've deprecated that repo in favor of a different pipeline naming scheme.

@shiyu22 can you update the repo along with bootcamp when you're free?

**Comment by shiyu22** [comment]
Hi @lilianfan, actually I have updated this pipeline to [img_object_embedding](https://towhee.io/towhee/img_object_embedding), but it's for towhee0.2.0.

I think that you can use the latest operator to detect objects, refer to https://towhee.io/object-detection/yolov5.

**Comment by lilianfan** [comment]
thank you

**Comment by binbinlv** [comment]
@lilianfan 
hello, could you please close this issue if the problem you addressed has been solved? Thanks.
