### ISSUE TITLE
[Enhancement]: Inconsistent results in documented cases

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#1043]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Running the case returns no True

```
>>> from towhee.functional import DataCollection
>>> from towhee.functional.entity import Entity
>>> entities = [Entity(a=i, b=i) for i in range(5)]
>>> dc = DataCollection(entities)
>>> res = dc.runas_op['a', 'b'](func=lambda x: x - 1).to_list()
>>> res[0].a = res[0].b + 1
>>>
```

<img width="683" alt="截屏2022-04-08 15 48 11" src="https://user-images.githubusercontent.com/34296482/162392099-8f935ca0-ff87-4665-bdd4-5a619e637059.png">

**Comment by binbinlv** [comment]
@jingkl 
please verify this issue.

**Comment by jingkl** [comment]
It has been verified, no problem
