### ISSUE TITLE
[Bug]: I use the same model, windos and linux generate completely different vectors

### ISSUE THREAD

**Issue by emmataobao** [towhee-io/towhee#1044]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

model towhee/image-embedding-regnetx-016
path  photo/202008/13/mapp202008130105517751.jpg
Windows 10  python 3.9 towhee 0.5.1
vector
centos 7 python 3.7 towhee 0.5.1

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by emmataobao** [comment]
![image (1)](https://user-images.githubusercontent.com/46233536/162399429-cb109fba-427f-4958-a9e2-8eb9794cb3e8.png)
![image](https://user-images.githubusercontent.com/46233536/162399458-c7e75754-07f7-4552-8c0d-a8d9521cef87.png)

**Comment by binbinlv** [comment]
Actually, I found the difference is at the last bits of each element, for example:
"0.021529437974095345" and "0.0215294249355793", " it is the same with the previous 7 bits "0.0215294", and the remaining is different.

I think this may be the difference between different OS and different python version.

@filip-halt  Could you help to have a look too? Thanks.

**Comment by jaelgu** [comment]
@emmataobao Can you check what is your output dtype? I've checked this pipeline and its output has dtype=float32. But according to your results, it looks like your dtype is about float64. If so, then the extra floats expanded are not precise for sure.

You may try several times in the same environment and to see if it still gives the exactly same results.

**Comment by fzliu** [comment]
The results that you see are normal and are a result of floating point inaccuracies between the two operating systems. Do you need the vectors to be entirely identical between the two? if you want to check for equality, you should be able to use `numpy.isclose`.
