### ISSUE TITLE
[Feature]: How to configure parameters or optimize feature extraction

### ISSUE THREAD

**Issue by emmataobao** [towhee-io/towhee#1059]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

Test 30,000 images to complete the recognition in 48 minutes. How can I improve the recognition speed, increase the server or optimize something.The time to recognize an image is between 5 seconds and 300 milliseconds。

**Comment by fzliu** [comment]
Which embedding pipeline are you using? Also, what kind of hardware (CPU/GPU) and server resources do you have?

**Comment by emmataobao** [comment]
towhee/image-embedding-regnetx-016

**Comment by emmataobao** [comment]
@fzliu @reiase towhee/image-embedding-regnetx-016 towhee=0.5.1
![image](https://user-images.githubusercontent.com/46233536/162652851-9a40bb7a-59b6-41a4-abc8-8df59d10220e.png)
The current test is the cpu server. Currently, both cpu and gpu servers are available.
I don't know how to improve the utilization of server resources to speed up feature extraction

**Comment by reiase** [comment]
> @fzliu @reiase towhee/image-embedding-regnetx-016 towhee=0.5.1
> ![image](https://user-images.githubusercontent.com/46233536/162652851-9a40bb7a-59b6-41a4-abc8-8df59d10220e.png)
> The current test is the cpu server. Currently, both cpu and gpu servers are available.
> I don't know how to improve the utilization of server resources to speed up feature extraction

you can compute on a large-scale dataset with the data collection API
```python
import towhee
embeddings = (
    towhee.dc(your_image_file_list)          # generate file list
        .image_decode()                               # decode all images
        .image_embedding.timm(model_name='resnet50')  # compute image embeddings
        .tensor_normalize()                           # embeddings normalization
        .to_list()
)
print(embeddings)
```

to improve cpu utilization, you can enable parallel execution by `set_parallel(num_thread)`:
```python
import towhee
embeddings = (
    towhee.dc(your_image_file_list)          # generate file list
        .set_parallel(5)                              # enable parallel execution with a thread pool of size 5
        .image_decode()                               # decode all images
        .image_embedding.timm(model_name='resnet50')  # compute image embeddings
        .tensor_normalize()                           # embeddings normalization
        .to_list()
)

print(embeddings)
```

in order to use the data collection API, you need to update to towhee 0.6 by 
```bash
$ pip install -U towhee
```

**Comment by fzliu** [comment]
> @fzliu @reiase towhee/image-embedding-regnetx-016 towhee=0.5.1 ![image](https://user-images.githubusercontent.com/46233536/162652851-9a40bb7a-59b6-41a4-abc8-8df59d10220e.png) The current test is the cpu server. Currently, both cpu and gpu servers are available. I don't know how to improve the utilization of server resources to speed up feature extraction

GPU auto-batching has already been implemented, but it hasn't been tested yet. It's in our roadmap for the next sub-release, i.e. 0.6.1. In the meantime, you can try @reiase's suggestion above to see if that improves performance.
