### ISSUE TITLE
[DesignProposal]: towhee command line tool for pipeline serve 

### ISSUE THREAD

**Issue by reiase** [towhee-io/towhee#1070]
### Background and Motivation

There are many predefined pipelines and operators on towhee hub. The users may want to deploy the pipelines and operators to cloud platforms.

### Design

Provide a command-line tool for pipeline/operator serving:

```shell
$ towhee serve -h 127.0.0.1 -p 8080 -r /app/myop towhee/image-embedding
```

towhee serve [-h host] [-p port] [-r route] [-D arg=val -D arg=val] pipeline/operator_name

**Comment by GuoRentong** [comment]
lgtm
