### ISSUE TITLE
gpu support problem

### ISSUE THREAD

**Issue by chrisyoung123** [towhee-io/towhee#1081]
```
my code are:

class resnet50:
       def __init__(self):
             self.embedding_pipeline = pipeline('image-embedding')
        def resnet50_extract_feat(self, img_path)
               img = Image.open(img_path)
               feat = self.embedding_pipleline(img)
               return feat

model = resnet50()
for file in os.path.listdir(srcdir):
       feat = model.resnet50_extract_feat(os.path.join(srcdir,file))

the code works fine, but when I run the command 'nvidia-smi', no change 
no gpu memory increse, the code excute very slow, seems not using gpu,
so I check the code, in towhee/engine/engine.py line 110:
dev_names = ['cpu:0']
change this line to
dev_names = ['gpu:0']
nothing chage, here is my computer enviroment
cuda 10.1
torch  1.6.0+cu101
ubuntu 18.04
```

**Comment by fzliu** [comment]
Hey @chrisyoung123, welcome to the Towhee community. GPU auto-batching (the ability to automatically compute embeddings on an NVIDIA GPU, if one is detected) is in our roadmap for the upcoming version. Can you tell us a bit more about your application? There may be other ways to speed up your code.

**Comment by chrisyoung123** [comment]
> Hey @chrisyoung123, welcome to the Towhee community. What your code changes have done is this: `copy image to GPU -> compute a single embedding vector -> copy result back to CPU -> repeat`. This is very inefficient and may actually perform worse than just doing everything on a CPU.
> 
> GPU auto-batching (the ability to simultaneously stream data and compute embeddings on an NVIDIA GPU, if one is detected) is in our roadmap for the upcoming version. Can you tell us a bit more about your application? There may be other ways to speed up your code prior to the next release.

i am tring to compute 100k imgs's embeding vector, and save them, if my changs make computing runing on gpu, it takes 4-5s ,how it that possible. vector is 8kB size, the whole should not take that long

**Comment by fzliu** [comment]
100k images will take quite a while on a CPU, depending on the model that you are using. #1123 introduces GPU auto-batching which should help.
