### ISSUE TITLE
[Documentation]: Towhee style guide link in contributing.md is broken.

### ISSUE THREAD

**Issue by omartarek206** [towhee-io/towhee#1085]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### When a user opens the [contributing.md](https://github.com/towhee-io/towhee/blob/main/CONTRIBUTING.md) file, then clicks on [Towhee style guide](https://github.com/towhee-io/towhee/STYLE_GUIDE.md) link.
![image](https://user-images.githubusercontent.com/40853054/163694075-5bb57f37-59ba-4c28-93d8-253ba4da537d.png)

### A  page saying "Not Found" is displayed.
![image](https://user-images.githubusercontent.com/40853054/163694081-f31662b6-9083-4a8c-99f6-24113c7cf84e.png)

### Expected Behavior

The page to the Towhee style guide should be shown.

### Steps To Reproduce

1. Open the [contributing.md](https://github.com/towhee-io/towhee/blob/main/CONTRIBUTING.md) page.
2. Click on [Towhee style guide](https://github.com/towhee-io/towhee/STYLE_GUIDE.md) link.

**Comment by omartarek206** [comment]
I have found another broken link in contributing.md which is get in touch link in line 11.
Both were modified in Pull request #1086

**Comment by fzliu** [comment]
@omartarek206 Welcome to the Towhee community. Your PR looks good - once CI/CD finishes, I'll merge your changes. Thanks for contributing!
