### ISSUE TITLE
[Feature]: new method for saving results

### ISSUE THREAD

**Issue by soulteary** [towhee-io/towhee#1093]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

hello maintainers 👋

I saw in the project that we can use the `show` method to display the results. But I didn't find a way to save these results.

https://github.com/towhee-io/towhee/blob/531b7144e2aec2b6e84d6b18351c509eb80cbb26/towhee/functional/mixins/display.py#L140-L162

Are you considering adding a method that can make it easier for users to directly save the displayed results?

Perhaps the user can specify the type of files to save, the directory location, and whether to package the result through parameters.

Would love to hear other people's thoughts and suggestions.

**Comment by reiase** [comment]
@soulteary We have just implemented a `to_csv` method, you can make a try.
