### ISSUE TITLE
[Bug]:  Buildin op dependence

### ISSUE THREAD

**Issue by junjiejiangjjj** [towhee-io/towhee#1100]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![yCMpn24V8P](https://user-images.githubusercontent.com/14136703/164144970-38b49c22-3b34-44fa-9a3b-2bde7809df5e.png)

My pipeline doesn't use buildin operators but occurs this error.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by Chiiizzzy** [comment]
It is an expected result because we don't want to introduce scipy as towhee's dependency. Therefore we raise such Error and tell users to manually install scipy.
