### ISSUE TITLE
[Enhancement]: Support GPU in data collection

### ISSUE THREAD

**Issue by reiase** [towhee-io/towhee#1158]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Support GPU in data collection, for example:

```python
towhee.range(10) \
    .CPU.image_decode() \
    .GPU(0).image_embedding.vgg() \
    .to_list()
```

**Comment by filip-halt** [comment]
wouldnt it have to be something like GPU[0].towhee.image_embedding(). Is callholder able to look indefinitely deep?

**Comment by reiase** [comment]
It can't, but we can modify the call holder if necessary.
