### ISSUE TITLE
[DesignProposal]: Batch operations for entities.

### ISSUE THREAD

**Issue by reiase** [towhee-io/towhee#1168]
### Background and Motivation

1. DataCollection support `batch` and `rolling` operations;
2. There lacks a field-awared batching for entities;

### Design

1. batching;

``` python
>>> towhee.range(4).batch(2)
[[0,1], [2, 3]]
```

2. rolling:

```python
>>> towhee.range(4). rolling(2)
[[0, 1], [1, 2], [2, 3]]
```

3. entity_batch:

```python
# batch of entities
>>> towhee.dc['x']([0,1,2,3]).batch(2)
[[{x:0}, {x:1}], [{x:2}, {x:3}]]

# batch for each field of the entity
>>> towhee.dc['x']([0,1,2,3]). entity_batch(2)
[{x:[0,1]}, {x:[2,,3]}]
```

4. group_by:
```python
>>> towhee.dc([{x: 1, y: 2}, {x:1, y:3}, {x:2, y:4}]).group_by['x']()
[{x: 1, y: [2, 3]}, {x: 2, y: [4]}]
```

**Comment by GuoRentong** [comment]
it seems that batch and rolling are the same functionality with different steps.

**Comment by reiase** [comment]
> it seems that batch and rolling are the same functionality with different steps.

Yea, pandas support both `batch` and `rolling`.
