### ISSUE TITLE
[Bug]: The requirements are not downloaded (No module name scipy)

### ISSUE THREAD

**Issue by krishnakatyal** [towhee-io/towhee#1182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when towhee is installed on a new system the required dependencies do not get installed 
This issue is same as [this issue  
](https://github.com/towhee-io/towhee/issues/952)

### Steps To Reproduce

```markdown
make a new env and run any operator
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: i7 16gb ram
- GPU:rtx 1050ti nvedia
- Others:nothing
```

**Comment by fzliu** [comment]
#1186
