### ISSUE TITLE
[Documentation]: Add link of coverage report at README

### ISSUE THREAD

**Issue by jaelgu** [towhee-io/towhee#1183]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

Broken links at README: pylint & coverage (404)
- coverage link: (open as public &) add coverage report from codecov: https://app.codecov.io/gh/towhee-io/towhee
- Add some link to pylint as well.

<img width="893" alt="image" src="https://user-images.githubusercontent.com/86251631/166931941-966f077b-9718-490e-a28a-db38ef0e057c.png">

### Why is this needed?

Broken links at README are weird.

**Comment by fzliu** [comment]
Fixed via #1212.
