### ISSUE TITLE
Implement Callstack class at compile/utils/callstack.py

### ISSUE THREAD

**Issue by Chiiizzzy** [towhee-io/towhee#12]
complete a call stack class, which includes the following functions:

- collect function, collect all the frames of the current call stack
- num_frmes, return the number of frames in the current stack
- find_func, given a function name, find the first match from the outermost frame in the stack, return its index
- hash, given the start and end indexes and an items list, return the hash value of the attributes in the items list between start and end.

**Comment by cxytz01** [comment]
hello,test.

**Comment by cxytz01** [comment]
hello,test.
