### ISSUE TITLE
[Bug]: 504 Server Error: Gateway Time-out for url: https://hub.towhee.io/api/v1/repos/towhee/image-decode/commits?limit=1&page=1&sha=main

### ISSUE THREAD

**Issue by xwy2258** [towhee-io/towhee#1201]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 towhee.glob(img_path) \
                         .image_decode()

运行这里时，发生错误
504 Server Error: Gateway Time-out for url: https://hub.towhee.io/api/v1/repos/towhee/image-decode/commits?limit=1&page=1&sha=main

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by fzliu** [comment]
Please bear with us as we roll out a fix. I'll post here as soon as that's done.

**Comment by jaelgu** [comment]
Updated behavio with towhee 0.6.0:
- with vpn: all good
- without vpn: connection refused (fail to download operator `image-decode/cv2` to local)

@junjiejiangjjj @reiase @fzliu Please take a look at this.

**Comment by fzliu** [comment]
@xwy2258 @hyyz17200 Can you try again? Our hub should be working normally now.

**Comment by hyyz17200** [comment]
> @xwy2258 @hyyz17200 Can you try again? Our hub should be working normally now.

Yeah it's working. In fact it was recovered, a few hours after my reply. 

Thanks!

**Comment by binbinlv** [comment]
@hyyz17200 
hello, could you please close this issue if it has been fixed now, thanks.

**Comment by xwy2258** [comment]
thank you

**Comment by hyyz17200** [comment]
Please check this issue, my personal solution may solve this issue too:

https://github.com/milvus-io/bootcamp/issues/1125
