### ISSUE TITLE
[Enhancement]: Redirect `hub.towhee.io` to `towhee.io`

### ISSUE THREAD

**Issue by fzliu** [towhee-io/towhee#1221]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Redirect `hub.towhee.io` -> `towhee.io`.

### Why is this needed?

`hub.towhee.io` displays an empty list of operators and pipelines. Adding an automatic redirect to `towhee.io` will reduce confusion.

**Comment by aadityasinha-dotcom** [comment]
Can I work on this issue?

**Comment by fzliu** [comment]
This update will require changes external to this repo, but there are other ways that you can help out, if you're still interested. We maintain a list of good first issues here: https://github.com/towhee-io/towhee/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22.
