### ISSUE TITLE
[Documentation]:  This tutorial should be updated to the latest build_image_search_engine

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#1261]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

In our official website:

https://docs.towhee.io/Tutorials/Computer%20Vision/reverse-image-search/

The tutorial is just the old example, and we constructed the examples in 0.6.1, so should we replace this tutorial with the new one using the new example?

The **milvus version** and `pymilvus version` in the demo are too old

<img width="1204" alt="截屏2022-05-18 18 48 56" src="https://user-images.githubusercontent.com/34296482/169022280-42c9c642-198e-459c-8b71-b7df89c4bbf0.png">

**Comment by binbinlv** [comment]
@reiase @shiyu22 could you please help to have a look at this issue? Thanks.

**Comment by binbinlv** [comment]
@jingkl 

could you please help to verify this issue, and please close it if it is fixed.

**Comment by jingkl** [comment]
<img width="855" alt="截屏2022-05-20 10 56 12" src="https://user-images.githubusercontent.com/34296482/169441310-bc64da84-55b0-4b2a-8131-dceff025e55e.png">
Already fixed, turn off issue
