### ISSUE TITLE
[Bug]: to_milvus unstream is unnecessary and causes OOM

### ISSUE THREAD

**Issue by filip-halt** [towhee-io/towhee#1270]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

to_milvus unstreams, causing a memory bottleneck. If inserting 100,000 images into milvus, the pipeline should be streamed. 

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by shiyu22** [comment]
`to_milvus` is unstream by default, in order to support inserting different data into different collections:
```bash
(
	towhee.glob['path']('./train/*/*.JPEG')
		.image_decode['path', 'img']()
		.image_embedding.timm['img', 'vec'](model_name='resnet50')
                 .image_embedding.timm['img', 'vec'](model_name='resnet101')
		.runas_op['path', 'label'](func = lambda path: path.split('/')[-2])
		.runas_op['path', 'path'](func=lambda path: abs(hash(path)) % (10 ** 8))
		.to_milvus['path', 'vec'](collection=collection_res50, batch=100)
                .to_milvus['path', 'vec'](collection=collection_res101, batch=100)
)
```

And anyone can add unstream=False to change the mode when using to_milvus, like `.to_milvus['id', 'vec'](collection=collection, batch=100, unstream=False)`.

**Comment by shiyu22** [comment]
The default `unstream` mode may work for demos, how do you think? @filip-halt @reiase

**Comment by reiase** [comment]
> The default `unstream` mode may work for demos, how do you think? @filip-halt @reiase

can we fix that by returning another DC in `to_milvus `
