### ISSUE TITLE
using pip install -u when downloading packages

### ISSUE THREAD

**Issue by reiase** [towhee-io/towhee#1278]
I was originally going to do this but then I didnt because using -u will mess up if the user is using a virtual_env

_Originally posted by @filip-halt in https://github.com/towhee-io/towhee/pull/1269#discussion_r878576884_

**Comment by reiase** [comment]
When installing packages with pip, we should consider `--user` option if the user is using a system python, but we should install the package without `--user` option if the user is using a virtual env.

We need to discuss the detail behavior of package install. @GuoRentong @junjiejiangjjj @fzliu @filip-halt

**Comment by GuoRentong** [comment]
> When installing packages with pip, we should consider `--user` option if the user is using a system python, but we should install the package without `--user` option if the user is using a virtual env.
> 
> We need to discuss the detail behavior of package install. @GuoRentong @junjiejiangjjj @fzliu @filip-halt

we can provide such control flexibility via environment variables

**Comment by reiase** [comment]
> > When installing packages with pip, we should consider `--user` option if the user is using a system python, but we should install the package without `--user` option if the user is using a virtual env.
> > We need to discuss the detail behavior of package install. @GuoRentong @junjiejiangjjj @fzliu @filip-halt
> 
> we can provide such control flexibility via environment variables

does the user have to restart ipython kernel when he is using jupyter notebook to set the environment variables?
