### ISSUE TITLE
[Bug]: AudioDecoder gets really slow processing the audio file

### ISSUE THREAD

**Issue by sberenson** [towhee-io/towhee#1289]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When we run inference many times on different audio files we see that AudioDecoder __call__ method eventually gets really slow in iterating over the for loop. we identified it by adding logs in various places while trying to debug why the inference of the model ("__call__") is not executed.

The slowness we observed that it will take 1-2 sec to go over one iteration inside AudioDecoder __call__ function.

We were able to reproduce on local machine (Mac), on dedicated EC2 instance and inside kubernetes cluster.

When this issue starts happening we observe the memory (2.5G used out of 7.49G) and CPU usage ~2%- 5% (4 cores available)

### Expected Behavior

We expect consistent behavior from AudioDecoder. 

### Steps To Reproduce

```markdown
1. Use embedding_pipeline = pipeline('towhee/audio-embedding-vggish')
2. Call vecs = embedding_pipeline(str(audio_path))
3. In our tests we provide 10 min wav audio files mono, 16Mhz
4. Wrap the embedding_pipeline into FastAPI endpoint.
5. Either using Gunicorn or Uvicorn start the web server :

"gunicorn fingerprint:app --workers 1 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000"

6. Using curl just call the endpoint with same file over and over
```

### Environment

```markdown
- Towhee version: 0.6.0
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: 4 CPU cores available. 7.5 GB Memory available
- GPU: Using AWS Infernia chip instead
- Others: Runs inside kubernetes 1.22 Pod, only one pod runs on the was inf1.xlarge instance.
```

**Comment by binbinlv** [comment]
@jaelgu 

Could you help to have a look first?

**Comment by fzliu** [comment]
@sberenson Just to clarify, calls to `AudioDecoder` become slower and slower the more times `pipeline` is called, correct?

**Comment by fzliu** [comment]
I also saw that you're using `inf1` instances on EC2 - we've never tested it on our end, but if you ran into any issues there let us know and I'd be happy to help out there as well.

**Comment by sberenson** [comment]
@fzliu correct.
Regarding inf1 instances, I had to recompile the model on the inf instance to generate the model and tweaked the vggish implementation to leverage inf1 chip if it present. Gets way better performance vs cpu mode.

**Comment by jaelgu** [comment]
@junjiejiangjjj Can you take a look at this issue regarding to audio-decoder?

**Comment by junjiejiangjjj** [comment]
```python
from towhee.engine.engine import EngineConfig

config = EngineConfig()
config.sched_threshold = 10000000
```
Please add this code and try again.   Towhee would slow down the  `AudioDecoder ` if there are lots of audio frame, the config will change the threshold. @sberenson

**Comment by sberenson** [comment]
thank you @junjiejiangjjj it seems to solve the problem, let it run for few hours and didnt experience it anymore.

**Comment by sberenson** [comment]
The solution proposed by @junjiejiangjjj fixes the slowness
