### ISSUE TITLE
[Bug]: Pytorchvideo: fail to load mvit model with provided weights

### ISSUE THREAD

**Issue by aiot-tech** [towhee-io/towhee#1292]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when running the code,
```
import towhee

(
    towhee.glob('datasets/1.mp4')
          .video_decode.ffmpeg()
          .video_classification.video_classification(model_name='mvit_base_16x4', return_vec=True)
)
```
some errors are occurred:
```
[Errno 2] No such file or directory: '/root/.towhee/hub/video-decode/ffmpeg/main/ffmpeg.py'

During handling of the above exception, another exception occurred:
...
...
...
/root/.towhee/hub/video-decode/ffmpeg/main/video_decoder.py in <module>()
      9 import numpy as np
     10 
---> 11 from towhee.types.video_frame import VideoFrame
     12 from towhee.operator.base import PyOperator
     13 

ModuleNotFoundError: No module named 'towhee.types.video_frame'

```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):v0.6.1
- OS(Ubuntu or CentOS):Ubuntu16.04
```

**Comment by binbinlv** [comment]
@junjiejiangjjj 

Could you please have a look at this issue? Thanks.

**Comment by junjiejiangjjj** [comment]
> @junjiejiangjjj
> 
> Could you please have a look at this issue? Thanks.

The `video_decode.ffmpeg()` should use the newest towhee code,  please git clone towhee and run `python setup.py install` to install towhee.

**Comment by aiot-tech** [comment]
thx for the reply! when I run the code you provided, some new errors occur:
```
git_utils.py-git_utils:94 - ERROR: video-classification/video-classification repo does not exist.
...
...
ValueError: video-classification/video-classification repo does not exist.
The above exception was the direct cause of the following exception:
...
...
ValueError: operator video-classification/video-classification not found!
```

**Comment by aiot-tech** [comment]
now I run the code as shown below:
```
import towhee

(
    towhee.glob('datasets/1.mp4')
          .video_decode.ffmpeg()
          .video_classification(model_name='mvit_base_16x4', return_vec=True)
)

```
and a new error occurs:
```
git_utils.py-git_utils:94 - ERROR: towhee/video-classification repo does not exist.
......
ValueError: towhee/video-classification repo does not exist.
The above exception was the direct cause of the following exception:
ValueError: operator towhee/video-classification not found!
```

**Comment by jaelgu** [comment]
@aiot-tech You can check the updated REAMDE here: https://towhee.io/video-classification/pytorchvideo I've just updated and fixed typo there.

**Comment by jaelgu** [comment]
@aiot-tech Actually most video operators are going to release in next version. Please understand that some of READMEs are not yet reviewed. But I've just updated the README for https://towhee.io/video-classification/pytorchvideo . Lemme know if there's still some confusion.

**Comment by aiot-tech** [comment]
and when I run code like in the [example](https://towhee.io/video-classification/pytorchvideo)
```
import towhee

(
    towhee.glob('datasets/1.mp4')
          .video_decode.ffmpeg()
          .video_classification.pytorchvideo(model_name='mvit_base_16x4', return_vec=True)
)
```
and a new exception has occurred
```
ModuleNotFoundError: No module named 'towhee.models'

During handling of the above exception, another exception occurred:

```

**Comment by jaelgu** [comment]
> and when I run code like in the [example](https://towhee.io/video-classification/pytorchvideo)
> 
> ```
> import towhee
> 
> (
>     towhee.glob('datasets/1.mp4')
>           .video_decode.ffmpeg()
>           .video_classification.pytorchvideo(model_name='mvit_base_16x4', return_vec=True)
> )
> ```
> 
> and a new exception has occurred
> 
> ```
> ModuleNotFoundError: No module named 'towhee.models'
> 
> During handling of the above exception, another exception occurred:
> ```

This is because `towhee.models` are separated from `towhee` packages. You need to install towhee.models package with latest code as well. In the same towhee github repo, use `python setup.py install --models`

**Comment by aiot-tech** [comment]
After running the code  as shown above, a new exception occurs:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-d1f240e6247f> in <module>()
      4     towhee.glob('datasets/1.mp4')
      5           .video_decode.ffmpeg()
----> 6           .video_classification.pytorchvideo(model_name='mvit_base_16x4', extract_features=True)
      7 )
.......
RuntimeError: Error(s) in loading state_dict for MultiscaleVisionTransformers:
	Missing key(s) in state_dict: "blocks.0.attn._attention_pool_k.pool.weight",
```

**Comment by jaelgu** [comment]
> After running the code as shown above, a new exception occurs:
> 
> ```
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-1-d1f240e6247f> in <module>()
>       4     towhee.glob('datasets/1.mp4')
>       5           .video_decode.ffmpeg()
> ----> 6           .video_classification.pytorchvideo(model_name='mvit_base_16x4', extract_features=True)
>       7 )
> .......
> RuntimeError: Error(s) in loading state_dict for MultiscaleVisionTransformers:
> 	Missing key(s) in state_dict: "blocks.0.attn._attention_pool_k.pool.weight",
> ```

This is weird. What is your torch version? Also can you try to run the following codes in your environment:
```
import torch

model = torch.hub.load('facebookresearch/pytorchvideo', model='mvit_base_16x4' pretrained=True)
```

**Comment by aiot-tech** [comment]
the same error:```RuntimeError: Error(s) in loading state_dict for MultiscaleVisionTransformers:
	Missing key(s) in state_dict: "blocks.0.attn._attention_pool_k.pool.weight",```

**Comment by jaelgu** [comment]
> the same error:`RuntimeError: Error(s) in loading state_dict for MultiscaleVisionTransformers: Missing key(s) in state_dict: "blocks.0.attn._attention_pool_k.pool.weight",` and the ckpt `torch.load("/root/.cache/torch/hub/checkpoints/MVIT_B_16x4.pyth")` can be loaded correctly.Maybe some keys dont match the model?

It should be matched. Can you try to remove `/root/.cache/torch/hub/checkpoints/MVIT_B_16x4.pyth` and re-run `torch.hub.load('facebookresearch/pytorchvideo', model='mvit_base_16x4' pretrained=True)`?

**Comment by aiot-tech** [comment]
Yes,I had did and the same error occurred again.

**Comment by jaelgu** [comment]
> Yes,I had did and the same error occurred again.

What is your torch version?

**Comment by aiot-tech** [comment]
I test it on both v1.11.0(gpu) and 1.10.2(cpu)

**Comment by aiot-tech** [comment]
When I run the code as shown below,the same error occurs,so it seems to be a problem from the repo  of  `pytorchvideo`?
```
import torch

model = torch.hub.load('facebookresearch/pytorchvideo', model='mvit_base_16x4')
ckpt = torch.load("/root/.cache/torch/hub/checkpoints/MVIT_B_16x4.pyth")
model.load_state_dict(ckpt["model_state"])
```

**Comment by jaelgu** [comment]
> When I run the code as shown below,the same error occurs,so it seems to be a problem from the repo of `pytorchvideo`?
> 
> ```
> import torch
> 
> model = torch.hub.load('facebookresearch/pytorchvideo', model='mvit_base_16x4')
> ckpt = torch.load("/root/.cache/torch/hub/checkpoints/MVIT_B_16x4.pyth")
> model.load_state_dict(ckpt["model_state"])
> ```

It looks like problem with pytorchvideo. I also checked with weight in my cache as well:
<img width="819" alt="image" src="https://user-images.githubusercontent.com/86251631/170469701-ccade450-f11b-4d79-a8f1-eb6af18ecb31.png">

Can you try to check your model with this:
```
import torch

model = torch.hub.load('facebookresearch/pytorchvideo', model='mvit_base_16x4', pretrained=False)
state_dict = model.state_dict()
'blocks.0.attn._attention_pool_k.pool.weight' in state_dict
```
The above code should return False. Can you check at your end?

**Comment by jaelgu** [comment]
@aiot-tech I can reproduce this issue by removing `~/.cache/torch/hub/facebookresearch_pytorchvideo_main` and making it re-download pytorchvideo with torch.hub.

It looks like an issue with some updates in https://github.com/facebookresearch/pytorchvideo.

**Comment by aiot-tech** [comment]
> import torch
> 
> model = torch.hub.load('facebookresearch/pytorchvideo', model='mvit_base_16x4', pretrained=False)
> state_dict = model.state_dict()
> 'blocks.0.attn._attention_pool_k.pool.weight' in state_dict

```
In [1]: import torch
   ...: 
   ...: model = torch.hub.load('facebookresearch/pytorchvideo', model='mvit_base_16x4', pretrained=False)
   ...: state_dict = model.state_dict()
   ...: 'blocks.0.attn._attention_pool_k.pool.weight' in state_dict
   ...: 

Using cache found in /root/.cache/torch/hub/facebookresearch_pytorchvideo_main
Out[1]: True
```
In my local environment, it returns True.

**Comment by jaelgu** [comment]
@aiot-tech Hello, I've actually submitted an issue to pytorchvideo. Hope they will fix it officially soon. However, I have a workaround:

```
cd  ~/.cache/torch/hub
mv facebookresearch_pytorchvideo_master pytorchvideo_bak
git clone https://github.com/facebookresearch/pytorchvideo.git facebookresearch_pytorchvideo_master
cd facebookresearch_pytorchvideo_master
 git checkout tags/0.1.3
```
(Note: make sure your torch used the correct cache dir. Sometimes, it uses 'facebookresearch_pytorchvideo_main' instead.)

With commands above, we can replace the pytorchvideo code used by torch with a previous version (actually v0.1.3 is its latest released version). Then you can load mvit model with its given weights properly.

**Comment by aiot-tech** [comment]
thx for your great work!

**Comment by aiot-tech** [comment]
thx for your great work!
