### ISSUE TITLE
[Feature]: Update notebook for Image animation

### ISSUE THREAD

**Issue by shiyu22** [towhee-io/towhee#1303]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

There are some notebooks for reverse image search with the [gradio showcase](https://github.com/towhee-io/examples/blob/main/image/reverse_image_search/1_build_image_search_engine.ipynb) and [deploy fastapi with towhee.api](https://github.com/towhee-io/examples/blob/main/image/reverse_image_search/2_deep_dive_image_search.ipynb), can you update the notebook for [Image animation](https://github.com/towhee-io/examples/tree/main/image/image_animation)?

### Describe the solution you'd like.

- Build an image animation engine
    Run [Animegan](https://towhee.io/img2img-translation/animegan) or [Cartoongan](https://towhee.io/img2img-translation/cartoongan) to change the style of the image and release the Gradio showcase.

- Deep dive image animation
   Set up running pipelines in parallel and deploy fastapi services using `towhee.api`, it would be better if video animations could be supported.

**Comment by harivamsi9** [comment]
Hey, I wanna take up this issue

**Comment by shiyu22** [comment]
Welcome to contribute :)

Feel free to contact me if you have any questions, or join [slack](https://join.slack.com/t/towheeio/shared_invite/zt-19xhoo736-PhIYh~hwOBsDSy5ZvGWJxA) in the **development** channel to discuss.

**Comment by shiyu22** [comment]
Hi @harivamsi9, any progress to share? One thing is that there is a [simple notebook](https://github.com/towhee-io/examples/blob/tutorial/image/image_animation/anime_style_transformer.ipynb) about anime-style transformers you can refer to.

**Comment by aadityasinha-dotcom** [comment]
Is this issue available? 
Can I work on this issue?

**Comment by harivamsi9** [comment]
Hey, I am still working on this issue

**Comment by aadityasinha-dotcom** [comment]
ok

**Comment by aadityasinha-dotcom** [comment]
any uodate?
