### ISSUE TITLE
[Bug]: iterators.py exception AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by sberenson** [towhee-io/towhee#1305]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I trigger:

embedding_pipeline = pipeline('towhee/audio-embedding-vggish')
vecs = embedding_pipeline(str(audio_path))  

sequentially 50 times it works as expected.
If we run 50 requests in 4 parallel jobs getting the following exception:

Traceback (most recent call last):
  File "/root/.towhee/./fingerprint.py", line 58, in main_func
    vecs = embedding_pipeline(str(audio_path))
  File "/usr/local/lib/python3.8/dist-packages/towhee/__init__.py", line 104, in __call__
    return format_handler(out_df)
  File "/usr/local/lib/python3.8/dist-packages/towhee/pipeline_format.py", line 57, in __call__
    for data in itr:
  File "/usr/local/lib/python3.8/dist-packages/towhee/dataframe/iterators.py", line 104, in __next__
    code, row, _ = df.get(self._offset, count = self._batch_size, iter_id = self._id)
AttributeError: 'NoneType' object has no attribute 'get'

### Expected Behavior

Expected the pipeline to process the files in parallel and apply locks on any shared resources or not to have shared resources between processing different input files.

### Steps To Reproduce

```markdown
1. Take a mono 16000 Mhz wav file.
2. use embedding_pipeline = pipeline('towhee/audio-embedding-vggish')
3. Execute embedding_pipeline in parallel many times.
We did it by wrapping the code into FastAPI endpoint and curl the endpoint in parallel.
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.6.1
- OS(Ubuntu or CentOS): Ubuntu 20.04
- CPU/Memory: 4CPU, 8 GB Memory
- GPU: none
- Others: Inference on aws Inf1 instance.
```

**Comment by junjiejiangjjj** [comment]
@filip-halt  #823   in this pr, the `GraphContext.result()`  returns an iterator, not a `dataframe`, the iter only has df's weakref, when the `GraphContext` destroy, all dfs will be destroyed too, so the iter gets the `None` not the df.

**Comment by sberenson** [comment]
@filip-halt here is the fingerprint.py script : [fingerprint.py.txt](https://github.com/towhee-io/towhee/files/8808819/fingerprint.py.txt)
save it to file and then you can execute it 
`uvicorn fingerprint:app --port=8000 --reload --workers=4`


to call it in parallel:

`
xargs -I % -P 4 curl -w "@curl-format.txt" -o /dev/null  --request POST 'http://localhost:8000/fingerprint' \
--header 'Content-Type: application/json' \
--data-raw '{
    "audio_path":"{full path to your test file}",
    "output_path":"{full path to output json file it will save}"
}' < <(printf '%s\n' {1..50})
`

**Comment by sberenson** [comment]
@filip-halt I have tested the fix by applying the same changes on local. How would you recommend to get the latest changes? When is the plan for next tag 0.6.2 ?

**Comment by binbinlv** [comment]
@sberenson 

I think you could use the version on "test pypi" temporarily before 0.6.2 using the following command:

pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple towhee==0.6.2.dev46
