### ISSUE TITLE
[Bug]: CPU OOM Error

### ISSUE THREAD

**Issue by aiot-tech** [towhee-io/towhee#1328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
ret = []
ret.append(towhee.glob("mp4/*.mp4") \
    .video_decode.ffmpeg() \
    .video_classification.pytorchvideo( \
    model_name='x3d_m', predict=False).to_list())
```
When running the code as above, I get a `cpu oom` error, is there any solution? And the dir `mp4/` contains more than 1k videos.
the oom error is:
```
[enforce fail at alloc_cpu.cpp:73] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 12830400000 bytes. Error code 12 (Cannot allocate memory)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.6.2.dev42(build from git source code)
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
@junjiejiangjjj 

Could you help to investigate this issue? Thanks.

**Comment by junjiejiangjjj** [comment]
How big are your videos? the pipeline only supports small videos.

**Comment by aiot-tech** [comment]
Most of them are less than 1024k. Is it possible to build a pipeline in style like below:
```
from towhee import pipeline
embedding_pipeline = pipeline('towhee/audio-embedding-vggish')
```

**Comment by reiase** [comment]
> Most of them are less than 1024KB. Is it possible to build a pipeline in style like below:
> 
> ```
> from towhee import pipeline
> embedding_pipeline = pipeline('towhee/audio-embedding-vggish')
> ```

Still working on that, we aim to provide an API like this:
```
ret = towhee.glob("mp4/*.mp4").audio_embedding_vggish().to_list()
```
where `audio_embedding_vggish` is the pipeline name.

**Comment by jaelgu** [comment]
@aiot-tech We have more example usage of this operator in https://github.com/towhee-io/examples/tree/main/video/reverse_video_search (More examples on the way). You may move the audio-subsampling step to audio-decode using sample codes below:

```
(
    towhee.glob("mp4/*.mp4")
                .video_decode.ffmpeg(sample_type='uniform_temporal_subsample', args={'num_samples': 16})
                .video_classification.pytorchvideo(model_name='x3d_m', predict=False, skip_preprocess=True)
)
```

**Comment by aiot-tech** [comment]
Now I do it like this, first delete self.model and inputs after inference `(/root/.towhee/hub/video-classification/pytorchvideo/main/pytorchvideo.py)`, then use the following code to process 800 videos (total 1000), it seems that there is no problem, but it is a bit slow.

```
ret = []
for p in paths:
    _tmp_ret = list(towhee.glob(p) \
        .video_decode.ffmpeg() \
        .video_classification.pytorchvideo( \
        model_name='x3d_m', predict=False))
    ret.append(_tmp_ret)
```

**Comment by aiot-tech** [comment]
> > Most of them are less than 1024KB. Is it possible to build a pipeline in style like below:
> > ```
> > from towhee import pipeline
> > embedding_pipeline = pipeline('towhee/audio-embedding-vggish')
> > ```
> 
> Still working on that, we aim to provide an API like this:
> 
> ```
> ret = towhee.glob("mp4/*.mp4").audio_embedding_vggish().to_list()
> ```
> 
> where `audio_embedding_vggish` is the pipeline name.

Great! Hope to use it soon.

**Comment by aiot-tech** [comment]
I get an another idea. First, move `/root/.towhee/hub/video-classification/pytorchvideo/main/pytorchvideo.py` to `PytorchVideo.py`, same for json, and then run the code below
```
from PytorchVideo import PytorchVideo
from towhee import ops
from tqdm import tqdm
import numpy as np

d = ops.video_decode.ffmpeg()
model = PytorchVideo(model_name='x3d_m', predict=False)

ret = []
for p in tqdm(paths):
    ret.append(model(list(d(p))))
```

**Comment by jaelgu** [comment]
> I get an another idea. First, move `/root/.towhee/hub/video-classification/pytorchvideo/main/pytorchvideo.py` to `PytorchVideo.py`, same for json, and then run the code below
> 
> ```
> from PytorchVideo import PytorchVideo
> from towhee import ops
> from tqdm import tqdm
> import numpy as np
> 
> d = ops.video_decode.ffmpeg()
> model = PytorchVideo(model_name='x3d_m', predict=False)
> 
> ret = []
> for p in tqdm(paths):
>     ret.append(model(list(d(p))))
> ```

Then how about this:

```
import tqdm
from towhee import ops

op1 = ops.video_decode.ffmpeg(sample_type='uniform_temporal_subsample', args={'num_samples': 16}) 
op2 = ops.video_classification.pytorchvideo(model_name='x3d_m', predict=False, skip_preprocess=True)
res = []
for p in tqdm(paths):
    frames = op1(p)
    re = op2(frames)                
    res.append(re)
```

**Comment by aiot-tech** [comment]
brilliant!
