### ISSUE TITLE
[Bug]: .dc() fails to work with more than one column

### ISSUE THREAD

**Issue by filip-halt** [towhee-io/towhee#1329]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

import towhee
dc = towhee.dc\(\["num","val"\](\[\[1,"one"\],\[2,"two"\]\]\)

Throws an error. 

Fix
return DataFrame(iterable).map(lambda x: Entity(**{index: x})) -------> return DataFrame(iterable).map(lambda x: Entity(**dict(zip(index, x))))

### Expected Behavior

To get a dc with two columns.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
@filip-halt 
Could you help to verify this?

And please close it if it is fixed. Thanks.
