### ISSUE TITLE
[DesignProposal]: refactoring towhee.api

### ISSUE THREAD

**Issue by reiase** [towhee-io/towhee#1332]
### Background and Motivation

`towhee.api` was originally designed to help the user to create an API for their application. For example, the user can create a RestFul API with the following code:

```
with towhee.api() as api:
    api.image_decode() \
        .image_embedding() \
        .search_milvus() \
        .serve(app, '/image/search')
```

or create a API function with:

```
with towhee.api() as api:
    api.image_decode() \
        .image_embedding() \
        .search_milvus() \
        .as_function()
```

we want to improve the design of the API, make the user's code much simpler.

### Design

we drop the with statement from the user's code and provide `towhee.dummy_input` as place holder for the data input:
```
towhee.dummy_input() \
        .image_decode() \
        .image_embedding() \
        .search_milvus() \
        .as_serve(app, '/image/search')
```

or 

```
towhee.dummy_input() \
        .image_decode() \
        .image_embedding() \
        .search_milvus() \
        .as_func()
```

### Pros and Cons

1. does `towhee.dummy_input` make the code simple and clear?
2. does `towhee.api` make the purpose of the API much clear to the user? The API is designed for helping the users to create their own API based on towhee?

**Comment by filip-halt** [comment]
Maybe instead of dummy input something like 'dynamic_input'

**Comment by reiase** [comment]
> Maybe instead of dummy input something like 'dynamic_input'

sounds much better

**Comment by shiyu22** [comment]
Does it support passing in multiple values? Such as `towhee.dummy_input['question', 'answer']()`.

**Comment by jaelgu** [comment]
Does `.dummy_input` support batch or single input? If using batch, will it easily cause OOM?
