### ISSUE TITLE
[Bug]: 不支持windows吗？ TypeError: argument of type 'WindowsPath' is not iterable

### ISSUE THREAD

**Issue by jandy0414** [towhee-io/towhee#1350]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

run resNet50 for  vector

### Expected Behavior

finish run

### Steps To Reproduce

```markdown
see the pic
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.6
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:     Python 3.6.2
```

### Anything else?

![bug001](https://user-images.githubusercontent.com/35617197/172976205-5a201bd9-5352-4ffb-afb9-bd8a43aea6cf.png)

**Comment by binbinlv** [comment]
@jaelgu 
Could you have a look at this issue? thanks.

**Comment by jaelgu** [comment]
@jandy0414 Can you try to modify your path with options below:
- option 1: r'D:\x\x\img.png'
- option 2: str(os.path.join(''D:/, 'x', 'img.png'))
