### ISSUE TITLE
[Bug]: VGGish pipeline waveform_to_examples func converts to mono input file that is already in mono

### ISSUE THREAD

**Issue by sberenson** [towhee-io/towhee#1361]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When you provide an input file that is already mono :
`    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s`
the function waveform_to_examples still will convert it the input data into mono again by looking into 
`if len(data.shape) > 1:
      data = np.mean(data, axis=1)
`

### Expected Behavior

Expected the pipeline to detect that the input file is already mono and not to convert to mono again.

### Steps To Reproduce

```markdown
1. Using ffmpeg tool convert a test audio file to mono
2. Run :
`
embedding_pipeline = pipeline('towhee/audio-embedding-vggish')
vecs = embedding_pipeline(str(audio_path))
`
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.6.1
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jaelgu** [comment]
/fixed by latest pipeline: https://towhee.io/towhee/audio-embedding-vggish (with change in related operators)
