### ISSUE TITLE
[Enhancement]: to_milvus operator must return the primary keys

### ISSUE THREAD

**Issue by paul-tharun** [towhee-io/towhee#1366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The present behavior in milvus mixins is to store the result of the milvus insert into a dummy variable and not return anything. 
` _ = _milvus_insert(dc_data, index, collection, batch_size)` line 89 in milvus mixins file. 

I believe returning the primary keys that can be added to the data collection would be better as it would allow users to use auto_id in milvus primary keys.

### Why is this needed?

Present version of milvus (2.0.2) does not support `STRING` data type , so the preferred way of storing data related to the vectors in milvus is using an external database like postgre or mysql and mapping that data to the primary keys in milvus. 

While using a towhee pipeline in this set up the two options user has are 
1. Define the primary keys in the pipeline and then map them to external database. (auto_id of primary key cannot be used as the keys are not returned to be stored in the external database)
2. Handling the milvus insertion outside the pipeline. 

Both of these aren't ideal and add an extra overhead.
Returning primary keys would enable users to use auto_id for primary keys and handle milvus insertion in pipeline.

**Comment by paul-tharun** [comment]
This makes better sense, I did not know about the ann_insert operator. I am closing this issue then as there isn't an enhancement. Thanks for the help.

**Comment by shiyu22** [comment]
It's my pleasure. And one thing is that we are going to make `to_milvus` to Operator and it will solve your issue and plans to deprecate `ann_insert`. I think @filip-halt is doing this, can you comment on this if you finished it?
