### ISSUE TITLE
[Bug]: ffmpag.py not found

### ISSUE THREAD

**Issue by Chiiizzzy** [towhee-io/towhee#1368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running:

```
dc = (
    towhee.read_csv(test_sample_csv_path)
      .runas_op['video_id', 'id'](func=lambda x: int(x[-4:]))
      .set_parallel(2)
      .video_decode.ffmpeg['video_path', 'frames'](sample_type='uniform_temporal_subsample', args={'num_samples': 12}) \
      .runas_op['frames', 'frames'](func=lambda x: [y for y in x]) \
      .video_text_embedding.clip4clip['frames', 'vec'](model_name='clip_vit_b32', modality='video', device=device) \
      .to_milvus['id', 'vec'](collection=collection, batch=30)
)
```
report `FileNotFoundError: [Errno 2] No such file or directory: '/Users/chizzy/.towhee/operators/video-decode/ffmpeg/main/ffmpeg.py'`

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by shiyu22** [comment]
I also met this issue before, but it's an issue about the version of towhee, I think you need to update the `towhee` and `towhee.models` to latest version. Note that you have to uninstall them before reinstall.

**Comment by Chiiizzzy** [comment]
> I also met this issue before, but it's an issue about the version of towhee, I think you need to update the `towhee` and `towhee.models` to latest version. Note that you have to uninstall them before reinstall.

I'm in develop mode, so technically it should be the latest towhee that I'm using(update to latest commit), also i tried to uninstall and install towhee from pypi, It's not working.

**Comment by shiyu22** [comment]
Maybe you need to remove the folder under site-packages, such as `rm -rf ~/miniconda3/envs/towhee/lib/python3.8/site-packages/towhee/*`. I can run it successfully after running this, although it's very confusing. -_-

**Comment by Chiiizzzy** [comment]
`VideoFrame` is not introduced in towhee 0.6.1, which is the latest version of towhee available in pypi. So when users install towhee from pypi and run operators with `VideoFrame` imported, they will encounter `ModuldNotFoundError`.

In this case, towhee is supposed to build a `VideoDecoder` operator from `video-decode/ffmpeg`'s `__init__.py`, where VideoFrame is imported by importing VideoDecoder, which caused error. So towhee will try to load op from path, i.e. find a file named `ffmpeg.py` in `video-decode/ffmpeg`, which does not exists, hence the bug.

**Comment by shiyu22** [comment]
You can find the latest version of towhee in [testpypi](https://test.pypi.org/project/towhee/#history). But the issue is that the Operator cannot run with the released towhee, maybe we need to add `develop` label in this Operator or Pipeline.
