### ISSUE TITLE
[Bug]: The code of towhee will be covered after the latest towhee.models are installed

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1378]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The code of towhee will be covered after the latest towhee.modes are installed

### Expected Behavior

The code of towhee will not be covered after the latest towhee.modes are installed

### Steps To Reproduce

1. install the latest towhee:
python3 -m pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple towhee==0.6.2.dev80

2. run code:
```python3
from towhee.utils.log import models_log
```

Result:
```
Do you want to install pyarrow? [y/n]: y
Collecting pyarrow
  Using cached pyarrow-8.0.0-cp38-cp38-macosx_10_13_x86_64.whl (22.4 MB)
Requirement already satisfied: numpy>=1.16.6 in ./towhee-test-env-3.8-0.7/lib/python3.8/site-packages (from pyarrow) (1.22.4)
Installing collected packages: pyarrow
Successfully installed pyarrow-8.0.0
pyarrow installed successfully!
```

3. install the latest towhee.models package:
pip install towhee.models-0.6.2.dev1-py3-none-any.whl

4. Run code again:
```python
from towhee.utils.log import models_log
```
Results:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'models_log' from 'towhee.utils.log' (/Users/binbin/Towhee_projects/towhee-test-env-3.8-0.7/lib/python3.8/site-packages/towhee/utils/log.py)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.6.2.dev80 (models package is built from the latest main branch)
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by reiase** [comment]
We have to clean the build cache before packaging `towhee.models`. @binbinlv

**Comment by binbinlv** [comment]
After rm directory "build" and "dist", this issue did not occur.
