### ISSUE TITLE
[Bug]: Fail to run pytorchvideo for "Remote end closed connection without response"

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Requirement already satisfied: portalocker in /test/miniconda3/envs/binbin-test-python-3.8/lib/python3.8/site-packages (from iopath->pytorchvideo==0.1.3->-r /home/super/.towhee/hub/action-classification/pytorchvideo/main/requirements.txt (line 1)) (2.4.0)
Building wheels for collected packages: pytorchvideo
  Building wheel for pytorchvideo (setup.py) ... done
  Created wheel for pytorchvideo: filename=pytorchvideo-0.1.3-py3-none-any.whl size=183830 sha256=a5605861589b3390792d8134082e43b37edf69176222f24a1ec35f40b8a0544f
  Stored in directory: /home/super/.cache/pip/wheels/7a/57/df/4fcc47d88542d6ecce755a7ccc8ceaa8edd65b378a7dc7d255
Successfully built pytorchvideo
Installing collected packages: pytorchvideo
  Attempting uninstall: pytorchvideo
    Found existing installation: pytorchvideo 0.1.5
    Uninstalling pytorchvideo-0.1.5:
      Successfully uninstalled pytorchvideo-0.1.5
Successfully installed pytorchvideo-0.1.3
2022-06-16 16:03:39,983 - 139986425451328 - test_action_classification.py-test_action_classification:59 - ERROR: Fail to run pytorchvideo - {'model_name': 'c2d_r50'}
ERROR MESSAGE: Remote end closed connection without response
2022-06-16 16:05:56,487 - 139986425451328 - test_action_classification.py-test_action_classification:59 - ERROR: Fail to run pytorchvideo - {'model_name': 'i3d_r50'}
ERROR MESSAGE: <urlopen error [Errno 110] Connection timed out>

### Expected Behavior

No error

### Steps To Reproduce

```python
import logging
import os
import time
import subprocess
from towhee import ops

logger = logging.getLogger()
log_path = 'action_classification.log'

# Test action-classification operators
action_classification = {
    'pytorchvideo': [
        {'model_name': 'c2d_r50'},
        {'model_name': 'i3d_r50'},
        {'model_name': 'slow_r50'},
        {'model_name': 'slowfast_r50'},
        {'model_name': 'slowfast_r101'},
        {'model_name': 'x3d_xs'},
        {'model_name': 'x3d_s'},
        {'model_name': 'x3d_m'},
        {'model_name': 'mvit_base_16x4'},
        {'model_name': 'mvit_base_32x3'},
    ],
    'actionclip': [
        {'model_name': 'clip_vit_b16'},
        {'model_name': 'clip_vit_b32'}
    ],
    'timesformer': [
        {'model_name': 'timesformer_k400_8x224'}
    ]
}


def test(data_path):
    if not os.path.isfile(data_path):
        subprocess.call(
            f'wget -O {data_path} https://dl.fbaipublicfiles.com/pytorchvideo/projects/archery.mp4',
            shell=True
        )

    video_decoder = ops.video_decode.ffmpeg()
    # Since the video_decoder returns generator, need to extract output from generator for repetitive usage
    input_data = [x for x in video_decoder(data_path)]
    handler = logging.FileHandler(log_path)
    logger.addHandler(handler)

    for k, v in action_classification.items():
        init_op = getattr(ops.action_classification, k)
        for args in v:
            try:
                op = init_op(**args)
                outs = op(input_data)
                assert outs[0][0] == 'archery'
                assert len(outs[1]) == 5
                assert outs[2].shape[0] > 0
                print('Success:', k, str(args))
                logger.info('Success %s - %s', k, str(args))
            except Exception as e:
                logger.error('Fail to run %s - %s', k, str(args))
                print(f'ERROR MESSAGE: {e}')
                pass
            time.sleep(5)
    print('Finished.')

if __name__ == '__main__':
    test('./archery.mp4')
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): latest (GPU)
- OS(Ubuntu or CentOS):Ubuntu
- CPU/Memory:
- GPU:
- Others:
```

**Comment by reiase** [comment]
The error is thrown from torch hub, can you check your internet connection? @binbinlv

**Comment by binbinlv** [comment]
I think this is the duplicate issue of #1432, so close it.
