### ISSUE TITLE
[Bug]: Dependency "transformers" is not compatible between op "blip" and "lightningdot"

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1456]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Dependency "transformers" is not compatible between op "blip" and "lightningdot"

"blip" needs "transformers>=4.15.0" 

"lightningdot" needs "transformers==2.3.0"

### Expected Behavior

No conflict dependency version

### Steps To Reproduce

```markdown
Running op "blip" and "lightningdot" automatically
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):latest pre-0.7
- OS(Ubuntu or CentOS):both
- CPU/Memory:
- GPU:
- Others:
```

**Comment by wxywb** [comment]
The pertained models in these two operators needs the specific data structure in two different version of the library(**transformers**) which is not backward-compatible. It costs hundreds of gpu machines in their original implementation so we can not retrain it weights in a newer version economically.

**Comment by binbinlv** [comment]
OK, so now the behavior is towhee report errors for dependency version conflict, and needs users to confirm and install the needed version.
