### ISSUE TITLE
[DesignProposal]: advise for git cloning big files from hub

### ISSUE THREAD

**Issue by dreamfireyu** [towhee-io/towhee#1458]
### Background and Motivation

When I tried to clone operator to local pc, the model weights are too big to download.
`from towhee import ops `
 `deepfake = ops.deepfake()`
 `pred = deepfake('/home/test_video')`
This is my error message:

> Cloning into '/Users/zilliz/.towhee/operators/towhee/deepfake/main'...
error: RPC failed; HTTP 504 curl 22 The requested URL returned error: 504
fatal: error reading section header 'shallow-info'

### Design

This problem can be solved by adding `--depth = 1` to git command like
`git clone –depth=1 https://towhee.io/towhee/deepfake.git`
with only cloning the latest commit.

**Comment by reiase** [comment]
Duplicate of #1452
