### ISSUE TITLE
[DesignProposal]: Execution strategy and chunked stream data processing

### ISSUE THREAD

**Issue by Chiiizzzy** [towhee-io/towhee#1461]
### Design

# Execution strategy
There are several ways that Towhee execute operators in the workflow, according to data type and execution mode:
![execution](https://user-images.githubusercontent.com/72550076/175256131-aa37bf83-467a-46db-b668-8501f989a3cb.png)
Say we have three operators, namely A, B, C, and input data 1, 2, 3.
- With unstreamed data and unparalleled execution:
Execute A with data 1, 2, 3 in order, then execute B with 1, 2, 3, finally execute C; 
- With streamed data and unparalleled execution:
Execute A, B, C for data 1, then Execute A, B, C for data 2, finally run A, B, C for data 3;
- With unstreamed data and paralleled execution:
Execute A with data 1, 2, 3 at the same time, then B, finally run C;
- With streamed data and paralleled execution:git add:
Excute A for 1, then A start process 2, meanwhile, B start process 1, and so on.
## Chunked data
With Chunked data, we preserve the same execution strategy.
For stream chunked data, we will introduce a buffer:
![buffer](https://user-images.githubusercontent.com/72550076/175256208-7448de30-7879-4d51-aa6f-68704b8af103.png)
We load data from stream to fill the chunk(buffer), then push the chunk(buffer) into a chunk(buffer) queue, the queue will pop the chunk(buffer) to feed the operator. By default, we will set the queue length to 1, i.e. Only one chunk(buffer) in queue . Once the chunk(buffer) is consumed, a new chunk will be produced.

**Comment by reiase** [comment]
Why we don't use stream+parallel execution by default:
1. we have to load all the operators into memory when using stream+parallel, which will increase the peek memory usage;
2. race condition will increase system latency;
