### ISSUE TITLE
[Bug]: Automatically downloaded "torch" is not suitable for GPU machine reporting "no kernel image is available for execution on the device\nCUDA"

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1462]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Automatically downloaded "torch" is not suitable for GPU machine reporting "no kernel image is available for execution on the device\nCUDA"

### Expected Behavior

Could we install the right version directly?

### Steps To Reproduce

```markdown
1. create new env
2. install towhee and towhee.models
3. running op
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):latest pre-0.7
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jaelgu** [comment]
To install pytorch with cuda, please refer to https://pytorch.org/get-started/locally/ for proper versions & installation commands. (I recommend to use `conda install` because it will install proper `cudatoolkit` for your environment.)
