### ISSUE TITLE
Call pipeline failed with error "Can not find pipeline by name resnet50_embedding"

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#151]
Steps/Code to reproduce:
1 setup env and install towhee:
```python
python3 -m venv towhee-test-env
pip install -U pip
pip install towhee
```

2 into python env: phthon3:
```python
from towhee import pipeline
pipeline = pipeline('image-embedding')
```

Expected result:
pipeline return successfully

Actual results:
error: 
Can not find pipeline by name resnet50_embedding

Environment:
Mac OS

**Comment by fzliu** [comment]
Fixed.
