### ISSUE TITLE
[Documentation]: 

### ISSUE THREAD

**Issue by sjcotto** [towhee-io/towhee#1515]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

Hi, can you please provide an example on how to run this: 

```
with towhee.api['file']() as api:
    app_insert = (
        api.image_load['file', 'img']()
        .save_image['img', 'path'](dir='tmp/images')
        .get_path_id['path', 'id']()
        .image_text_embedding.clip['img', 'vec'](model_name='clip_vit_b32',modality='image')
        .tensor_normalize['vec', 'vec']()
        .milvus_insert[('id', 'vec'), 'res'](collection=milvus_collection)
        .select['id', 'path']()
        .serve('/insert', app)
    )
```

but using and url instead of the local file? i think clip supports urls but can't find the example

**Comment by shiyu22** [comment]
Hi @sjcotto you can try to use `image_decode` to upload file with URL, for example:
```python
with towhee.api['url']() as api:
    app_insert = (
        api.image_decode['url', 'img']()
        .save_image['img', 'path'](dir='tmp/images')
        .get_path_id['path', 'id']()
        .image_embedding.timm['img', 'vec'](model_name='resnet50')
        .tensor_normalize['vec', 'vec']()
        .milvus_insert[('id', 'vec'), 'res'](collection=milvus_collection)
        .select['id', 'path']()
        .serve('/insert_url', app)
    )
```
And you can call it with `$ curl -X POST "http://0.0.0.0:8000/insert_url"  --data https://github.com/towhee-io/towhee/raw/main/towhee_logo.png#gh-light-mode-only`.


BTW, the `image_load` is used to load the image binary file in the cache, and `image_decode` can load images with path or url.

**Comment by shiyu22** [comment]
Could you please submit another issue for the `towhee.api` docs?
