### ISSUE TITLE
[Feature]: 期待能够支持中文搜图片

### ISSUE THREAD

**Issue by klisly** [towhee-io/towhee#1518]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

通过中文文本搜索图片这个想法已经在我的想法清单中列了好久。
很苦恼的地方在于，自己手动训练模型的话，需要投入很多时间，做了很多调研，最终没有花时间去做。
很开心，看到towhee提供以文搜图的应用示例。
比较遗憾的是，目前只支持英文，期待能支持中文搜索图片

**Comment by GuoRentong** [comment]
we are now having a study on chinese-image retrieval models. Once supported, models such as BriVL will be included.

BTW, we suggest writing issue in english, so that more people in our community can read this.

**Comment by oneseer** [comment]
We are testing SOTA Chinese text-image retrieval algorithms. And at least two solutions will released, please stay tuned.

**Comment by fishfree** [comment]
@oneseer Have you done this problem? I notcie the bot mark it as complted. /reopen

**Comment by wxywb** [comment]
@fishfree ,hello please have a look at this https://towhee.io/image-text-embedding/taiyi
