### ISSUE TITLE
[Feature]: How can I use paddle pretrained model in towhee?

### ISSUE THREAD

**Issue by lx1054331851** [towhee-io/towhee#1544]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

I trained my model based on paddlepaddle, could I use it in towhee?

### Describe the solution you'd like.

Paddlepaddle now is a very populate deep learning framework in china, how can I use the pretrained model based on paddlepaddle framework in towhee?

**Comment by oneseer** [comment]
Our framework is mainly base on pytorch. Maybe you can try converting your weights to pytorch, please try this converting tool, https://github.com/PaddlePaddle/X2Paddle. Let us know how it goes. Cheers!

**Comment by lx1054331851** [comment]
@oneseer 
Thank you for your reply.
X2Paddle can just convert pytorch、tensorflow models to paddle models, but there is no way convert paddle models to pytorch models.
Someone can convert paddle models to numpy array, but it is a little complex.
For now, use pytorch models is the best way in towhee.
