### ISSUE TITLE
[Bug]: Pyarrow is mandatory for towhee pipeline

### ISSUE THREAD

**Issue by jaelgu** [towhee-io/towhee#1554]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I chose not to install pyarrow when importing pipeline from towhee. However, it fails to import pipeline.
After pyarrow is installed, then it's able to import pipeline.

<img width="715" alt="image" src="https://user-images.githubusercontent.com/86251631/178631803-a2e843a9-2ff3-4f9a-ae53-8ef69af01487.png">

### Expected Behavior

If towhee pipeline doesn't use pyarrow, then it should allow user to skip pyarrow when using pipeline.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
Fixed, so close it.
