### ISSUE TITLE
[Documentation]: How to find out all the towhee supported builded-in pipeline operators?

### ISSUE THREAD

**Issue by lx1054331851** [towhee-io/towhee#1568]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

Where can i find all the towhee supported builded in pipeline operation like “save_image”？

From the current doc，a lot of useful function is hard to find for a new guy with towhee.

### Why is this needed?

By read the source code, I find these builded-in operators,
``` python
__all__ = [
    'DEFAULT_PIPELINES',
    'pipeline',
    'ops',
    'register',
    'param_scope',
    'Build',
    'Inject',
    'dataset',
    'Document',
    'DataCollection',
    'DataFrame',
    'State',
    'Entity',
    'connectors',
    #
    'glob',
    'glob_zip',
    'from_df',
    'read_audio',
    'read_camera',
    'read_csv',
    'read_json',
    'read_video',
    'read_zip',
    'dc',
    'api',
    'dummy_input'
]
```
But something like "image_decode", "object_detection.yolov5", I must read the bootcamp, I want to know  how many operators there are but I don't know but it is really useflly?

**Comment by binbinlv** [comment]
@reiase 
Could you please answer this question? Thanks.

**Comment by binbinlv** [comment]
@lx1054331851 
Could you please help to add the title?  And it is easy for any others to get your problems quickly. 

Thanks.
