### ISSUE TITLE
[Bug]: SSLError: HTTPSConnectionPool(host='towhee.io', port=443): Max retries exceeded with url: /api/v1/repos/towhee/image-decode (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

### ISSUE THREAD

**Issue by Rosesqy** [towhee-io/towhee#1570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

On a databricks notebook, When I try to run 
```
towhee.glob(pattern).exception_safe().image_decode().image_embedding().timm(model_name="resnet50")
        .drop_empty()
        .tensor_normalize()
        .to_list()
```
, it shows error:
SSLError: HTTPSConnectionPool(host='towhee.io', port=443): Max retries exceeded with url: /api/v1/repos/towhee/image-decode (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

### Expected Behavior

When I run the command locally, it can successfully generate the embedding vectors for the images in pattern

### Steps To Reproduce
1-2. In databricks notebook, version 10.4 LTS (includes Apache Spark 3.2.1, Scala 2.12), python version 3.8
3. save png images in the "pattern", want to generate embeddings for all the images in the file, so run  

```
towhee.glob(pattern).exception_safe().image_decode().image_embedding().timm(model_name="resnet50")
        .drop_empty()
        .tensor_normalize()
        .to_list()
```

4. it goes to the SSL error

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): v0.7.2
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory:
- GPU:
- Others:
```

**Comment by Rosesqy** [comment]
I also tried 
```
embedding_pipeline = towhee.pipeline("towhee/image-embedding-resnet50")
embedding = embedding_pipeline(pattern)
embedding
```
and it shows the same error

**Comment by binbinlv** [comment]
@reiase 

Could you help to have a look at this issue?

Thanks.

**Comment by jin1ming** [comment]
I thought it might not be a bug, I had the same problem, but when I turned the system proxy off it worked fine.
