### ISSUE TITLE
[Bug]: text_image_search cannot run in an offline environment

### ISSUE THREAD

**Issue by 2132660698** [towhee-io/towhee#1573]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when I follow 
https://github.com/milvus-io/bootcamp/blob/master/solutions/text_image_search/1_build_text_image_search_engine.ipynb
run code in an offline environment,I encountered the following error.
![lALPJwnIzT40WzXNAc7NCIQ_2180_462](https://user-images.githubusercontent.com/94035926/179342080-3753defd-f822-48bb-abc7-4b29ef649365.png)

I have followed the following
https://github.com/towhee-io/towhee/issues/1523
copy all ~/.towhee files (online mechine run ok) to the offline environment.

### Expected Behavior

text_image_search cannot run in an offline environment

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by 2132660698** [comment]
![image](https://user-images.githubusercontent.com/94035926/179342232-fc379aaf-8e84-4312-9326-7e6c4b8fb67c.png)
copy all ~/.towhee files (online mechine run ok) to the offline environment.

**Comment by wxywb** [comment]
it needs towhee.models, make sure it is installed in your python environment.
` pip list |grep towhee.models`
