### ISSUE TITLE
[Bug]: Error “towhee/data2vec repo does not exist” occurs when running audio embedding

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1587]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Error “towhee/data2vec repo does not exist” occurs when running audio embedding

### Expected Behavior

No error

### Steps To Reproduce

```markdown
import towhee

(
    towhee.glob('***')
          .audio_decode.ffmpeg()
          .runas_op(func=lambda x:[y[0] for y in x])
          .towhee.data2vec()
          .show()
)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.7.3.dev32 (models latest)
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by wxywb** [comment]
this operator has been moved to **audio-embedding/data2vec**

**Comment by binbinlv** [comment]
@wxywb so the following guide should be modified on the official website.
https://towhee.io/audio-embedding/data2vec

**Comment by wxywb** [comment]
doc has been fixed.

**Comment by binbinlv** [comment]
Fixed and close it.
