### ISSUE TITLE
[Bug]: Duplicate "transformers" dependency in the requirements of image embedding for data2vec

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#1590]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Duplicate "transformers" dependency in the requirements of image embedding for data2vec

https://towhee.io/image-embedding/data2vec/src/branch/main/requirements.txt:
numpy
transformers>4.19.0
torch
transformers
towhee

### Expected Behavior

transformers>4.19.0 and transformers are duplicated?

### Steps To Reproduce

```markdown
NA
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):towhee latest
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by wxywb** [comment]
duplicated dependency is removed.

**Comment by binbinlv** [comment]
Fixed, so close it.
