### ISSUE TITLE
[Bug]: DC set_parallel does not work

### ISSUE THREAD

**Issue by Chiiizzzy** [towhee-io/towhee#1626]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

<img width="583" alt="截屏2022-07-25 18 39 43" src="https://user-images.githubusercontent.com/72550076/180758532-742e0e4d-dcd0-4f91-981a-b91bde9a1dce.png">
<img width="644" alt="截屏2022-07-25 18 39 53" src="https://user-images.githubusercontent.com/72550076/180758539-4f31174e-ab60-4916-b9ef-4e6bf4cb1413.png">
Parallel does not speed up the model.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by filip-halt** [comment]
I believe this occurred due to the introduction of the config mixin. There was one bug that i fixed here: https://github.com/towhee-io/towhee/commit/8b08f3d294ecc1ac623c79cd40c82526314ce897 but there may be a few more.

**Comment by Chiiizzzy** [comment]
https://zilliverse.feishu.cn/docx/doxcnDUAMa4Vu9D39CsVSvraGrK

**Comment by filip-halt** [comment]
[Parallel Report.pdf](https://github.com/towhee-io/towhee/files/9202401/Parallel.Report.pdf)

**Comment by filip-halt** [comment]
> https://zilliverse.feishu.cn/docx/doxcnDUAMa4Vu9D39CsVSvraGrK

Please upload as pdf next time.
