### ISSUE TITLE
[Bug]: GPU for Image embedding

### ISSUE THREAD

**Issue by Kevinarun** [towhee-io/towhee#1649]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I want to extract emb from images as there are many images I want to use GPU, but I'm unable to use GPU in colab.

dc = (towhee.glob('/path/to/folder/*')
          .image_decode()
          .image_embedding.timm(model_name='resnet50')
          .to_list()
     )
 
How can I use GPU?

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
@jaelgu 

Could you help to answer this question? Thanks.
