### ISSUE TITLE
[Bug]: use pipeline, when the python program works for a while, the process hang on, the process exist, and has no exception. But client cannot access the interface anymore

### ISSUE THREAD

**Issue by angelapytao** [towhee-io/towhee#1652]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

 I use pipeline found another issue, when the python program works a while, the process hang on, the process exist, and has no exception. But client cannot access the interface anymore.
![image](https://user-images.githubusercontent.com/5369411/182095759-5e3375f1-8d04-4adb-96df-d867e574860a.png)
There is no
_end_op ends with status: RunnerStatus.FINISHED, graph_context.py-graph_context:136 - INFO: Graph 25872 end., so I think why the program hangs on...

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.6.1
- OS(Ubuntu or CentOS):CentOS
- CPU/Memory:
- GPU:GeForce RTX 3090
- Others:
```

**Comment by junjiejiangjjj** [comment]
if the problem occurs again, please use `stack` or `pstrace` to find where the process hangs. I have run the pipeline 1000000 times, but the problem has not occurred.

**Comment by angelapytao** [comment]
I use strace found
<img width="1283" alt="image" src="https://user-images.githubusercontent.com/5369411/183321586-c0a7a1d2-6d6b-4555-b9c0-7201e4b44eaa.png">

**Comment by angelapytao** [comment]
cat /proc/142637/stack
<img width="389" alt="image" src="https://user-images.githubusercontent.com/5369411/183321899-0ead8c21-b006-4903-ad7e-c29e606b1bb1.png">

**Comment by junjiejiangjjj** [comment]
Any other infos?  the stack is very similar to this https://stackoverflow.com/questions/68125101/python-multiprocessing-getting-stuck  maybe because of multiprocessing.

**Comment by angelapytao** [comment]
I raise up the single python process separately, within single python process, there is no multiprocessing.

**Comment by fzliu** [comment]
@angelapytao were you ever able to resolve your issue?

**Comment by angelapytao** [comment]
@fzliu still exist. occasionally happened.

**Comment by angelapytao** [comment]
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/5369411/187011696-7b6c8ff7-2c41-4001-986f-27d62b873103.png">
