### ISSUE TITLE
[DesignProposal]: Support parallel in GPU

### ISSUE THREAD

**Issue by Chiiizzzy** [towhee-io/towhee#1653]
#### Multi Stream
When setting multi stream manually:
```
%%time
import torch
from torch.profiler import profile, ProfilerActivity

with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA]) as prof:
    s1 = torch.cuda.Stream()
    s2 = torch.cuda.Stream()
    A = torch.rand(1000, 1000, device = 'cuda')
    B = torch.rand(1000, 1000, device = 'cuda')
    torch.cuda.synchronize()
    with torch.cuda.stream(s1):
        for _ in range(100):
            C = torch.mm(A, A)
    with torch.cuda.stream(s2):
        for _ in range(100):
            D = torch.mm(B, B)
    torch.cuda.synchronize()

prof.export_chrome_trace("MultiStream.json")
```
<img width="1845" alt="截屏2022-08-01 16 56 09" src="https://user-images.githubusercontent.com/72550076/182301921-e6c708da-2eee-4fe5-9928-37caef4c29d4.png">
The green parts represent the execution of torch.mm. Running in two streams separately, realize parallel.

#### Single Stream(Default)
```
%%time
import torch
from torch.profiler import profile, ProfilerActivity

with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA]) as prof:
    A = torch.rand(1000, 1000, device = 'cuda')
    B = torch.rand(1000, 1000, device = 'cuda')
    for _ in range(100):
        C = torch.mm(A, A)
    for _ in range(100):
        D = torch.mm(B, B)
prof.export_chrome_trace("trace.json")
```
<img width="1842" alt="截屏2022-08-01 17 00 34" src="https://user-images.githubusercontent.com/72550076/182302042-06230ab5-f5bd-4ea9-bdc4-f14a3759a64f.png">

Two for loops are running serially in one single stream.
#### Multi Thread
When setting multi thread without declaring multi stream:
```
%%time
import threading 
 
def gothread(A):
    for i in range(100):
        C = torch.mm(A, A)

with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA]) as prof:
    A = torch.rand(1000, 1000, device = 'cuda')
    B = torch.rand(1000, 1000, device = 'cuda')
    for i in [A, B]:
        threading.Thread(target=gothread(i,)).start()

prof.export_chrome_trace("trace.json")
```

<img width="1372" alt="截屏2022-08-02 13 56 30" src="https://user-images.githubusercontent.com/72550076/182302225-fa5d5a23-9715-41de-92da-403322188b3e.png">
The computation is still serial. 

#### Conlusion
Setting multi thread only works on CPU, we need to set stream when running DC in GPU machine.

### Design

TBD

**Comment by reiase** [comment]
@Chiiizzzy could you please post the detailed design instead of posting a link in this issue?

**Comment by yfq512** [comment]
@ reiase
like this code
```
towhee.dc(['./1.mp4']) \
        .video_decode.ffmpeg(sample_type='uniform_temporal_subsample', args={'num_samples': 12}) \
        .runas_op(func=lambda x: [y for y in x]) \
        .video_text_embedding.clip4clip(model_name='clip_vit_b32', modality='video', device='cpu') \
        .show()
```
how can assign a video_text_embedding（[0.31566384, -0.07464158, -0.023179442, ...] shape=(480,)
） to a variable
