### ISSUE TITLE
[Bug]: Fail to download op "deepfake"

### ISSUE THREAD

**Issue by jaelgu** [towhee-io/towhee#1654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fail to download op: https://towhee.io/towhee/deepfake (with git-lfs installed)

```
git clone https://towhee.io/towhee/deepfake.git
```
<img width="715" alt="image" src="https://user-images.githubusercontent.com/86251631/182115656-1fba242c-7653-4709-9346-43388c2feae0.png">

- able to git clone other repos (towhee repo)
- able to download other operators (with or without large files)

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by zhujiming** [comment]
This  item is too big, you can use command

> git clone https://towhee.io/towhee/deepfake.git --depth 1

**Comment by jaelgu** [comment]
> This item is too big, you can use command
> 
> > git clone https://towhee.io/towhee/deepfake.git --depth 1

git clone --depth1 works. @reiase @Chiiizzzy But is this (--depth 1) enabled when we call the operator in python? Because when I call it in python with dc and it gives me broken weights files, leading to failure of loading weights.
