### ISSUE TITLE
[Bug]: operator towhee/load-image not found!

### ISSUE THREAD

**Issue by JinXia77** [towhee-io/towhee#1656]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

I followed the process of offical document of towhee [DataCollection](https://docs.towhee.io/User%20Guides/DataCollection/data-collection/) occured "operator towhee/load-image not found!" error when I run below codes. 
`dataset = DataCollection.from_glob('towhee.jpeg') \
        .load_image() \
        .random_resize_crop(224) \
        .random_horizontal_flip() \
        .cvt_color('RGB2BGR') \
        .normalize() \
        .towhee.image_embedding(model_name='resnet101') # redirect function call to towhee operators`

### Steps To Reproduce

```markdown
1. In the towhee env followed by offical document procedure
2. from towhee import DataCollection
3. run the previous code and occur the errors shown above
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):ubuntu
- CPU/Memory:cpu
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
Recently, we changed some API name, some example has expired, we will fix it, thanks very much.
