### ISSUE TITLE
[Bug]:  lost op_config info.

### ISSUE THREAD

**Issue by junjiejiangjjj** [towhee-io/towhee#1659]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```python
import towhee
from towhee.serve.triton import builder

f = towhee.dummy_input().image_decode.cv2_rgb(op_config={'instance_count':2})\
                                     .image_text_embedding.clip_image(op_config=
                                                                      {
                                                                          'format_priority': ['onnx'],
                                                                          'device_ids': [0],
                                                                          'dynamic_batching': {
                                                                              'max_batch_size': 128,
                                                                              'preferred_batch_size': [8, 16],
                                                                              'preferred_max_queue_delay_microseconds': 100000
                                                                          }
                                                                      })\
                                                          .as_function()
dag = f.dag_info
print(dag)
```

the result lost the `format_priority` info.
```text
{'e550e54d': {'op': 'map', 'op_name': 'image-decode/cv2-rgb', 'is_stream': True, 'init_args': {}, 'call_args': {'*arg': (<towhee.engine.factory._OperatorLazyWrapper object at 0x7f7d2a9b6bb0>,), '*kws': {}}, 'op_config': {'instance_count': 2, 'chunksize': None, 'jit': None, 'format_priority': None}, 'input_info': Non\
e, 'output_info': None, 'parent_ids': ['start'], 'child_ids': ['d31ba70d']}, 'd31ba70d': {'op': 'map', 'op_name': 'image-text-embedding/clip-image', 'is_stream': True, 'init_args': {}, 'call_args': {'*arg': (<towhee.engine.factory._OperatorLazyWrapper object at 0x7f7d280a6e80>,), '*kws': {}}, 'op_config': {'format_p\
riority': None, 'device_ids': [0], 'dynamic_batching': {'max_batch_size': 128, 'preferred_batch_size': [8, 16], 'preferred_max_queue_delay_microseconds': 100000}, 'parallel': None, 'chunksize': None, 'jit': None}, 'input_info': None, 'output_info': None, 'parent_ids': ['e550e54d'], 'child_ids': ['end']}, 'end': {'op\
': 'end', 'op_name': 'end', 'init_args': None, 'call_args': None, 'op_config': None, 'input_info': None, 'output_info': None, 'parent_ids': ['d31ba70d'], 'child_ids': []}, 'start': {'op': 'stream', 'op_name': 'dummy_input', 'is_stream': False, 'init_args': None, 'call_args': {'*arg': (), '*kws': {}}, 'op_config': {'\
parallel': None, 'chunksize': None, 'jit': None, 'format_priority': None}, 'input_info': None, 'output_info': None, 'parent_ids': [], 'child_ids': ['e550e54d']}}
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by zhujiming** [comment]
#1661 
this pr will fix this bug. And test result like
`{'de3264c7': {'op': 'map', 'op_name': 'image-decode/cv2-rgb', 'is_stream': True, 'init_args': {}, 'call_args': {'*arg': (<towhee.engine.factory._OperatorLazyWrapper object at 0x12c51c580>,), '*kws': {}}, 'op_config': {'chunksize': None, 'jit': None, 'format_priority': None, 'instance_count': 2}, 'input_info': None, 'output_info': None, 'parent_ids': ['start'], 'child_ids': ['e39d6a62']}, 'e39d6a62': {'op': 'map', 'op_name': 'image-text-embedding/clip-image', 'is_stream': True, 'init_args': {}, 'call_args': {'*arg': (<towhee.engine.factory._OperatorLazyWrapper object at 0x1387c8910>,), '*kws': {}}, 'op_config': {'parallel': None, 'chunksize': None, 'jit': None, 'format_priority': ['onnx'], 'device_ids': [0], 'dynamic_batching': {'max_batch_size': 128, 'preferred_batch_size': [8, 16], 'preferred_max_queue_delay_microseconds': 100000}}, 'input_info': None, 'output_info': None, 'parent_ids': ['de3264c7'], 'child_ids': ['end']}, 'end': {'op': 'end', 'op_name': 'end', 'init_args': None, 'call_args': None, 'op_config': None, 'input_info': None, 'output_info': None, 'parent_ids': ['e39d6a62'], 'child_ids': []}, 'start': {'op': 'stream', 'op_name': 'dummy_input', 'is_stream': False, 'init_args': None, 'call_args': {'*arg': (), '*kws': {}}, 'op_config': {'parallel': None, 'chunksize': None, 'jit': None, 'format_priority': None}, 'input_info': None, 'output_info': None, 'parent_ids': [], 'child_ids': ['de3264c7']}}`
