### ISSUE TITLE
[Bug]: CI failed to install requirements

### ISSUE THREAD

**Issue by Chiiizzzy** [towhee-io/towhee#1676]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/towhee-io/towhee/runs/7720888625?check_suite_focus=true

When running codecov workflow in our own GPU machine, we will create a new virtual env `towhee-ut`, and install requirements in this env. However, I found that many requirements already exists in `/home/super/actions-runner/_work/_tool/Python/3.8.13/x64/lib/python3.8/site-packages`, thus won't be installed in `towhee-ut`. This problem leads to the ci failure reported in the PR above.

<img width="933" alt="截屏2022-08-08 16 25 26" src="https://user-images.githubusercontent.com/72550076/183373968-f1eb702d-3436-4281-91aa-be39a1bd69f1.png">
 

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jennyli-z** [comment]
@binbinlv please help have a look, as self hosted machine is controlled by you.
