### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'towhee'

### ISSUE THREAD

**Issue by aiot-tech** [towhee-io/towhee#1688]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After the installation of towhee is completed, it cannot be imported, nor can it be reinstalled

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
@aiot-tech 
could you run "pip show towhee"?

**Comment by aiot-tech** [comment]
```pip show towhee```
The output is as follows:
```

Name: towhee
Version: 0.7.2
Summary: Towhee is a framework that helps you encode your unstructured data into embeddings.
Home-page: https://github.com/towhee-io/towhee
Author: Towhee Team
Author-email: towhee-team@zilliz.com
License: http://www.apache.org/licenses/LICENSE-2.0
Location: /root/miniconda3/lib/python3.9/site-packages
Requires: numpy, tqdm, requests, tabulate, ruamel.yaml
Required-by: 
```

**Comment by binbinlv** [comment]
@aiot-tech 
Now the latest is 0.7.3, could you please run "pip uninstall towhee" then "pip install towhee" and check whether it is 0.7.3 now.

And maybe you need pay attention which python env you are using if you have several python versions in your system.

maybe "python3 -m pip install towhee" could make sure you have the same python version when you running "import towhee" in python3 terminal.

**Comment by aiot-tech** [comment]
What a stupid mistake I make.You are right, I import it with another python interpreter. Thx a lot:)
