### ISSUE TITLE
[DesignProposal]: Guide to towhee ci/cd pipeline

### ISSUE THREAD

**Issue by filip-halt** [towhee-io/towhee#1730]
### Background and Motivation

When making a PR that adds inline comments and docstring improvements, codecov might have a tiny delta due to non-determinism, ultimately blocking the PR with a failed codecov case.

### Design

Add a new label for pr's that signifies that the PR should be force merged, as long as the reviewer reviews docstrings and such. Some ideas were `review/codecov` and `type/api-doc`

**Comment by reiase** [comment]
can we change the title of the issue to "guild to towhee ci/cd pipeline", or something like that?

**Comment by filip-halt** [comment]
https://github.com/towhee-io/towhee/pull/1752 

An example of a pull request that cant be merged because files that werent changed have different codecov results.
