### ISSUE TITLE
How set query conditions for "milvus_search"

### ISSUE THREAD

**Issue by yfq512** [towhee-io/towhee#1811]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

yes

### Describe the solution you'd like.

I have query similar datas from milvus, and it work well

```
    connections.connect(host=host, port=port)
    default_fields = [
        FieldSchema(name="milvus_id", dtype=DataType.INT64, is_primary=True),
        FieldSchema(name="feature", dtype=DataType.FLOAT_VECTOR, dim=dim),
        FieldSchema(name="time", dtype=DataType.INT64)
    ]
    default_schema = CollectionSchema(fields=default_fields, description="test collection")

    collection = Collection(name=field_name, schema=default_schema)

    (
        towhee.dc[('milvus_id', 'img_url', 'time')](read_kafka())
            .runas_op['img_url', 'img'](lambda url: [from_pil(url2img_pil(url)), ])
            .action_classification.pytorchvideo['img', ('', '', 'feature')](model_name='x3d_m')
            .runas_op['feature', 'feature'](lambda feature: DataCollection([feature]).tensor_normalize().to_list()[0].tolist())
            .milvus_search['feature', 'result'](collection=collection, limit=10)
            .run()
    )
```
But  how set query conditions for "milvus_search", such as "time > 10"?

### Describe an alternate solution.

```
    vectors = img2feature('1.jpg')

    topK = 10
    search_params = {"metric_type": "L2", "params": {"nprobe": 10}}

    res = collection.search(
        [vectors],
        "feature",
        search_params,
        topK,
        "app_id == {} and time > {}".format(8, 10),
        output_fields=["milvus_id"]
    )
```
我可以设置 " "app_id == {} and time > {}".format(8, 10), " 进行搜索，但是在towhee中怎么添加类似的条件？

**Comment by shiyu22** [comment]
Hi @yfq512,  of course, the parameters in milvus.search() can be passed directly to the milvus_search Operator, but the parameter name needs to be specified, such as:
```bash
.milvus_search['feature', 'result'](collection=collection, 
        param=search_params, 
	limit=topK, 
	expr="app_id == {} and time > {}".format(8, 10),
	output_fields=["milvus_id"]
)
```

**Comment by yfq512** [comment]
@shiyu22 Thanks for your reply, another question, when I set ".set_parallel(5)" in "towhee.dc()", It don't work sometimes, and when I delete the line ".set_parallel(5)", It will work well always. 
Why?

**Comment by yfq512** [comment]
> Hi @yfq512, of course, the parameters in milvus.search() can be passed directly to the milvus_search Operator, but the parameter name needs to be specified, such as:
> 
> ```shell
> .milvus_search['feature', 'result'](collection=collection, 
>         param=search_params, 
> 	limit=topK, 
> 	expr="app_id == {} and time > {}".format(8, 10),
> 	output_fields=["milvus_id"]
> )
> ```

感谢您的回复，现在我知道了是可以通过 expr 设置查询条件的，但是：
像这样：```.milvus_search['feature', 'result'](collection=collection, limit=10, expr="app_id== {}".format(???app_id))```
我该如何把 app_id 传进去，这里的 app_id 是个变量。
我不太熟悉towhee.dc()的编程方式，并且没找到相关的示例，您能写个简单的示例么？万分感谢！

**Comment by shiyu22** [comment]
> > Hi @yfq512, of course, the parameters in milvus.search() can be passed directly to the milvus_search Operator, but the parameter name needs to be specified, such as:
> > ```shell
> > .milvus_search['feature', 'result'](collection=collection, 
> >         param=search_params, 
> > 	limit=topK, 
> > 	expr="app_id == {} and time > {}".format(8, 10),
> > 	output_fields=["milvus_id"]
> > )
> > ```
> 
> 感谢您的回复，现在我知道了是可以通过 expr 设置查询条件的，但是： 像这样：`.milvus_search['feature', 'result'](collection=collection, limit=10, expr="app_id== {}".format(???app_id))` 我该如何把 app_id 传进去，这里的 app_id 是个变量。 我不太熟悉towhee.dc()的编程方式，并且没找到相关的示例，您能写个简单的示例么？万分感谢！

I think you are right and you can try it, and you can also run with `.milvus_search['feature', 'result'](collection=collection, limit=10, expr='app_id== {app_id}')`.

**Comment by shiyu22** [comment]
> @shiyu22 Thanks for your reply, another question, when I set ".set_parallel(5)" in "towhee.dc()", It don't work sometimes, and when I delete the line ".set_parallel(5)", It will work well always. Why?

Is there any error message? I met this issue before, but it's because no cuda memory, I think you can also check your memory changes.

**Comment by yfq512** [comment]
> > > Hi @yfq512, of course, the parameters in milvus.search() can be passed directly to the milvus_search Operator, but the parameter name needs to be specified, such as:
> > > ```shell
> > > .milvus_search['feature', 'result'](collection=collection, 
> > >         param=search_params, 
> > > 	limit=topK, 
> > > 	expr="app_id == {} and time > {}".format(8, 10),
> > > 	output_fields=["milvus_id"]
> > > )
> > > ```
> > 
> > 
> > 感谢您的回复，现在我知道了是可以通过 expr 设置查询条件的，但是： 像这样：`.milvus_search['feature', 'result'](collection=collection, limit=10, expr="app_id== {}".format(???app_id))` 我该如何把 app_id 传进去，这里的 app_id 是个变量。 我不太熟悉towhee.dc()的编程方式，并且没找到相关的示例，您能写个简单的示例么？万分感谢！
> 
> I think you are right and you can try it, and you can also run with `.milvus_search['feature', 'result'](collection=collection, limit=10, expr='app_id== {app_id}')`.

我的程序大概是这样的：
```
    connections.connect(host=host, port=port)
    default_fields = [
        FieldSchema(name="milvus_id", dtype=DataType.INT64, is_primary=True),
        FieldSchema(name="feature", dtype=DataType.FLOAT_VECTOR, dim=dim),
        FieldSchema(name="time", dtype=DataType.INT64)
    ]
    default_schema = CollectionSchema(fields=default_fields, description="test collection")

    collection = Collection(name=field_name, schema=default_schema)

    (
        towhee.dc[('milvus_id', 'img_url', 'time')](read_kafka())
            .runas_op['img_url', 'img'](lambda url: [from_pil(url2img_pil(url)), ])
            .action_classification.pytorchvideo['img', ('', '', 'feature')](model_name='x3d_m')
            .runas_op['feature', 'feature'](lambda feature: DataCollection([feature]).tensor_normalize().to_list()[0].tolist())
            .milvus_search['feature', 'result'](collection=collection, limit=10)
            .run()
    )
```
app_id 可以从 read_kafka 生成器拿出来，但不知道怎么传到milvus_search，[ ] 内可以填多个变量么，这样可以么？```.milvus_search['feature', 'result', 'app_id'](collection=collection, limit=10, expr='app_id== {app_id}')```

**Comment by yfq512** [comment]
> > @shiyu22 Thanks for your reply, another question, when I set ".set_parallel(5)" in "towhee.dc()", It don't work sometimes, and when I delete the line ".set_parallel(5)", It will work well always. Why?
> 
> Is there any error message? I met this issue before, but it's because no cuda memory, I think you can also check your memory changes.

没任何报错，主程序不退出，也没反应，我用的是cpu，感觉就像是线程里面的程序挂了，但towhee就像个黑盒不知道里面发生了什么。

**Comment by shiyu22** [comment]
Got it, I think what you need is to set the app_id parameter, for example:
```python
app_id=None
def set_app_id(x):
    global app_id
    app_id = x

(
    towhee.dc[('milvus_id', 'img_url', 'time', 'app_id')](read_kafka())
        .runas_op['img_url', 'img'](func=lambda url: [from_pil(url2img_pil(url)), ])
        .action_classification.pytorchvideo['img', ('', '', 'feature')](model_name='x3d_m')
        .runas_op['feature', 'feature'](func=lambda feature: DataCollection([feature]).tensor_normalize().to_list()[0].tolist())
        .runas_op['app_id', ''](func=set_app_id)
        .milvus_search['feature', 'result'](collection=collection, limit=10, expr=f'app_id== {app_id}')
        .run()
)

**Comment by yfq512** [comment]
@shiyu22 这样写的话，多线程 ".set_parallel( )" 还能用吗😄，可以在 milvus_search [] 内传多个参数么？

**Comment by yfq512** [comment]
> Got it, I think what you need is to set the app_id parameter, for example:
> 
> ```python
> app_id=None
> def set_app_id(x):
>     global app_id
>     app_id = x
> 
> (
>     towhee.dc[('milvus_id', 'img_url', 'time', 'app_id')](read_kafka())
>         .runas_op['img_url', 'img'](func=lambda url: [from_pil(url2img_pil(url)), ])
>         .action_classification.pytorchvideo['img', ('', '', 'feature')](model_name='x3d_m')
>         .runas_op['feature', 'feature'](func=lambda feature: DataCollection([feature]).tensor_normalize().to_list()[0].tolist())
>         .runas_op['app_id', ''](func=set_app_id)
>         .milvus_search['feature', 'result'](collection=collection, limit=10, expr=f'app_id=={app_id}')
>         .run()
> )
> ```

 这样写的话，多线程 ".set_parallel( )" 还能用吗😄，可以在 milvus_search [] 内传多个参数么？

**Comment by shiyu22** [comment]
I think set_parallel() will work. And the milvus_search operator just gets the query vector as the data parameter in [collection.search](https://milvus.io/docs/v2.1.x/search.md#Conduct-a-vector-search), so it cannot add muti-parameters in [].
