### ISSUE TITLE
[Bug]: ValueError: operator image-decode/cv2 not found!

### ISSUE THREAD

**Issue by wbc110460** [towhee-io/towhee#1818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Thanks for read this.
I just follow this guide,
https://codelabs.towhee.io/build-a-reverse-image-search-engine-in-minutes/index#2

And I meet the bug. ValueError: operator image-decode/cv2 not found!

How can i deal with it ?
Thank you for your help

### Expected Behavior

No

### Steps To Reproduce

```markdown
No
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

### Anything else?

No

**Comment by shiyu22** [comment]
Hi @wbc110460 , which version of towhee are you using? I think it required towhee>=0.7.

**Comment by wbc110460** [comment]
> Hi @wbc110460 , which version of towhee are you using? I think it required towhee>=0.7.

but my towhee is (0.8.0). emm

**Comment by wbc110460** [comment]
> > Hi @wbc110460 , which version of towhee are you using? I think it required towhee>=0.7.
> 
> but my towhee is (0.8.0). emm

Oh. I reinstalled it once again, and it ran.

**Comment by wbc110460** [comment]
> Hi @wbc110460 , which version of towhee are you using? I think it required towhee>=0.7.

but in this url:https://codelabs.towhee.io/build-a-reverse-image-search-engine-in-minutes/index#3
I can't find the func read_images :  (func=read_images) 
how can i deal with it?

**Comment by shiyu22** [comment]
> > Hi @wbc110460 , which version of towhee are you using? I think it required towhee>=0.7.
> 
> but in this url:https://codelabs.towhee.io/build-a-reverse-image-search-engine-in-minutes/index#3 I can't find the func read_images : (func=read_images) how can i deal with it?

You can refer to the [notebook](https://github.com/towhee-io/examples/blob/main/image/reverse_image_search/1_build_image_search_engine.ipynb), it seems that the website lacks this function, I will add it, thank you :)

**Comment by wbc110460** [comment]
您好。我看咱们towheel支持视觉问答模型。但是那些例子里没有视觉问答的。 最近你们准备上一个这样的吗？



发自我的iPhone


------------------ Original ------------------
From: shiyu22 ***@***.***&gt;
Date: Wed,Aug 24,2022 9:52 AM
To: towhee-io/towhee ***@***.***&gt;
Cc: 王炳超 ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [towhee-io/towhee] [Bug]: ValueError: operator image-decode/cv2 not found! (Issue #1818)





   
Hi @wbc110460 , which version of towhee are you using? I think it required towhee&gt;=0.7.
  
but in this url:https://codelabs.towhee.io/build-a-reverse-image-search-engine-in-minutes/index#3 I can't find the func read_images : (func=read_images) how can i deal with it?
  
You can refer to the notebook, it seems that the website lacks this function, I will add it, thank you :)
