### ISSUE TITLE
[Bug]: Task exceeded maximum timeout value (180 seconds)

### ISSUE THREAD

**Issue by utopictown** [towhee-io/towhee#1933]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Im running milvus app on top fastapi served using supervisord in a docker, and SOMETIMES i had ```Task exceeded maximum timeout value (180 seconds)``` from ```towhee/image-embedding-resnet50``` extractor, is there any way to increase the timeout? or do we have any lead that might cause this?

### Expected Behavior

successfully extracting the item

### Steps To Reproduce

```markdown
1. milvus app on top of fastapi
2. extractor run on queue with python RQ
3. served on supervisord inside docker
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): towhee/image-embedding-resnet50
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others: internet 4-5 Mbps
```

**Comment by junjiejiangjjj** [comment]
Did it happen after the docker container started, if so, it is downloading the model weights, you can build a new docker image that already has downloaded the weights.

**Comment by utopictown** [comment]
> 

how to get one? do you have any docker image example that already has downloaded the weights?

**Comment by junjiejiangjjj** [comment]
After installing towhee, you can run cmd `towhee run towhee/image-embedding-resnet50 -i  ${image_path}`, make sure the `image_path` can access when building the docker image.
In your dockerfile, you can add this
```dockerfile
RUN pip install towhee towhee.models
RUN towhee run towhee/image-embedding-resnet50 -i  image.jpg
```

**Comment by utopictown** [comment]
thank you, will try
