### ISSUE TITLE
[Bug]:   File "pydantic\json.py", line 45, in pydantic.json.lambda UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by suforme** [towhee-io/towhee#2071]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

from pymilvus import connections, FieldSchema, CollectionSchema, DataType, Collection, utility

connections.connect(host='192.168.0.101', port='19530')

def create_milvus_collection(collection_name, dim):
    if utility.has_collection(collection_name):
        utility.drop_collection(collection_name)
    
    fields = [
        FieldSchema(name='path', dtype=DataType.VARCHAR, descrition='path to image', max_length=500, 
                    is_primary=True, auto_id=False),
        FieldSchema(name='embedding', dtype=DataType.FLOAT_VECTOR, descrition='image embedding vectors', dim=dim)
    ]
    schema = CollectionSchema(fields=fields, description='reverse image search')
    collection = Collection(name=collection_name, schema=schema)

    index_params = {
        'metric_type':'L2',
        'index_type':"IVF_FLAT",
        'params':{"nlist":2048}
    }
    collection.create_index(field_name="embedding", index_params=index_params)
    return collection

import towhee
bench_collection = create_milvus_collection('resnet50', 2048)
(
towhee.glob['path']('train/test_me/*.JPEG')
    .image_decode['path', 'img']()
    .image_embedding.timm['img', 'vec'](model_name='resnet50')
    .tensor_normalize['vec', 'vec']()
    .ann_insert.milvus[('path', 'vec'), 'mr'](collection=bench_collection)
   )

import time
import towhee
from fastapi import FastAPI
from pymilvus import connections, Collection

app = FastAPI()
connections.connect(host='192.168.0.101', port='19530')
milvus_collection = Collection('resnet50')

@towhee.register(name='get_path_id')
def get_path_id(path):
    timestamp = int(time.time()*10000)
    id_img[timestamp] = path
    return timestamp

@towhee.register(name='milvus_insert')
class MilvusInsert:
    def __init__(self, collection):
        self.collection = collection

    def __call__(self, *args, **kwargs):
        data = []
        for iterable in args:
            data.append([iterable])
        mr = self.collection.insert(data)
        self.collection.load()
        return str(mr)

with towhee.api['file']() as api:
    app_insert = (
        api.image_load['file', 'img']()
        .save_image['img', 'path'](dir='tmp/images')
        .get_path_id['path', 'id']()
        .image_embedding.timm['img', 'vec'](model_name='resnet50')
        .tensor_normalize['vec', 'vec']()
        .milvus_insert[('id', 'vec'), 'res'](collection=milvus_collection)
        .select['id', 'path']()
        .serve('/insert', app)
    )

with towhee.api['file']() as api:
    app_search = (
        api.image_load['file', 'img']()
        .image_embedding.timm['img', 'vec'](model_name='resnet50')
        .tensor_normalize['vec', 'vec']()
        .milvus_search['vec', 'result'](collection=milvus_collection)
        .runas_op['result', 'res_file'](func=lambda res: str([x.id for x in res]))
        .select['res_file']()
        .serve('/search', app)
    )

with towhee.api() as api:
    app_count = (
        api.map(lambda _: milvus_collection.num_entities)
        .serve('/count', app)
        )

import uvicorn
import nest_asyncio

nest_asyncio.apply()
uvicorn.run(app=app, host='localhost', port=8000)

### Expected Behavior

![微信截图_20220913174203](https://user-images.githubusercontent.com/18099778/189869008-c6862d0a-e0c2-468c-9897-0fe36a125072.png)
![微信截图_20220913174221](https://user-images.githubusercontent.com/18099778/189869108-82f19259-6a74-4112-ad26-90a03513ce55.png)
![微信截图_20220913174248](https://user-images.githubusercontent.com/18099778/189869137-2f8599d9-56a9-4f83-a269-5fbd6bcbcb34.png)

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
@suforme thank you for the issue. 

Could you please provide which towhee version you are using?

**Comment by binbinlv** [comment]
@shiyu22 

Could you please help on this issue about milvus search scenario within towhee? thanks.

**Comment by shiyu22** [comment]
Hi @suforme, can you run with curl command, such as `curl -X POST "http://0.0.0.0:8000/search"  --data-binary @test/lion/n02129165_13728.JPEG -H 'Content-Type: image/jpeg'`?

BTW, you can try the [latest notebook](https://github.com/towhee-io/examples/blob/main/image/reverse_image_search/2_deep_dive_image_search.ipynb) and run with Body data in postman:
![image](https://user-images.githubusercontent.com/53459423/189887142-dadc2033-67cd-4756-a621-7f6a5a6056be.png)

**Comment by suforme** [comment]
> 

towhee               0.8.0
towhee.models        0.8.0

**Comment by suforme** [comment]
Python 3.10.6  @binbinlv
