### ISSUE TITLE
[Feature]: Is there any way to get towhee to support batch processing of images

### ISSUE THREAD

**Issue by zhenzi0322** [towhee-io/towhee#2076]
Example:
```python
import towhee


class Resnet50:
    """
    Say something about the ExampleCalass...

    Args:
        args_0 (`type`):
        ...
    """

    def resnet50_extract_feat(self, img_path):
        feat = towhee.glob(img_path) \
                     .image_decode() \
                     .image_embedding.timm(model_name='resnet50') \
                     .tensor_normalize() \
                     .to_list()
        return feat[0]
```

**Comment by shiyu22** [comment]
Towhee support `batch` interface to run the data in batch, you can refer to [this](https://towhee.readthedocs.io/en/main/data_collection/mixins.html#towhee.functional.mixins.DataProcessingMixin.batch). Is this interface what you want?

BTW, if you want to processing batch images, you can set the img_path as the paths matching a pathname pattern, such as `towhee.glon('all_img/*.jpg', 'all_img/*.png')`. And `set_parallel` [interface](https://towhee.readthedocs.io/en/main/data_collection/mixins.html#towhee.functional.mixins.ParallelMixin) will help to process image in multi parallel.
