### ISSUE TITLE
[DesignProposal]: Does it support Chinese picture description model?

### ISSUE THREAD

**Issue by suforme** [towhee-io/towhee#2091]
### Design

Does it support Chinese picture description model?

**Comment by wxywb** [comment]
Hi, currently you can combine two operators to get the result.
```python
import towhee
towhee.glob['path']('./girlanddog.jpeg') \
      .image_decode['path', 'img']() \
      .image_captioning.clipcap['img', 'en_text'](model_name='clipcap_coco') \
      .machine_translation.opus_mt['en_text', 'zh_text']('opus-mt-en-zh') \
      .select['img', 'en_text', 'zh_text']() \
      .show()
```
<img width="678" alt="飞书20221010-200300" src="https://user-images.githubusercontent.com/5432721/194862167-257e5d95-767b-4ef7-aedb-362341d24f40.png">
