### ISSUE TITLE
[Feature]: 使用embedding_pipline,参数必须是图片地址吗，可以是图片的numpy或者torch吗

### ISSUE THREAD

**Issue by God-song** [towhee-io/towhee#2099]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

使用embedding_pipline,参数必须是图片地址吗，可以是图片的numpy或者torch吗

### Describe the solution you'd like.

使用embedding_pipline,参数必须是图片地址吗，可以是图片的numpy或者torch吗

**Comment by wxywb** [comment]
Yes, let me show you an example.
```python
#using the path as input.
res = towhee.glob('./img.jpg') \
      .image_decode() \
      .image_embedding.timm(model_name='resnet50') \
      .to_list()
```
```python
#using np.array as input
img = cv2.imread('./img.jpg')
res = towhee.dc([img]) \
      .image_embedding.timm(model_name='resnet50') \
      .to_list()
```
In the second case, image_decode is no longer needed because the input is np.ndarray now.
