### ISSUE TITLE
[Bug]:  Image read exception

### ISSUE THREAD

**Issue by zhenzi0322** [towhee-io/towhee#2102]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Read the images:

![555798_8f802d268330d51b2d2410062a6d0209](https://user-images.githubusercontent.com/34839719/191684704-120d5fb9-e401-41bf-a260-7bc570ae680b.jpg)

errors:

![image](https://user-images.githubusercontent.com/34839719/191684782-58a0a420-0369-4939-be17-f0e7005f507e.png)

```python
import os
import towhee

class Resnet50:
    """
    Say something about the ExampleCalass...

    Args:
        args_0 (`type`):
        ...
    """

    def resnet50_extract_feat(self, img_path):
        feat = towhee.glob(img_path) \
            .image_decode() \
            .image_embedding.timm(model_name='resnet50') \
            .tensor_normalize() \
            .to_list()
        return feat[0]

    def bulk_resnet50_extract_feat(self, imgs_dir, num=100, is_del=True):
        feat = towhee.glob['path'](f'{imgs_dir}/*.jpg').head(num).image_decode['path', 'img']() \
            .image_embedding.timm['img', 'vec'](model_name='resnet50') \
            .tensor_normalize['vec', 'vec']().select['path', 'vec']()
        feat_list = feat.to_list()  # [<Entity dict_keys(['path', 'vec'])>, <Entity dict_keys(['path', 'vec'])>]
        vectors = []
        vectors_ids = []
        for i in feat_list:
            img_path = i.path
            file_name = os.path.split(img_path)[-1]
            v_id = file_name.split("_")[0]
            vectors.append(i.vec)
            vectors_ids.append(int(v_id))
            if is_del and os.path.exists(img_path):
                os.remove(img_path)
        return vectors, vectors_ids
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):  0.6.0
- OS(Ubuntu or CentOS): ubuntu
- CPU/Memory: 16c/62G
- GPU: GeForce RTX 2070
- Others:
```

**Comment by wxywb** [comment]
Hi, I downloaded your image and run with following code.
```python
import towhee

res = towhee.glob('./191684704-120d5fb9-e401-41bf-a260-7bc570ae680b.jpeg') \
      .image_decode() \
      .image_embedding.timm(model_name='resnet50') \
      .to_list()
```
It works fine.
Can you check with your opencv-python by
```python
cv2.imread('./191684704-120d5fb9-e401-41bf-a260-7bc570ae680b.jpeg')
```

**Comment by zhenzi0322** [comment]
> Hi, I downloaded your image and run with following code.
> 
> ```python
> import towhee
> 
> res = towhee.glob('./191684704-120d5fb9-e401-41bf-a260-7bc570ae680b.jpeg') \
>       .image_decode() \
>       .image_embedding.timm(model_name='resnet50') \
>       .to_list()
> ```
> 
> It works fine. Can you check with your opencv-python by
> 
> ```python
> cv2.imread('./191684704-120d5fb9-e401-41bf-a260-7bc570ae680b.jpeg')
> ```


```
opencv-python:  4.6.0.6
```

**Comment by wxywb** [comment]
@zhenzi0322 , you can read this pic(191684704-120d5fb9-e401-41bf-a260-7bc570ae680b.jpeg) with cv2 normally, but still have exception with this pipeline?
```python
res = towhee.glob('./191684704-120d5fb9-e401-41bf-a260-7bc570ae680b.jpeg') \
      .image_decode() \
      .image_embedding.timm(model_name='resnet50') \
      .to_list()
```
please confirm it once again.

**Comment by zhenzi0322** [comment]
[150084_d4ca9dd5639c6a0ee725c15d77a60358.zip](https://github.com/towhee-io/towhee/files/9623995/150084_d4ca9dd5639c6a0ee725c15d77a60358.zip)


Yes, now there is a new picture with anomalies

**Comment by wxywb** [comment]
can this works well for you while another is not? @zhenzi0322 
```python
img = cv2.imread('150084_d4ca9dd5639c6a0ee725c15d77a60358.jpg')
res = towhee.dc([img]) \
      .image_embedding.timm(model_name='resnet50') \
      .to_list()
```

**Comment by zhenzi0322** [comment]
> ```python
> img = cv2.imread('150084_d4ca9dd5639c6a0ee725c15d77a60358.jpg')
> ```

After using your way, it still doesn't work

**Comment by wxywb** [comment]
>What is your version of opencv-python

opencv-python                      4.5.5.64
>After using your way, it still doesn't work

so where is the exception, in **cv.imread** or **towhee.dc**?

**Comment by zhenzi0322** [comment]
That may be the problem caused by the version of opencv-python, I'll try to change to the same version as yours.

**Comment by zhenzi0322** [comment]
> can this works well for you while another is not? @zhenzi0322
> 
> ```python
> img = cv2.imread('150084_d4ca9dd5639c6a0ee725c15d77a60358.jpg')
> res = towhee.dc([img]) \
>       .image_embedding.timm(model_name='resnet50') \
>       .to_list()
> ```

This will report an error: 'numpy.ndarray' object has no attribute 'mode'.

**Comment by zhenzi0322** [comment]
![image](https://user-images.githubusercontent.com/34839719/191709737-d93712eb-8afd-4829-a5b1-38eaaec5035c.png)

**Comment by wxywb** [comment]
I guess you meet a opencv's issue, please take a look at other versions and retry. Make sure you can read an image in a regular cv2 method, and it will also works for towhee.

**Comment by zhenzi0322** [comment]
> I guess you meet a opencv's issue, please take a look at other versions and retry. Make sure you can read an image in a regular cv2 method, and it will also works for towhee.

The same version as yours is also not working

**Comment by wxywb** [comment]
A quick workaround is to using a docker image and run towhee inside it. 
or using Pillow instead of cv2
```python
from PIL import Image
img = Image.open('150084_d4ca9dd5639c6a0ee725c15d77a60358.jpg')
img = np.array(img)
res = towhee.dc([img]) \
      .image_embedding.timm(model_name='resnet50') \
      .to_list()
```

**Comment by zhenzi0322** [comment]
> 



> A quick workaround is to use a docker image and run towhee inside it. or using Pillow instead of cv2
> 
> ```python
> from PIL import Image
> img = Image.open('150084_d4ca9dd5639c6a0ee725c15d77a60358.jpg')
> img = np.array(img)
> res = towhee.dc([img]) \
>       .image_embedding.timm(model_name='resnet50') \
>       .to_list()
> ```



![image](https://user-images.githubusercontent.com/34839719/191715660-7a64a52b-43df-4951-90f6-371ab69d98d6.png)

**Comment by wxywb** [comment]
please update to a newer version. 
my version is:
towhee                                   0.8.0
towhee.models                      0.8.0

**Comment by zhenzi0322** [comment]
> please update your towhee to a newer version. my version is: towhee 0.8.0 towhee.models 0.8.0

Thanks, it's the towhee version that's the problem
