### ISSUE TITLE
[Documentation]: towhee how to set up multiple graphics cards to use at the same time, currently has been a graphics card in the extraction of dim

### ISSUE THREAD

**Issue by zhenzi0322** [towhee-io/towhee#2116]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

Hello, I have two graphics cards on my machine, and when I use towhee, I find that one graphics card is always in use and increasing the video memory, is there a way to set up towhee to use multiple graphics cards at the same time.

**Comment by binbinlv** [comment]
@zhenzi0322 
what you mean is that you want to input a picture list rather than only one picture when embedding?

**Comment by zhenzi0322** [comment]
> @zhenzi0322 what you mean is that you want to input a picture list rather than only one picture when embedding?

不是，是在`towhee`怎么使用多张gpu。

**Comment by binbinlv** [comment]
@junjiejiangjjj 

Could you help to answer this question? Thanks.

**Comment by zhenzi0322** [comment]
I want to know how towhee use multiple gpu

**Comment by junjiejiangjjj** [comment]
towhee doesn't support multiple GPU now

**Comment by zhenzi0322** [comment]
> towhee doesn't support multiple GPU now

Okay, so how do you specify the serial number of the gpu used?

**Comment by Chiiizzzy** [comment]
> 

import os
os.environ["CUDA_VISIBLE_DEVICES"] = '<device_number>'

**Comment by Chiiizzzy** [comment]
> > towhee doesn't support multiple GPU now
> 
> Okay, so how do you specify the serial number of the gpu used?

import os
os.environ["CUDA_VISIBLE_DEVICES"] = '<device_number>'

**Comment by zhenzi0322** [comment]
> > > towhee doesn't support multiple GPU now
> > 
> > 
> > Okay, so how do you specify the serial number of the gpu used?
> 
> import os os.environ["CUDA_VISIBLE_DEVICES"] = '<device_number>'

Okay, thanks

**Comment by jaelgu** [comment]
@zhenzi0322 Towhee does not support GPU inside its own framework. But it allows deep learning model to use cuda if device is specified inside operator.
So if you want to do anything related to device, you can modify the corresponding operator. (Find `device` in operator and assign device ids properly.)

**Comment by zhenzi0322** [comment]
> @zhenzi0322 Towhee does not support GPU inside its own framework. But it allows deep learning model to use cuda if device is specified inside operator. So if you want to do anything related to device, you can modify the corresponding operator. (Find `device` in operator and assign device ids properly.)

Ok.
