### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fishfl** [towhee-io/towhee#2123]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

我们是一个中国工程师团队，叫ai模型市场（aimodelmarket.cn），

我们将打包好的docker镜像卖个客户，以提供在线人工智能API。

我们惊喜的发现，我们的业务和towhee有很强的互补性。

如何有兴趣进一步合作，请联系我们 fishfl@163.com

期待您的来信。

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by fzliu** [comment]
It doesn't look like our two projects are quite the same, but cool project nonetheless. Thanks for getting in touch with us.
