### ISSUE TITLE
[DesignProposal]: Do you have a plan to make an example for "video question answer"?

### ISSUE THREAD

**Issue by wbc110460** [towhee-io/towhee#2132]
### Design

I saw that we provided the model for "video question answer"， but  I can't use the towhee to realize it. Can you let me know Do you have a plan to make an example for "video question answer"? Thank you for your answer.

**Comment by jaelgu** [comment]
@wbc110460 Check this operator out: https://towhee.io/towhee/vilt-vqa . You can find examples in the README.
