### ISSUE TITLE
[Documentation]: add all operator introduce

### ISSUE THREAD

**Issue by pengdaqian2020** [towhee-io/towhee#2182]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

some operator don't have document

like this 
![image](https://user-images.githubusercontent.com/71140907/194697961-b291790c-0842-4677-9ae9-48dfeb0a9a68.png)

or this
.pipeline_config(format_priority=['tensorrt', 'onnx'])

and I notice that https://towhee.io/ hub cannot register

I think that the improvement of document is most important now

**Comment by shiyu22** [comment]
Hi @pengdaqian2020, this pipeline includes three built-in functions(`dummy_input`, `pipeline_config` and `as_function`) and two operators(`image_decode.cv2_rgb` and `image_text_embedding.clip_image`), you can find all the operator in [this page](https://towhee.io/operators?limit=30&page=1), and refer to the [API docs](https://towhee.readthedocs.io/en/main/user_guide/index.html) for the func.
