### ISSUE TITLE
[DesignProposal]: Concat node in DagRepr

### ISSUE THREAD

**Issue by shiyu22** [towhee-io/towhee#2235]
### Background and Motivation

Each node in `dag_dict` will have `inputs` and `outputs` schema, each node in `dag_repr` will have `in_edges` and `out_edges`, and edges will record the schema of the data required by all subsequent nodes, so in the case of **concat,** their edges will be more complex, some we will support, but some can throw exception directly.

### Design

If the schema after concat node does not contain the previous schema we will support it, such as the following dag:
![p1](https://user-images.githubusercontent.com/53459423/198252625-b0cc638f-b1ed-417f-9919-efb9df4c278d.png)

And if the schema after concat node contains the previous schema:
>Update:  return the all used schema, and concat will update all the key-value.

1. The nodes before concat node do not modify the original data,  and the two in_edges from concat will both contain the original schema.

![p2](https://user-images.githubusercontent.com/53459423/198252737-72feeed8-25d7-4234-9894-6cb03e358ad1.png)

2. One node modified the original data.
It means on any incoming edge from concat, if a node after the forked node modified the data, and the two in_edges from concat will only one(the updated edges) contain the original schema.
![p3](https://user-images.githubusercontent.com/53459423/198252763-206c5743-b22d-4dd4-9aa5-9d08ff7b4131.png)

3. Both nodes modified the original data.
If the incoming edge from the concat botch modified the original data and the schema after concat node contains them, it will throw exception directly, because we don't know which data to choose.
![p4](https://user-images.githubusercontent.com/53459423/198252810-fa5a55e5-48eb-4af6-bead-cf9f00ac0b21.png)

**Comment by junjiejiangjjj** [comment]
```python
p1 = pipe.input('a')
p2 = p1.map('a', 'b')
p3 = p1.map('a', 'b')
p4 = p1.map('a', 'b')
p2.concat(p3, p4).output('b')

[p1, p2, p3]  read data in this order, and merge the data
for example:
>>> p1_data  ={'a': 1}
>>> p2_data = {'a': 2}
>>> p3_data = {'a': 3}
>>> ret ={}
>>> ret.update(p1_data)
>>> ret.update(p2_data)
>>> ret.update(p3_data)
>>> ret
{'a': 3}

**Comment by shiyu22** [comment]
> ```python
> p1 = pipe.input('a')
> p2 = p1.map('a', 'b')
> p3 = p1.map('a', 'b')
> p4 = p1.map('a', 'b')
> p2.concat(p3, p4).output('b')
> 
> [p1, p2, p3]  read data in this order, and merge the data
> for example:
> >>> p1_data  ={'a': 1}
> >>> p2_data = {'a': 2}
> >>> p3_data = {'a': 3}
> >>> ret ={}
> >>> ret.update(p1_data)
> >>> ret.update(p2_data)
> >>> ret.update(p3_data)
> >>> ret
> {'a': 3}
> ```

So will use the latest data(in the last pipeline) if there is the same schema?

**Comment by shiyu22** [comment]
The current DagRepr support to send all the data, and concat will cover the data before.
