### ISSUE TITLE
[Bug]: An error occurs when using 'lsS3' to view files

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2284]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/109071306/202390283-bdf67df0-b592-4956-a307-d5c2ca2cb3ea.png)
The s3-path is right. But i met an error when using towhee command 'lsS3'.
This is the error line mentioned above(s3.py).
![image](https://user-images.githubusercontent.com/109071306/202391258-6d2f4bb7-b6a9-45f6-8ecd-e1d401271f82.png)

### Expected Behavior

Succeed

### Steps To Reproduce

```markdown
towhee lsS3 -p s3://pretrainedweights.towhee.io/deepfake/v1.0/
or
towhee lsS3 -p s3://pretrainedweights.towhee.io/deepfake/
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.8.2.dev78
- Towhee.models: 0.8.2.dev76
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by zhujiming** [comment]
lsS3 command used like
`towhee lsS3 deepfake/v1.0/`
don't need bucket_name
![gQ30PEJLxo](https://user-images.githubusercontent.com/18031320/202442195-654b2f20-8c5f-4170-8e3e-18918be886aa.png)

**Comment by binbinlv** [comment]
@zhujiming 
could you improve the error message?

The "contents" is not meaningful about what the error is. Thanks.

**Comment by NicoYuan1986** [comment]
> lsS3 command used like `towhee lsS3 -p deepfake/v1.0/` don't need bucket_name ![gQ30PEJLxo](https://user-images.githubusercontent.com/18031320/202442195-654b2f20-8c5f-4170-8e3e-18918be886aa.png)

I'll retry.

**Comment by zhujiming** [comment]
@NicoYuan1986 @binbinlv Considering user habits, the query mode with bucket_names is supported. And if path is error, it will return not exist.#2292

**Comment by NicoYuan1986** [comment]
![image](https://user-images.githubusercontent.com/109071306/202637607-2b3e432c-d0ec-469a-b09c-a557ef03a805.png)
![image](https://user-images.githubusercontent.com/109071306/202638273-07f61e42-491a-4b7f-8927-1cdfa6f61d44.png)

lsS3 command Succeed.
