### ISSUE TITLE
[Bug]: Lack error checking of new pipeline node - input

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2285]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When empty, list, set or number is input, no exception is raised.I think it's not rigorous enough.

### Expected Behavior

Add error message

### Steps To Reproduce

```markdown
from towhee.dc2 import pipe, ops
p = pipe.input()
p = pipe.input({1})
p = pipe.input([2])
p = pipe.input(3)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.8.2.dev78
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
Pipeline should end with the `output` interface, else will do nothing.

**Comment by shiyu22** [comment]
We need to raise errors when run input() without args.

**Comment by junjiejiangjjj** [comment]
> We need to raise errors when run input() without args, right?

it's expected behavior, if we didn't call the `output`, do nothing

**Comment by shiyu22** [comment]
So when running `towhee.input().output()` got nothing is normal.
