### ISSUE TITLE
[Bug]: The order of usage of new pipeline node filter is not clear

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2287]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The order of usage of new pipeline node filter is not clear.
When executing
```
import towhee
from towhee.dc2 import pipe, ops

p = towhee.pipe.input('a').map('a', 'b', lambda x: x + 1).filter('a', 'b', 'a', lambda x: x > 10).output('b')
p(5).get()
```
The result is [6]. It seems the filter doesn't work.

However, when executing
```
p = towhee.pipe.input('a').filter('a', 'b', 'a', lambda x: x > 10).map('a', 'b', lambda x: x + 1).output('b')
p(5).get()
```
There is no response. This is expected.

### Expected Behavior

If the usage of filter need to satisfy some rules, The documents should show it.
if it's unexpected, we should fix it.

### Steps To Reproduce

```markdown
import towhee
from towhee.dc2 import pipe, ops

p = towhee.pipe.input('a').map('a', 'b', lambda x: x + 1).filter('a', 'b', 'a', lambda x: x > 10).output('b')
p(5).get()
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.8.2.dev78
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
The bug that filter doesn't work has been fixed. 
But the 'map' doesn't work.
For example,
```
import towhee
from towhee.dc2 import pipe, ops

p = towhee.pipe.input('a').map('a', 'b', lambda x: x + 1).filter('a', 'b', 'a', lambda x: x > 10).output('b')
p(12).get()
```
the correct result is [13], but got [12]. 
version: towhee-0.8.2.dev80
@junjiejiangjjj  ,could you please help look at it ?

**Comment by junjiejiangjjj** [comment]
> the correct result is [13], but got [12].
input              map               filter
a: 12   -> a: 12, b:13 -> a:12, b:12    
filter('a', 'b', 'a', lambda x: x > 10 )  col a will cover col b

**Comment by NicoYuan1986** [comment]
> it is correct input -> map -> filter a: 12 -> a: 12, b:13 -> a:12, b:12 filter('a', 'b', 'a', lambda x: x > 10 ) col a will cover col b

Thanks for your explanation.
