### ISSUE TITLE
[Feature]: Call operator static method without init args

### ISSUE THREAD

**Issue by jaelgu** [towhee-io/towhee#2312]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

Can we call a static method from a towhee operator without initialization the op? Check example op below:
```python
class ExampleOp(NNOperator):
    def __init__(self, model_name='model1'):
        self.model = create_model(model1, pretrained=True)
    
    def __call__(self, x):
        return self.model(x)
    
    @staticmethod
    def supported_model_names():
        return ['model1', 'model2', 'model3']
```

With example op above, how can I call `op.supported_model_names()` without loading any model? I tried current methods and it always initialize op:
```python
from towhee import ops

op = ops.name_space.op_name().get_op()
op.supported_model_names()
```

### Describe the solution you'd like.

Get op static call without initializing the op module.

**Comment by junjiejiangjjj** [comment]
Not easy to support it, and it is not in the plan.
