### ISSUE TITLE
[Documentation]: How can I extract picture for towhee by io

### ISSUE THREAD

**Issue by sulmz** [towhee-io/towhee#2313]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

I am using towhee to extract picture, but according to demo, it just can extract by url， as below code:
class ResNet50:
    def __init__(self):
        self.pipe = (towhee.dummy_input()
                    .image_decode()
                    .image_embedding.timm(model_name='resnet50')
                    .tensor_normalize()
                    .as_function()
        )
    #图片路径即url解压为向量
    # @staticmethod
    def resnet50_extract_feat(self, img_path):
        feat = self.pipe(img_path)
        if isinstance(feat, _Reason):
            raise feat.exception
        return feat

if __name__=='__main__':
  c = ResNet50()
  vector = c. resnet50_extract_feat(https://XXXXXXXXXXX)

how can I extract by io, maybe like code as below:
if __name__=='__main__':
  with open(r'd:\abc\123.jpg','rb')as file:
    pic_io = file
  c = ResNet50()
  vector = c. resnet50_extract_feat(pic_io)

### Why is this needed?

when client upload a picture, server receive a picture which is io. I prefer extract picture for io rather than  save picture first and extract a picture path

**Comment by sulmz** [comment]
by bytes both ok

**Comment by junjiejiangjjj** [comment]
Try this
```python
import cv2
import numpy as np

import towhee
from towhee.types import Image

def decode(content):
    arr = np.asarray(bytearray(content), dtype=np.uint8)
    return Image(cv2.imdecode(arr, -1), 'BGR')


pipe = (towhee.dummy_input()
        .runas_op(decode)
        .image_embedding.timm(model_name='resnet50')
        .tensor_normalize()
        .as_function()
)

with open('image_path', 'rb') as f:
    content = f.read()
    print(pipe(content))

**Comment by binbinlv** [comment]
@sulmz 
is it ok now?

**Comment by sulmz** [comment]
> Try this
> 
> ```python
> import cv2
> import numpy as np
> 
> import towhee
> from towhee.types import Image
> 
> def decode(content):
>     arr = np.asarray(bytearray(content), dtype=np.uint8)
>     return Image(cv2.imdecode(arr, -1), 'BGR')
> 
> 
> pipe = (towhee.dummy_input()
>         .runas_op(decode)
>         .image_embedding.timm(model_name='resnet50')
>         .tensor_normalize()
>         .as_function()
> )
> 
> with open('image_path', 'rb') as f:
>     content = f.read()
>     print(pipe(content))
> ```

thank you very much! it is work

**Comment by sulmz** [comment]
> @sulmz is it ok now?

yes
