### ISSUE TITLE
[Bug]: Lack download link of some resources

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2317]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lack download link of some resources.
https://github.com/towhee-io/examples/blob/main/nlp/text_search/search_article_in_medium.ipynb
```
FileNotFoundError: [Errno 2] No such file or directory: 'New_Medium_Data.csv'
```
![image](https://user-images.githubusercontent.com/109071306/205036352-8c97b5cf-2b47-4bff-87b1-3050dd66af91.png)

@shiyu22  Could you please help improve the documentation?

### Expected Behavior

succeed

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.9.0
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
another: https://github.com/towhee-io/examples/blob/main/data_science/credit_card_approval_prediction/credit_card_approval_prediction.ipynb
![image](https://user-images.githubusercontent.com/109071306/205044595-e03d0e5f-9018-44ce-8366-d564bc18c11c.png)

**Comment by NicoYuan1986** [comment]
Here the path is wrong.
![image](https://user-images.githubusercontent.com/109071306/205046608-8fa9a884-c280-4b85-a67f-6c0f94197f91.png)
https://github.com/towhee-io/examples/blob/main/audio/audio_fingerprint/audio_fingerprint_advanced.ipynb

**Comment by shiyu22** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### Current Behavior
> Lack download link of some resources. https://github.com/towhee-io/examples/blob/main/nlp/text_search/search_article_in_medium.ipynb
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: 'New_Medium_Data.csv'
> ```
> 
> ![image](https://user-images.githubusercontent.com/109071306/205036352-8c97b5cf-2b47-4bff-87b1-3050dd66af91.png)
> 
> @shiyu22 Could you please help improve the documentation?
> 
> ### Expected Behavior
> succeed
> 
> ### Steps To Reproduce
> _No response_
> 
> ### Environment
> ```gfm
> - Towhee version(e.g. v0.1.3 or 8b23a93):0.9.0
> - OS(Ubuntu or CentOS):
> - CPU/Memory:
> - GPU:
> - Others:
> ```
> 
> ### Anything else?
> _No response_

It said that the data is from Kaggle, you can download it from the link. And I will also add the link for another notebook.

**Comment by shiyu22** [comment]
Add link with [#128](https://github.com/towhee-io/examples/pull/128)

**Comment by NicoYuan1986** [comment]
Fixed
