### ISSUE TITLE
[Bug]: read audio error

### ISSUE THREAD

**Issue by haha010508** [towhee-io/towhee#2320]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

this is my code:

`import os
os.environ['CUDA_VISIBLE_DEVICES'] = '3'
import pandas as pd
import statistics
import gradio
import towhee

df = pd.read_csv('audio_fp/ground_truth.csv')
df.head()

@towhee.register
def get_gt(query_path):
    filename = query_path.split('/')[-1]
    name = filename.split('_')[1]
    answer = os.path.join('audio_fp', 'candidates', name + '.wav')
    return answer

example_query = df['query'][0]
example_candidate = df['answer'][0]

HOST = 'localhost'
PORT = '19530'
COLLECTION_NAME = 'nnfp'
INDEX_TYPE = 'IVF_FLAT'
METRIC_TYPE = 'IP'
DIM = 128
TOPK = 10
(
    towhee.read_audio(example_candidate)
          .batch(99999)
          .audio_embedding.nnfp()
          .show()
)` 
and when i run it, i got this
`TypeError: float() argument must be a string or a number, not 'av.audio.frame.AudioFrame'`

i think this is because av module have some problem.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by haha010508** [comment]
and my av==9.2.0

**Comment by jaelgu** [comment]
@haha010508 `towhee.read_audio` reads audio from path and returns audio frames. If your input is a list of audio frames, just use `towhee.dc([example_candidate])` to pass it into audio embedding op.
