### ISSUE TITLE
How to load the image from the path in batch mode?

### ISSUE THREAD

**Issue by check-777** [towhee-io/towhee#2328]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

` api.get_image_info_1['text', 'image_path']()
        .image_load['image_path','img']()`

this code puts all image into memory? Is that right? But if we have  5 million pictures，it must be out of memory.

### Expected Behavior

None

### Steps To Reproduce

```markdown
None
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

### Anything else?

None

**Comment by filip-halt** [comment]
There is the ability to do a streamed mode. By calling .stream() and .unstream() you should be able to avoid that problem. Not sure if it is compatible with the tabular mode but it should be.

**Comment by check-777** [comment]
> There is the ability to do a streamed mode. By calling .stream() and .unstream() you should be able to avoid that problem. Not sure if it is compatible with the tabular mode but it should be.

When I use .stream(),it has no different with .unstream(). By the way, .stream() can not work with set_parallel(),such as  towhee.from_df(df, True).stream().set_parallel(4). So, how to  input the path to image in batch, input the image to embedding in batch and input the embedding to  milvus  in batch mode?
