### ISSUE TITLE
[Feature]: How can I take a bag from pysintaller?

### ISSUE THREAD

**Issue by sulmz** [towhee-io/towhee#2334]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

I am developing a software which can search photo by photo.
I take a software bag from pyinstaller.
I want to use software for extract picture to vector and post it to server.(It can speed up time for transmit picture data)
When I am running on VS code, it is correct.
However, when I was take a bag, it is blocked. 
What happen?

import towhee
import numpy as np
from towhee.types import Image
import cv2
from towhee.functional.option import _Reason
#图片解压
class ResNet50:
    def __init__(self):
        self.url_pipe = (towhee.dummy_input()
                    .image_decode()
                    .image_embedding.timm(model_name='resnet50')
                    .tensor_normalize()
                    .as_function()
        )
        self.byte_pipe = (towhee.dummy_input()
        .runas_op(self.decode)
        .image_embedding.timm(model_name='resnet50')
        .tensor_normalize()
        .as_function()
)

    def decode(self,content):
        arr = np.asarray(bytearray(content), dtype=np.uint8)
        return Image(cv2.imdecode(arr, -1), 'BGR')

    #图片url解压为向量
    def extract_by_url(self, img_path):
        feat = self.url_pipe(img_path)
        if isinstance(feat, _Reason):
            raise feat.exception
        return feat

    #图片本地路径解压为向量
    def extract_by_byte(self,img_path):
        with open(img_path,'rb')as f:
            content = f.read()
            vector = self.byte_pipe(content)
            return vector

vector = ResNet50().extract_by_url('https://oss.mingzhouyun.com/test/O1CN01lXr5KC1RtRpHFHot2_!!669642169.jpg')
with open('/Users/sulimingzhou/Desktop/明洲云/test_towhee/logs/test.txt','w')as file:
    file.write(str(vector))

### Describe the solution you'd like.

I try extract from url and img_byte， both wrong

**Comment by junjiejiangjjj** [comment]
The image URL is not available, I try the pipeline with the right image URL is successful.

**Comment by sulmz** [comment]
I am using M1 MAX MAC, how about your env?@junjiejiangjjj

**Comment by sulmz** [comment]
> The image URL is not available, I try the pipeline with the right image URL is successful.
I am using M1 MAX MAC, how about your env?

**Comment by junjiejiangjjj** [comment]
> > The image URL is not available, I try the pipeline with the right image URL is successful.
> > I am using M1 MAX MAC, how about your env?

Ubuntu
