### ISSUE TITLE
[Bug]: Frequent access to github when yolov5 objects are created multiple times.

### ISSUE THREAD

**Issue by iebing** [towhee-io/towhee#2359]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When yolov5 objects are created for many times, the python hub load will request github for many times. If github is unstable, the service will exit abnormally

<img width="641" alt="image" src="https://user-images.githubusercontent.com/7081953/209786169-6718e53f-ed81-4451-8bd7-4076a86e3366.png">

<img width="1191" alt="image" src="https://user-images.githubusercontent.com/7081953/209786547-a43653c2-5faa-4ac0-aa8e-edbaed46c183.png">

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): v0.9.0
- OS(Ubuntu or CentOS): MacOS
- CPU/Memory: 4CPU、8G
- GPU:
- Others:
```

**Comment by shiyu22** [comment]
@iebing, can you show me the steps for this error? I can't reproduce it in my environment.

**Comment by shiyu22** [comment]
@iebing, I have reproduced it when I run the yolov5 op in different paths, and the weights(yolov5s.pt) will save to the working directory, so it will download multi times.

And I have uploaded the weights to [towhee hub](https://towhee.io/object-detection/yolov5/src/branch/main/models), and it will use the model with the specified path, so you can remove `~/.towhee/operators/object-detection/yolov5` and try  it again.

Note that the large weight is saved with git-lfs, so you should [install git-lfs](https://docs.github.com/en/repositories/working-with-files/managing-large-files/installing-git-large-file-storage) in your env, and you can check if you have successfully download the weight in `~/.towhee/operators/object-detection/yolov5/models`.

**Comment by iebing** [comment]
ok, I'll try,  Do I need to upgrade the version of towhee?

**Comment by shiyu22** [comment]
> ok, I'll try, Do I need to upgrade the version of towhee?

No. The code in the hub is independent.
