### ISSUE TITLE
[Bug]: Filter data is always None

### ISSUE THREAD

**Issue by shiyu22** [towhee-io/towhee#2364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I run the following code, the size of the results is always None:
```python
from towhee.dc2 import pipe, ops

obj_embedding = ( pipe.input('url')
        .map('url', 'img', ops.image_decode.cv2())
        .map('img', ('boxes', 'class', 'score'), ops.object_detection.yolov5())
        .filter(('img', 'boxes'), ('img', 'boxes'), 'boxes', lambda x: len(x) > 0) #comments it and try again
        .flat_map(('img', 'boxes'), 'object', ops.towhee.image_crop())
        .map('object', 'embedding', ops.image_embedding.timm(model_name='resnet50'))
        .output('class', 'score', 'embedding')
)
data = 'https://towhee.io/object-detection/yolov5/raw/branch/main/test.png'
res = obj_embedding(data)
res.size
```

But the image definitely has object and when I comments the filter node, it works fine. So there may be some bug in the Filter node.

### Expected Behavior

Filter node return the normal results.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
![image](https://user-images.githubusercontent.com/14136703/211293653-f7404cce-3a01-4af9-bac4-6e7696c3574f.png)
yolov node's input_schema is wrong
