### ISSUE TITLE
Model calculation dimension error

### ISSUE THREAD

**Issue by wangfaqing** [towhee-io/towhee#2368]
embedding_pipeline = pipeline('towhee/image-embedding-vit-large-patch32-384') , The dimension of their computer is 1024, GPU server results for 148480; 
embedding_pipeline = pipeline('towhee/image-embedding-vgg16'), The dimension of their computer is 4096, GPU server results for 512; 
What kind of question is that?

**Comment by wangfaqing** [comment]
close

**Comment by jaelgu** [comment]
@wangfaqing Which version is your towhee? It looks like this kind of pipeline is no longer maintained any more. I suggest to use this guide for image embedding:  https://towhee.io/image-embedding/timm
