### ISSUE TITLE
[Bug]: 无法离线使用towhee

### ISSUE THREAD

**Issue by chencoyote** [towhee-io/towhee#2373]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在离线环境下执行代码
import towhee
feat = towhee.glob('/home/50.jpg').image_decode().image_embedding.timm(model_name='resnet50').tensor_normalize().to_list()

出现如下报错：
gaierror                                  Traceback (most recent call last)
~/.conda/envs/ecdb/lib/python3.7/site-packages/urllib3/connection.py in _new_conn(self)
    174             conn = connection.create_connection(
--> 175                 (self._dns_host, self.port), self.timeout, **extra_kw
    176             )

~/.conda/envs/ecdb/lib/python3.7/site-packages/urllib3/util/connection.py in create_connection(address, timeout, source_address, socket_options)
     71
---> 72     for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
     73         af, socktype, proto, canonname, sa = res

~/.conda/envs/ecdb/lib/python3.7/socket.py in getaddrinfo(host, port, family, type, proto, flags)
    747     addrlist = []
--> 748     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
    749         af, socktype, proto, canonname, sa = res

gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

NewConnectionError                        Traceback (most recent call last)
~/.conda/envs/ecdb/lib/python3.7/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    709                 headers=headers,
--> 710                 chunked=chunked,
    711             )

~/.conda/envs/ecdb/lib/python3.7/site-packages/urllib3/connectionpool.py in _make_request(self, conn, method, url, timeout, chunked, **httplib_request_kw)
    385         try:
--> 386             self._validate_conn(conn)
    387         except (SocketTimeout, BaseSSLError) as e:

~/.conda/envs/ecdb/lib/python3.7/site-packages/urllib3/connectionpool.py in _validate_conn(self, conn)
   1041         if not getattr(conn, "sock", None):  # AppEngine might not have  `.sock`
-> 1042             conn.connect()
   1043

~/.conda/envs/ecdb/lib/python3.7/site-packages/urllib3/connection.py in connect(self)
    357         # Add certificate verification
--> 358         self.sock = conn = self._new_conn()
    359         hostname = self.host

~/.conda/envs/ecdb/lib/python3.7/site-packages/urllib3/connection.py in _new_conn(self)
    186             raise NewConnectionError(
--> 187                 self, "Failed to establish a new connection: %s" % e
    188             )

NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f2552810b70>: Failed to establish a new connection: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

MaxRetryError                             Traceback (most recent call last)
~/.conda/envs/ecdb/lib/python3.7/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    498                     retries=self.max_retries,
--> 499                     timeout=timeout,
    500                 )

~/.conda/envs/ecdb/lib/python3.7/site-packages/urllib3/connectionpool.py in urlopen(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, **response_kw)
    787             retries = retries.increment(
--> 788                 method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
    789             )

~/.conda/envs/ecdb/lib/python3.7/site-packages/urllib3/util/retry.py in increment(self, method, url, response, error, _pool, _stacktrace)
    591         if new_retry.is_exhausted():
--> 592             raise MaxRetryError(_pool, url, error or ResponseError(cause))
    593

MaxRetryError: HTTPSConnectionPool(host='towhee.io', port=443): Max retries exceeded with url: /api/v1/repos/towhee/image-decode (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2552810b70>: Failed to establish a new connection: [Errno -2] Name or service not known'))

During handling of the above exception, another exception occurred:

ConnectionError                           Traceback (most recent call last)
<ipython-input-2-046e00436460> in <module>
----> 1 feat = towhee.glob('/home/50.jpg').image_decode().image_embedding.timm(model_name='resnet50').tensor_normalize().to_list()

~/.conda/envs/ecdb/lib/python3.7/site-packages/towhee/hparam/hyperparameter.py in __call__(self, *args, **kwds)
    203
    204     def __call__(self, *args: Any, **kwds: Any) -> Any:
--> 205         return self._callback(self._path, self._index, *args, **kwds)
    206
    207

~/.conda/envs/ecdb/lib/python3.7/site-packages/towhee/functional/data_collection.py in wrapper(path, index, *arg, **kws)
    632                 _ = index
    633                 op = self.resolve(dispatcher, path, index, *arg, **kws)
--> 634                 return self.map(op)
    635
    636             callholder = hp.callholder(wrapper)

~/.conda/envs/ecdb/lib/python3.7/site-packages/towhee/functional/data_collection.py in map(self, *arg)
    352
    353         # smap map for stateful operator
--> 354         if hasattr(unary_op, 'is_stateful') and unary_op.is_stateful:
    355             return self.smap(unary_op)
    356

~/.conda/envs/ecdb/lib/python3.7/site-packages/towhee/engine/factory.py in is_stateful(self)
    105         with self._lock:
    106             if self._op is None:
--> 107                 self._create_op()
    108         return hasattr(self._op, 'fit')
    109

~/.conda/envs/ecdb/lib/python3.7/site-packages/towhee/engine/factory.py in _create_op(self)
    140         # pylint: disable=unused-variable
    141         with param_scope(index=self._index) as hp:
--> 142             self._op = op(self._name, self._tag, **self._kws)
    143
    144

~/.conda/envs/ecdb/lib/python3.7/site-packages/towhee/engine/factory.py in op(operator_src, tag, **kwargs)
     43         op_obj = loader.load_operator_from_path(operator_src, kwargs)
     44     else:
---> 45         op_obj = loader.load_operator(operator_src, kwargs, tag)
     46
     47     return op_obj

~/.conda/envs/ecdb/lib/python3.7/site-packages/towhee/engine/operator_loader.py in load_operator(self, function, args, tag)
    148                         self.load_operator_from_packages,
    149                         self.load_operator_from_cache]:
--> 150             op = factory(function, args, tag)
    151             if op is not None:
    152                 return op

~/.conda/envs/ecdb/lib/python3.7/site-packages/towhee/engine/operator_loader.py in load_operator_from_cache(self, function, args, tag)
    120         try:
    121             fm = FileManager()
--> 122             path = fm.get_operator(operator=function, tag=tag)
    123         except ValueError as e:
    124             raise ValueError('operator {} not found!'.format(function)) from e

~/.conda/envs/ecdb/lib/python3.7/site-packages/towhee/hub/file_manager.py in get_operator(self, operator, tag, install_reqs)
    443                 try:
    444                     git = GitUtils(author, repo)
--> 445                     git.clone(tag=tag, install_reqs=install_reqs, local_repo_path=repo_path)
    446                 # If user does not have git in the system, subprocess throws FileNotFound error.
    447                 except FileNotFoundError:

~/.conda/envs/ecdb/lib/python3.7/site-packages/towhee/utils/git_utils.py in clone(self, tag, install_reqs, local_repo_path)
     91         local_repo_path = Path(local_repo_path)
     92
---> 93         if not self.exists():
     94             engine_log.error('%s/%s repo does not exist.', self._author, self._repo)
     95             raise ValueError(f'{self._author}/{self._repo} repo does not exist.')

~/.conda/envs/ecdb/lib/python3.7/site-packages/towhee/utils/git_utils.py in exists(self)
     66         """
     67         try:
---> 68             response = HubUtils(self._author, self._repo).get_info()
     69             return response.status_code == 200
     70         except HTTPError as e:

~/.conda/envs/ecdb/lib/python3.7/site-packages/towhee/utils/hub_utils.py in get_info(self)
     67         """
     68         url = f'{self._root}/api/v1/repos/{self._author}/{self._repo}'
---> 69         response = requests.get(url)
     70         return response
     71

~/.conda/envs/ecdb/lib/python3.7/site-packages/requests/api.py in get(url, params, **kwargs)
     71     """
     72
---> 73     return request("get", url, params=params, **kwargs)
     74
     75

~/.conda/envs/ecdb/lib/python3.7/site-packages/requests/api.py in request(method, url, **kwargs)
     57     # cases, and look like a memory leak in others.
     58     with sessions.Session() as session:
---> 59         return session.request(method=method, url=url, **kwargs)
     60
     61

~/.conda/envs/ecdb/lib/python3.7/site-packages/requests/sessions.py in request(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)
    585         }
    586         send_kwargs.update(settings)
--> 587         resp = self.send(prep, **send_kwargs)
    588
    589         return resp

~/.conda/envs/ecdb/lib/python3.7/site-packages/requests/sessions.py in send(self, request, **kwargs)
    699
    700         # Send the request
--> 701         r = adapter.send(request, **kwargs)
    702
    703         # Total elapsed time of the request (approximately)

~/.conda/envs/ecdb/lib/python3.7/site-packages/requests/adapters.py in send(self, request, stream, timeout, verify, cert, proxies)
    563                 raise SSLError(e, request=request)
    564
--> 565             raise ConnectionError(e, request=request)
    566
    567         except ClosedPoolError as e:

ConnectionError: HTTPSConnectionPool(host='towhee.io', port=443): Max retries exceeded with url: /api/v1/repos/towhee/image-decode (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f2552810b70>: Failed to establish a new connection: [Errno -2] Name or service not known'))

导致无法通过towhee解析图片，后续代码无法执行

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by fzliu** [comment]
You'll need internet access if you want to use operators from the Towhee hub.
