### ISSUE TITLE
[Documentation]: How to Debug My towhee Code

### ISSUE THREAD

**Issue by geekchen007** [towhee-io/towhee#2380]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

For ordinary python programs, developers can click on the IDE such as vscode to view the source code, but the package of towhee can't do this. How should I view the source code and do unit tests?
```
	towhee.glob['video_url'](all_file_pattern).stream()
		.video_decode.ffmpeg['video_url', 'frames'](sample_type='time_step_sample', args={'time_step': 1})
		.get_image['frames', 'images']()
		.flatten('images')
		.drop_empty()
```

### Why is this needed?

Debug is a necessary function developed by every programmer

### Anything else?

None

**Comment by junjiejiangjjj** [comment]
example: https://towhee.io/video-decode/ffmpeg    
You can try the new interface （towhee 0.9.0）, compared with the old interface, the new one is more friendly to the IDE
```python
from towhee.dc2 import pipe, ops, DataCollection

p = (
    pipe.input('video_file')
    .flat_map('video_file', 'frame', ops.video_decode.ffmpeg(start_time=10.0, end_time=15.0, sample_type='time_step_sample', args={'time_step': 1}))
    .output('frame')
)

DataCollection(p('./video.mp4')).show(limit=1)
```
---
#### ops code:
ops.{namespace}.{name}  
    all ops are dynamic import, the code cache in ~/.towhee/operators/{namespace}/{name}

**Comment by binbinlv** [comment]
@geekchen007 
How is the answer above?

**Comment by geekchen007** [comment]
> @geekchen007 How is the answer above?

Thank you for your answer. It is recommended to update the tutorial to the wiki to help more new users

**Comment by binbinlv** [comment]
> > @geekchen007 How is the answer above?
> 
> Thank you for your answer. It is recommended to update the tutorial to the wiki to help more new users

OK, thanks for your recommendation.

**Comment by binbinlv** [comment]
@geekchen007 
And could you please close this issue if it solves your problem now, thanks.
