### ISSUE TITLE
[Feature]: 请问支持Audio/Text Multimodal吗

### ISSUE THREAD

**Issue by yanchaoguo** [towhee-io/towhee#2383]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

 包含训练好的文本-语音多模态模型 用于特征提取 ，构建一个文本->音频的检索系统

### Describe the solution you'd like.

 包含训练好的文本-语音多模态模型 用于特征提取 ，构建一个文本->音频的检索系统

### Describe an alternate solution.

 包含训练好的文本-语音多模态模型 用于特征提取 ，构建一个文本->音频的检索系统

### Anything else? (Additional Context)

 包含训练好的文本-语音多模态模型 用于特征提取 ，构建一个文本->音频的检索系统

**Comment by binbinlv** [comment]
Currently, towhee does not support this feature.
