### ISSUE TITLE
[Bug]: The date on Towhee website has not been updated

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2386]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://towhee.io/
At the bottom right of the page, it's still in 2022 as we can see. I think it should be modified to 2023
![image](https://user-images.githubusercontent.com/109071306/217133383-7a9ff6ec-a015-4481-a225-b42adf616dba.png)

### Expected Behavior

update

### Steps To Reproduce

https://towhee.io/

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
@NicoYuan1986 
could you please translate Chinese into English? Thanks.

**Comment by binbinlv** [comment]
@NicoYuan1986 
Fixed now, please verify, thanks.

**Comment by NicoYuan1986** [comment]
Verified fixed.
