### ISSUE TITLE
[Bug]: The model average_word_embeddings_komninos will get result 'nan' when testing sentence similarity

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2405]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The model average_word_embeddings_komninos will get result 'nan' when testing sentence similarity.

![7c9b61a1-9216-4be2-8361-cc306c7bc819](https://user-images.githubusercontent.com/109071306/218954909-78c06cf1-8ccd-4b8d-aa07-13ee1d7cd365.jpeg)

### Expected Behavior

succeed

### Steps To Reproduce

```markdown
1. sentence similarity setting
2. get the built-in sentence_similarity pipeline
3. generate embedding for one sentence
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
My code:
(config.normalize_vec defaults to true)

```python
from towhee.dc2 import AutoPipes, AutoConfig

# sentence similarity setting
config = AutoConfig.load_config('sentence_embedding')
config.model = 'gpt2-xl'
config.device = 0

# get the built-in sentence_similarity pipeline
sentence_embedding = AutoPipes.pipeline('sentence_embedding', config=config)
# generate embedding for one sentence
embedding = sentence_embedding('how are you?').get()
print(embedding)
```

**Comment by NicoYuan1986** [comment]
@junjiejiangjjj  Could you help take a look?

**Comment by junjiejiangjjj** [comment]
![image](https://user-images.githubusercontent.com/14136703/218956605-38667911-9be6-411c-b1c2-755b2008ef54.png)
Is this normal  @jaelgu

**Comment by NicoYuan1986** [comment]
Now the result can be searched with towhee==0.9.1.dev51.
![image](https://user-images.githubusercontent.com/109071306/219289994-335a50e3-1ed6-47b0-8f27-44de3f1eac8a.png)

but the embedding of the sentence is [0.0, 0.0, ... ]. Is this normal? 
![image](https://user-images.githubusercontent.com/109071306/219290247-2058778d-7214-4d6f-9e0f-31b4eb8716c2.png)
@junjiejiangjjj  @jaelgu
