### ISSUE TITLE
[Bug]: The error message is not clear when TextImageEmbeddingConfig param 'modality' is invalid

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The error message is not clear when TextImageEmbeddingConfig param 'modality' is invalid.
![image](https://user-images.githubusercontent.com/109071306/219293618-e8ada656-caab-4b82-ba9e-1ccdb06cd8bd.png)

![image](https://user-images.githubusercontent.com/109071306/219293675-30e677fb-4f4b-4c6d-baad-98808f43f6bb.png)

### Expected Behavior

The error message should be more clear.
UnboundLocalError: local variable 'p' referenced before assignment   ->  modality not exist or modality type error

### Steps To Reproduce

```markdown
from towhee.dc2 import AutoPipes, AutoConfig, pipe, ops

emb_conf = AutoConfig.load_config('text_image_embedding')
emb_conf.modality = 890
emb_pipe = AutoPipes.pipeline('text_image_embedding', emb_conf)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):towhee==0.9.1.dev51
- OS(Ubuntu or CentOS):Ubuntu
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
@junjiejiangjjj  Can you help make a difference? Thanks.

**Comment by binbinlv** [comment]
@NicoYuan1986 
please verify, thanks.

**Comment by NicoYuan1986** [comment]
Fixed!
