### ISSUE TITLE
[Bug]: The pipeline MilvusInsert config will constantly report error if param user and password not exist

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The pipeline MilvusInsert config will constantly report error if param user and password not exist.
Even if i stop it by KeyboardInterrupt, it doesn't work.
![image](https://user-images.githubusercontent.com/109071306/219569119-e6dc90c9-d7a7-4ad2-bfc4-d0fbd81dfc9a.png)
![image](https://user-images.githubusercontent.com/109071306/219569252-e643e513-0abe-4f1f-a485-9aaa949ce4f7.png)

### Expected Behavior

Report an error like 'user not exist'.

### Steps To Reproduce

```markdown
from towhee.dc2 import AutoPipes, AutoConfig

insert_conf = AutoConfig.load_config('insert_milvus')
insert_conf.collection_name = 'sentence_similarity'
insert_conf.user = 'kk'
insert_conf.password = '123456'
insert_pipe = AutoPipes.pipeline('insert_milvus', insert_conf)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.9.1.dev51
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
bug of `pymilvus`
```python
from pymilvus import connections, Collection

connections.connect(alias='test',
                    uri='https://localhost:19530',
                    user='kkkk',
                    password='fff',
                    secure = True
)
also has this problem

**Comment by NicoYuan1986** [comment]
![image](https://user-images.githubusercontent.com/109071306/219581575-1083aafe-c230-448f-9e66-0f48dad794ec.png)

![image](https://user-images.githubusercontent.com/109071306/219582682-46e76e82-b5d1-4769-9403-6016d5874232.png)
