### ISSUE TITLE
[Documentation]: [Notebook]We should load collection before searching

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

https://github.com/towhee-io/examples/blob/main/image/reverse_image_search/1_build_image_search_engine.ipynb

![image](https://user-images.githubusercontent.com/109071306/220052539-b2a45496-9838-49ba-87e1-3a184badc08d.png)

### Why is this needed?

Improve documentation.

**Comment by NicoYuan1986** [comment]
https://github.com/towhee-io/examples/blob/main/image/reverse_image_search/2_deep_dive_image_search.ipynb
![image](https://user-images.githubusercontent.com/109071306/220055507-770ebdf0-192a-41f7-b2b7-7320f7386dd1.png)

**Comment by NicoYuan1986** [comment]
@jaelgu  Can you help modify?

**Comment by NicoYuan1986** [comment]
https://github.com/towhee-io/examples/blob/main/image/reverse_image_search/2_deep_dive_image_search.ipynb

![image](https://user-images.githubusercontent.com/109071306/220506862-33148f22-2105-4f14-b7be-f48c42bb6194.png)
Need a newline

**Comment by jaelgu** [comment]
@NicoYuan1986 fixed by https://github.com/towhee-io/examples/pull/174

**Comment by NicoYuan1986** [comment]
Fixed.
