### ISSUE TITLE
[Bug]: [Notebook]Model image-text-embedding/clip has an import error

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Model image-text-embedding/clip has an import error.
https://github.com/towhee-io/examples/blob/main/image/text_image_search/2_deep_dive_text_image_search.ipynb
When i run this part, an error occurred.
![image](https://user-images.githubusercontent.com/109071306/220294238-81d5ff97-7237-46d3-82c8-507e7a45b8fe.png)

error:
![image](https://user-images.githubusercontent.com/109071306/220294389-9d49d314-1e3d-4231-97f7-06b6987ee114.png)

### Expected Behavior

succeed

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.9.1.dev55
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
@wxywb  Can you help me?

**Comment by wxywb** [comment]
ipdb is removed, it is only for debug purpose.

**Comment by NicoYuan1986** [comment]
Fixed.
