### ISSUE TITLE
[Bug]: [Notebook]The picture is gone in the example of image_animation

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The picture is gone in the example of image_animation.
https://github.com/towhee-io/examples/blob/main/image/image_animation/example.ipynb
![image](https://user-images.githubusercontent.com/109071306/220300795-69fb977b-bca0-479c-8eab-c349925ee84d.png)

### Expected Behavior

add the picture

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.9.1.dev55
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jaelgu** [comment]
@NicoYuan1986 Fixed by https://github.com/towhee-io/examples/pull/162. Please re-check.

**Comment by NicoYuan1986** [comment]
Fixed.
