### ISSUE TITLE
[Bug]: [Notebook]Insert data cost too long over 2 hours using image_decode

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2424]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/towhee-io/examples/blob/main/image/reverse_image_search/2_deep_dive_image_search.ipynb
When I get to this step:
![image](https://user-images.githubusercontent.com/109071306/220538936-4efc986f-59a6-493a-8140-373fe7b6e82a.png)

It last over 2 hours. Is it normal? Or It need some device?

### Expected Behavior

succeed

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.9.1.dev55
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jaelgu** [comment]
@NicoYuan1986  It's not normal...it should be similar as 1_reverse_image_search. Can you make sure milvus is ready and try again?

**Comment by NicoYuan1986** [comment]
Fixed.
