### ISSUE TITLE
[Bug]: Pipe will return an unexpected answer when 'batch' get an invalid input 'set'

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pipe will return an unexpected answer when 'batch' get an invalid input 'set'.
![image](https://user-images.githubusercontent.com/109071306/220570584-8637e3b7-410c-4335-a261-54d5577aa748.png)

### Expected Behavior

raise exception or handle it correctly.

### Steps To Reproduce

```python
from towhee.dc2 import pipe, ops
p = pipe.input('a').map('a', 'b', lambda x: x + 1).output('b')
res = p.batch({1, 0})
[r.get() for r in res]
# [[1], [2]]

res = p.batch({1, 9, 8})
[r.get() for r in res]
# [[9], [2], [10]]
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.9.1.dev55
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
For the batch interface, all iterable data is legal, the user should be responsible for the input data.
for example, I can use `set` to remove duplicate URLs.
```python
p = (
  pipe.input('url')
  .map('url', 'image', ops.image_decode.cv2())
  .map('image', 'vec', ops.image_embedding.timm())
  .map('vec', (), ops.ann_insert.milvue())
 .output()
)

p.batch(set(['url1', 'url2', 'url1']))
