### ISSUE TITLE
[Bug]: [Notebook]Lack some packages provided to run fine tune

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2430]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Lack some packages provided to run fine tune.
https://github.com/towhee-io/examples/blob/main/fine_tune/5_train_cub_200_2011.ipynb
![image](https://user-images.githubusercontent.com/109071306/220810400-303c9c81-3a4e-4f11-8935-f3dec2c83ebb.png)

### Expected Behavior

succeed

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by zc277584121** [comment]
fix:
https://github.com/towhee-io/examples/pull/172

**Comment by NicoYuan1986** [comment]
Fixed.
