### ISSUE TITLE
[Bug]: Video Copy Detection search failed using leveldb

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2436]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/109071306/221511451-0b013bb2-990f-4af6-abe8-a53df4daf5fd.png)

### Expected Behavior

pass

### Steps To Reproduce

```markdown
1. create a collection
2. Video Embedding and insert data
3. search -> raise error
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.9.1.dev55
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by Chiiizzzy** [comment]
del previous pipeline to release leveldb lock before running next pipeline. I suggest you delete existing url_vec.db folder first, then run your embedding pipeline, before running search pipeline, del embedding pipeline.

**Comment by NicoYuan1986** [comment]
Resolved by del insert_pipe
