### ISSUE TITLE
[Documentation]: Some scenes need more clear error message about Video Copy Detection 

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

Some scenes need more clear error message

**Comment by NicoYuan1986** [comment]
1. When the model is not consistent in video_embedding config and video_copy_detection config, the error message is not clear.
for example, 
......
insert_conf.model='tnt_s_patch16_224'
......
search_conf.model='isc'
....
error message should be like 'The model should be consistent'..

**Comment by Chiiizzzy** [comment]
Since these are two separated pipelines, system has no information on users' model selection, so I'm afraid we cannot offer such error message. This is what users should pay attention to.
