### ISSUE TITLE
[Bug]: The VideoCopyDetectionConfig param top_k will always be 3 once it was set 3

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2439]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The first time, i set VideoCopyDetectionConfig top_k=3
```
search_conf = AutoConfig.load_config('video_copy_detection')
search_conf.collection='video_copy_detection'
search_conf.model='tnt_s_patch16_224'
search_conf.device = -1
search_conf.hbase_table = 'video_copy_detection'
search_conf.top_k=3
search_pipe = AutoPipes.pipeline('video_copy_detection', search_conf)
```
3 results are returned as expected.

The second time, i delete the param topK.
```
search_conf = AutoConfig.load_config('video_copy_detection')
search_conf.collection='video_copy_detection'
search_conf.model='tnt_s_patch16_224'
search_conf.device = -1
search_conf.hbase_table = 'video_copy_detection'
search_pipe = AutoPipes.pipeline('video_copy_detection', search_conf)
```
However, i get 3 results once again.
I think it should work as default.
![image](https://user-images.githubusercontent.com/109071306/221740916-b2615891-90f1-44db-85cc-5d048feeeb81.png)

### Expected Behavior

return 5

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.9.1.dev55
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
@Chiiizzzy  Could you help resolve it?

**Comment by Chiiizzzy** [comment]
Check your training and testing set size. I suppose you have only inserted 3 videos similar to the query one.

**Comment by NicoYuan1986** [comment]
Resolved！
