### ISSUE TITLE
[Bug]: Advise add milvus_host parameter in pipe VideoCopyDetectionConfig

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Now that we provide milvus_host and milvus_port in VideoEmbeddingConfig by which we can insert data to wanted place, The same parameter should be provided in VideoCopyDetectionConfig, which is for search function.
Or VideoCopyDetectionConfig can use milvus host and port in VideoEmbeddingConfig.

At present, we can only search with milvus host 127.0.0.1

### Expected Behavior

make some changes

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.9.1.dev55
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by Chiiizzzy** [comment]
We do provide milvus related config in VideoCopyDetectionConfig, https://github.com/towhee-io/towhee/blob/8b1574115dc38fa64181b8655cd88a48e1cefa65/towhee/pipelines/video_copy_detection.py#L58

**Comment by NicoYuan1986** [comment]
Not mentioned in document. So i don't know it. we need update.
