### ISSUE TITLE
[Bug]: Inserting multiple object embeddings using to_milvus() method in batch mode

### ISSUE THREAD

**Issue by solomonmanuelraj** [towhee-io/towhee#2449]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi towhee team, 
We have followed the below link code for yolo5 based object detection and embedding the max area object in milvus using to_milvus() function. https://codelabs.towhee.io/deep-dive-into-reverse-image-search-with-towhee/index
In our requirement instead of max area object we need to insert all the identified objects (e.g. 10 objects/15 objects in a image) need to be embedded in the milvus. when we use to_milvus() method we could not insert multiple objects embedding at the same time. 
we need the sample code of multiple object embedding using to_milvus() method .

your help will be very useful. thanks in advance. 

### Expected Behavior

multiple objects embedding using to_milvus() method

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
@junjiejiangjjj 
could you please answer this question?

Thanks.

**Comment by junjiejiangjjj** [comment]
towhee >= 0.9
In this way, the embedding will insert into Milvus one by one.
```python
from towhee.dc2 import ops, pipe
obj_embedding = (
    pipe.input('url')
    .map('url', 'img', ops.image_decode.cv2_rgb())
    .flat_map('img', ('box', 'class', 'score'), ops.object_detection.yolo())
    .flat_map(('img', 'box'), 'object', ops.towhee.image_crop())
    .map('object', 'embedding', ops.image_embedding.timm(model_name='resnet50'))
    .map('embedding', 'mr', ops.ann_insert.milvus_client(host='', port='', collection_name=''))
    .output('mr')
)
obj_embedding(image_path)
```
if you want to do batch-insert, use towhee to get the embeddings, and pymilvus to insert.
```python
from towhee.dc2 import ops, pipe
obj_embedding = (
    pipe.input('url')
        .map('url', 'img', ops.image_decode.cv2_rgb())
        .flat_map('img', ('box', 'class', 'score'), ops.object_detection.yolo())
        .flat_map(('img', 'box'), 'object', ops.towhee.image_crop())
        .map('object', 'embedding', ops.image_embedding.timm(model_name='resnet50'))
        .output('embedding')
    ) 
embeddings = obj_embedding(image_path).to_list()
# use pymilvus to insert embeddings

**Comment by junjiejiangjjj** [comment]
towhee pipeline is a callable object,  you can do like this, 
get an image's embeddings, and insert them into milvus.

```python
# define embedding pipeline, 
...
# call it
for image in image_list:
    embedings = obj_embedding(image).to_list()
    # insert to milvus

**Comment by solomonmanuelraj** [comment]
Thanks for your quick response.
