### ISSUE TITLE
[Bug]: The filter seems not always work

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2470]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The filter seems not always work.

Before, it went well in ci.
![image](https://user-images.githubusercontent.com/109071306/225543461-1b1425fd-548a-41ed-ab79-d3d9bd3269a3.png)

When i update the towhee version in #2467 to 0.9.1.dev78, The case failed.
Here the filter seems not work.
![image](https://user-images.githubusercontent.com/109071306/225543804-427dd4b6-0adc-4ed3-b4cc-e40f9909889e.png)

### Expected Behavior

get right answer

### Steps To Reproduce

```markdown
q = towhee.pipe.input('a').filter('a', 'b', 'a', lambda x: x > 10)\
    .map('a', 'b', lambda x: x + 1).output('b')
q(5).get()
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.9.1.dev78
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
filter('a', 'b', 'a', lambda x: x > 10)  the filter will not change the `a` col,  for the filter result will insert into `b` col
filter('a', 'a', 'a', lambda x: x > 10)  this will change the `a` col.

**Comment by NicoYuan1986** [comment]
Got it. I'll change the concerned cases
