### ISSUE TITLE
[Bug]: The new command 'lsS3' and 'downloadS3' do not work with the latest towhee version

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2471]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The new command 'lsS3' and 'downloadS3' do not work with the latest towhee version.

For example, lsS3:
![image](https://user-images.githubusercontent.com/109071306/225552367-5c6ba302-927d-40ba-af63-22240564febf.png)

locally, towhee=0.9.1.dev66
![image](https://user-images.githubusercontent.com/109071306/225552518-e6ce2d62-df4c-4b89-ae49-96c329603b6f.png)

towhee=0.9.1.dev78,
![image](https://user-images.githubusercontent.com/109071306/225552682-3ba02049-aa1d-4324-a92e-5180d784600c.png)

### Expected Behavior

succeed

### Steps To Reproduce

```markdown
towhee lsS3 -p test/test.pt
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.9.1.dev78
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
`s3` has been removed.

**Comment by NicoYuan1986** [comment]
OK, I'll skip linked cases.
