### ISSUE TITLE
[Feature]: How can i custom pretained model path like transformers from_pretrain?

### ISSUE THREAD

**Issue by Mewral** [towhee-io/towhee#2491]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

I've searched all the documents and couldn't find a way to custom my pre-trained model path.

### Describe the solution you'd like.

custom pre-trained model path

**Comment by Mewral** [comment]
@shiyu22 I'm using image_text_embedding.taiyi. I found that the operator is downloaded in local folder. Can i just modify local operator file?

**Comment by wxywb** [comment]
It seems you  you have a customized trained taiyi model, you want to use your own trained weights. right?

**Comment by Mewral** [comment]
Yes. how can i do that? Thank you

**Comment by Mewral** [comment]
Much appreciated!

**Comment by Mewral** [comment]
Exactly! Thanks again!

**Comment by wxywb** [comment]
sure, you need to find the your operator path ,  it supposed in the '~/.towhee/'
```shell
find ~/.towhee/operators/ -name "taiyi"
```
