### ISSUE TITLE
[Documentation]: replace Lena image

### ISSUE THREAD

**Issue by kgeis** [towhee-io/towhee#2499]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

I would like to see a different image to demonstrate the capabilities of the [Image Crop operator](https://towhee.io/tasks/detail/operator?field_name=Computer-Vision&task_name=Image-Crop).

### Why is this needed?

The use of a Playboy centerfold image perpetuates a culture of sexism and objectification.

### Anything else?

![image](https://user-images.githubusercontent.com/2237299/229269858-16df21d9-8154-4dec-b6c0-528e2c206d18.png)

**Comment by wxywb** [comment]
Thanks for your kindly reminder. We used the image because it is widely used in computer vision community in past years. We will replace the logo of this operator to show the respect to Lena.

**Comment by spacewalkingninja** [comment]
There is no documentation on how to use the video question answering thing. @kgeis would you kindly mind if I assign you to give me a way to use this towhee thing so that I input mp4 and I get description of what is happening in the MP4. 
Thanks.

**Comment by kgeis** [comment]
> There is no documentation on how to use the video question answering thing. @kgeis would you kindly mind if I assign you to give me a way to use this towhee thing so that I input mp4 and I get description of what is happening in the MP4. Thanks.

Yes, I would mind. I am not a developer of this software. Feel free to create a separate issue, and do not assign it to me.

**Comment by wxywb** [comment]
we have replaced the image of image crop operator. Thanks for Lena for her contribution to computer vision community.

**Comment by spacewalkingninja** [comment]
> > There is no documentation on how to use the video question answering thing. @kgeis would you kindly mind if I assign you to give me a way to use this towhee thing so that I input mp4 and I get description of what is happening in the MP4. Thanks.
> 
> @spacewalkingninja Yes, I would mind. I am not a developer of this software. Feel free to create a separate issue, and do not assign it to me.

I would like you to help me, seeing that you have the time and are such a thoughtful person that makes it a personal must to improve in the best possible way the git software on which you posted the issue. I think you are the best fit, considering your deep undestanding of computer vision and the special importance your soul gives to fixing the issues that are of the upmost importance to improve this software. I hope you accept my request.
