### ISSUE TITLE
[Bug]: Got "TypeError: cannot pickle '_thread.lock' object" when call pipe.input().map().output()

### ISSUE THREAD

**Issue by bruce-zhu01** [towhee-io/towhee#2500]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

**I try to run the sample codes,**

`from towhee import pipe, ops, DataCollection

p = (
    pipe.input('text')
    .map('text', 'vec', ops.text_embedding.dpr(model_name='facebook/dpr-ctx_encoder-single-nq-base'))
    .output('text', 'vec')
)`

**I try to run the codes above but got error:**

`File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/towhee/runtime/pipeline.py:103, in Pipeline.output(self, *output_schema, **config_kws)
    100 output_schema = self._check_schema(output_schema)
    102 uid = OutputConst.name
--> 103 dag_dict = deepcopy(self._dag)
    104 dag_dict[uid] = {
    105     'inputs': output_schema,
    106     'outputs': output_schema,
   (...)
    111     'next_nodes': None,
    112 }
    113 dag_dict[self._clo_node]['next_nodes'].append(uid)

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/copy.py:146, in deepcopy(x, memo, _nil)
    144 copier = _deepcopy_dispatch.get(cls)
...
--> 161     rv = reductor(4)
    162 else:
    163     reductor = getattr(x, "__reduce__", None)

TypeError: cannot pickle '_thread.lock' object`

### Expected Behavior

the sample code should work

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.9.0
- OS(Ubuntu or CentOS): CentOS
- CPU/Memory: 32G
- GPU: 8G
- Others: Python 3.9.7
```

**Comment by shiyu22** [comment]
Hi @bruce-zhu01, can you check this issue [#185](https://github.com/towhee-io/examples/issues/185)?
