### ISSUE TITLE
[Bug]: In git_utils.py, why does the cloned repo forcibly designated as a local repo?

### ISSUE THREAD

**Issue by jin1ming** [towhee-io/towhee#2503]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When my project was hosted by a self built git website such as xxx.com, I used the towhee package, but it was searched and cloned on my git website(xxx.com)，and not yours repo!

### Expected Behavior

I think when towhee checks for updates or clones, it uses repo from Github.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS): ubuntu 20.04
- CPU/Memory:i7 12700
- GPU:1650
- Others:
```

**Comment by jin1ming** [comment]
@Chiiizzzy @shiyu22 I think this issue is related to you.

**Comment by Chiiizzzy** [comment]
Could you please describe your issue more specifically, like how to reproduce, and what is the error message.

**Comment by Chiiizzzy** [comment]
Seems you are using a local repo as your decoder, we have two options to solve your issue:
- Define your decode operator and use `register` decorator to wrap it, then you can use your own decoder with `ops.image_decode()`;
- Use our pre-defined decode operator from https://towhee.io/tasks/detail/operator?field_name=Computer-Vision&task_name=Image-Decode
