### ISSUE TITLE
[Documentation]: New DataCollection API

### ISSUE THREAD

**Issue by pakelley** [towhee-io/towhee#2546]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

I'd like to know how to, for example, load a directory of image files into a `DataCollection` and map operations over it. It seems that the current `DataCollection` docs haven't been updated for the new API, and I (a new user) haven't been able to figure out how to load my data into towhee.
When I `from towhee import DataCollection` I get a function, with none of the `DataCollection` class methods. When I `from towhee.datacollection import DataCollection` then run e.g. `data = DataCollection([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])`, the `__init__` expects some `"schema"` attribute that I don't know what to do with.

I saw from the GH issues that there was a `towhee.dc2` before, is there a `towhee.dc1` or something for now that I can use for now to use the documented API?

### Why is this needed?

It's not currently clear how to load data into the new DataCollection api, or how to map a pipeline over a dataset in parallel.

**Comment by junjiejiangjjj** [comment]
The newest [docs](https://towhee.readthedocs.io/en/latest/user_guide/index.html), all [examples](https://github.com/towhee-io/examples), need towhee 1.0.0rc1
`pip install towhee==1.0.0rc1`
An example to deal with images 
```python 
from glob import glob
from towhee import ops, pipe
# define an image embedding pipeline:
p = (
    pipe.input('path')
    .map('path', 'img', ops.image_decode.cv2('rgb'))
    .map('img', 'vec', ops.image_text_embedding.clip(model_name='clip_vit_base_patch16', modality='image'))
    .output('vec')
)

# process images
images = glob('./*jpg')
for image in images:
    vec = p(image).to_list()[0][0]

```
