### ISSUE TITLE
[Feature]: Pipeline: Image Embedding using resnet50

### ISSUE THREAD

**Issue by codeformeaning** [towhee-io/towhee#2548]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

the shape of output embedding is shape: (1, 2048), can i get (1, 64) or (1, 32) ?
---------------------
Pipeline Output:
The pipeline returns a tuple Tuple[('feature_vector', numpy.ndarray)] containing following fields:
feature_vector:
the embedding of input image
data type: numpy.ndarray
shape: (1, 2048)

**Comment by junjiejiangjjj** [comment]
Currently, the smallest is resnet18, which is 512 dimensions. You can try some dimensionality reduction methods provided by sklearn.

**Comment by codeformeaning** [comment]
> Currently, the smallest is resnet18, which is 512 dimensions. You can try some dimensionality reduction methods provided by sklearn.

thanks vert much !
