### ISSUE TITLE
[Bug]: concurrent running model process error

### ISSUE THREAD

**Issue by iebing** [towhee-io/towhee#2553]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

在利用milvus demo 的 image_server 服务跑并发测试过程，模型出现并发问题。

### Expected Behavior

image_server 服务能够支持并发请求，而不是串行执行。

### Steps To Reproduce

```markdown
1、把fastapi的async去除。
2、用jmetter 10个线程并发打api服务。
3、跑的过程encode中的pipline会被多次加载，最后报错。
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): v0.9.0
- OS(Ubuntu or CentOS):CentOS
- CPU/Memory: 24CPU\92GMemory
- GPU: Tesla T4
- Others:
```

**Comment by iebing** [comment]
![Uploading image.png…]()
跑的过程报这个错误！

**Comment by iebing** [comment]
<img width="922" alt="image" src="https://github.com/towhee-io/towhee/assets/7081953/8bcd4795-9882-4234-810d-8829a0a4a219">
跑的过程报这个错误！

**Comment by shiyu22** [comment]
Hi @iebing, can you try this issue [#1140](https://github.com/milvus-io/bootcamp/issues/1140)?
