### ISSUE TITLE
[Bug]: Fail to run pipeline as a node with error Symbol not found

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2575]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Fail to run pipeline as a node with error Symbol not found.
https://towhee.readthedocs.io/en/main/pipeline/usage.html#pipeline-act-as-node
![image](https://github.com/towhee-io/towhee/assets/109071306/e629e90d-d8cb-4536-a2bf-ed55695832ba)

```
>>> from towhee import pipe, ops
>>> 
>>> img_embedding = (
...     pipe.input('url')
...         .map('url', 'img', ops.image_decode.cv2())
...         .map('img', 'embedding', ops.image_embedding.timm(model_name='resnet50'))
...         .output('embedding')
... )
/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: dlopen(/Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/torchvision/image.so, 0x0006): Symbol not found: __ZN3c106detail19maybe_wrap_dim_slowExxb
  Referenced from: /Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/torchvision/image.so
  Expected in: /Users/zilliz/virtual-environment/towhee/lib/python3.10/site-packages/torch/lib/libc10.dylib
  warn(f"Failed to load image Python extension: {e}")

```

### Expected Behavior

pass

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
Another warning:
https://towhee.readthedocs.io/en/main/operator/usage.html#running-operators
![image](https://github.com/towhee-io/towhee/assets/109071306/56b35cae-bfb7-4c13-bdeb-38b2297f31d4)

![image](https://github.com/towhee-io/towhee/assets/109071306/1aa6c427-0c8c-4cdb-80eb-e63a25538a81)

**Comment by junjiejiangjjj** [comment]
It seems the wrong torchvision was installed, try reinstalling it.

**Comment by NicoYuan1986** [comment]
Fixed.
