### ISSUE TITLE
[Bug]: Run operator question-answer failed reporting 'Response' object has no attribute 'context'

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2576]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Run operator question-answer failed reporting 'Response' object has no attribute 'context'.
https://towhee.io/prompt/question-answer
![image](https://github.com/towhee-io/towhee/assets/109071306/53e27ff7-1a57-4380-aa01-813694cfffe1)

![image](https://github.com/towhee-io/towhee/assets/109071306/abee9347-dfc1-44f7-bb97-d0ed32e2c24b)

### Expected Behavior

pass

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
fixed

**Comment by NicoYuan1986** [comment]
Same: https://towhee.io/prompt/template

openai.error.InvalidRequestError: This model's maximum context length is 4097 tokens. However, your messages resulted in 5379 tokens. Please reduce the length of the messages.

**Comment by junjiejiangjjj** [comment]
Have revised the sample code, please try again

**Comment by NicoYuan1986** [comment]
Fixed.
