### ISSUE TITLE
[Bug]: can't open/read file when filename has Chinese

### ISSUE THREAD

**Issue by wjx-sudo** [towhee-io/towhee#2584]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

when run ：towhee.glob(img_path)
if img_path has Chinese
error： can't open/read file: check file path/integrity

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
try the new interface of Towhee, run success with the Chinese path
https://towhee.io/data-source/glob

**Comment by binbinlv** [comment]
@wjx-sudo 
Is it fixed using the new interface?
