### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by chandrakalagowda** [towhee-io/towhee#2588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I execute the block below from the page https://github.com/towhee-io/examples/blob/main/image/text_image_search/1_build_text_image_search_engine.ipynb
============================
%%time
collection = create_milvus_collection('text_image_search', 512)

def read_csv(csv_path, encoding='utf-8-sig'):
    import csv
    with open(csv_path, 'r', encoding=encoding) as f:
        data = csv.DictReader(f)
        for line in data:
            yield int(line['id']), line['path']

p3 = (
    pipe.input('csv_file')
    .flat_map('csv_file', ('id', 'path'), read_csv)
    .map('path', 'img', ops.image_decode.cv2('rgb'))
    .map('img', 'vec', ops.image_text_embedding.clip(model_name='clip_vit_base_patch16', modality='image', device=0))
    .map('vec', 'vec', lambda x: x / np.linalg.norm(x))
    .map(('id', 'vec'), (), ops.ann_insert.milvus_client(host='127.0.0.1', port='19530', collection_name='text_image_search'))
    .output(tracer=True)
)

p3('reverse_image_search.csv')

profiler_info = p3.profiler()
profiler_info.show()
============================
============================
I get an error message. 

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File <timed exec>:17

TypeError: Pipeline.output() got an unexpected keyword argument 'tracer'

### Expected Behavior

I am trying to reproduce https://github.com/towhee-io/examples/blob/main/image/text_image_search/1_build_text_image_search_engine.ipynb

So the code should run without error.

### Steps To Reproduce

```markdown
I followed the same steps shown in the page https://github.com/towhee-io/examples/blob/main/image/text_image_search/1_build_text_image_search_engine.ipynb
install docker,
install milvus,
and run docker compose up -d

once the milvus services were. up and. running

www.abcom.in@C02XJ0Z1JG5L milvus % docker compose up -d
[+] Building 0.0s (0/0)                                                         
[+] Running 4/4
 ✔ Network milvus               Created                                    0.0s 
 ✔ Container milvus-minio       Started                                    0.6s 
 ✔ Container milvus-etcd        Started                                    0.6s 
 ✔ Container milvus-standalone  Started                                    0.8s 
www.abcom.in@C02XJ0Z1JG5L milvus % jupyter notebook

I work on the jupyter notebook with the code from the github page.
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): v2.30.0
- OS(Ubuntu or CentOS):MAC
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
The profiler function has been moved to the [debug](https://towhee.readthedocs.io/en/latest/debug/usage.html) interface. This code can be modified to run as follows: 

```python
p3 = (
    pipe.input('csv_file')
    .flat_map('csv_file', ('id', 'path'), read_csv)
    .map('path', 'img', ops.image_decode.cv2('rgb'))
    .map('img', 'vec', ops.image_text_embedding.clip(model_name='clip_vit_base_patch16', modality='image', device=0))
    .map('vec', 'vec', lambda x: x / np.linalg.norm(x))
    .map(('id', 'vec'), (), ops.ann_insert.milvus_client(host='127.0.0.1', port='19530', collection_name='text_image_search'))
    .output(tracer=True)
)

p3('reverse_image_search.csv')

profiler_info = p3.profiler()
profiler_info.show()
```

to 
```python
p3 = (
    pipe.input('csv_file')
    .flat_map('csv_file', ('id', 'path'), read_csv)
    .map('path', 'img', ops.image_decode.cv2('rgb'))
    .map('img', 'vec', ops.image_text_embedding.clip(model_name='clip_vit_base_patch16', modality='image', device=0))
    .map('vec', 'vec', lambda x: x / np.linalg.norm(x))
    .map(('id', 'vec'), (), ops.ann_insert.milvus_client(host='127.0.0.1', port='19530', collection_name='text_image_search'))
    .output()
)

p3('reverse_image_search.csv')
```

**Comment by chandrakalagowda** [comment]
yes it worked. Thank you. I have another issue now. Will post it as a new issue.
