### ISSUE TITLE
[Documentation]: Scaling pipeline on millions of data

### ISSUE THREAD

**Issue by mzolfaghari** [towhee-io/towhee#2591]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

I would like to know how can I use towhee to scale data processing on multiple GPUs and speed of the process? Imagine I have millions of data and processing them on one GPU takes weeks! Therefore distributed processing is critical here! Would be great if you share some pointers. Thanksthe 

### Why is this needed?

Document on distributed processing with Towhee!

**Comment by junjiejiangjjj** [comment]
You can create multiple pipelines, each binding to a different GPU.
An example of binding GPUs.: https://towhee.readthedocs.io/en/latest/GPU/GPU.html

**Comment by xiaofan-luan** [comment]
did we ever tried to create a on a 10M data set?

**Comment by xiaofan-luan** [comment]
@junjiejiangjjj

**Comment by junjiejiangjjj** [comment]
Currently there is still no solution considered for large-scale data. Going forward, a solution based on k8s can be considered.

**Comment by xiaofan-luan** [comment]
we should at least test on embedding 10M vectors.
