### ISSUE TITLE
[Documentation]: Can you add a document introduction on how to build Towhee on the company intranet?

### ISSUE THREAD

**Issue by Fakeraway** [towhee-io/towhee#2593]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

Can you add a document introduction on how to build towhee on the company intranet?

### Why is this needed?

The company's intranet is not connected to the Internet, and the required dependencies need to be resolved manually without document guidance.

**Comment by junjiejiangjjj** [comment]
Huggingface offline mode: https://github.com/huggingface/transformers/issues/10379
