### ISSUE TITLE
[Bug]: AttributeError: module 'towhee' has no attribute 'glob'

### ISSUE THREAD

**Issue by junka007** [towhee-io/towhee#2614]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

[root@localhost towhee]# python3
Python 3.8.13 (default, Jul  7 2023, 09:39:03) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import towhee
>>> towhee.glob['path']('./test/lion/n02129165_13728.JPEG') \
...       .image_decode['path', 'img']() \
...       .image_embedding.timm['img', 'vec'](model_name='resnet50') \
...       .select['img', 'vec']() \
...       .show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'towhee' has no attribute 'glob'
>>> towhee.glob['path']('./test/lion/n02129165_13728.JPEG').image_decode['path', 'img']().image_embedding.timm['img', 'vec'](model_name='resnet50').select['img', 'vec']().show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'towhee' has no attribute 'glob'

### Expected Behavior

OK

### Steps To Reproduce

```markdown
[root@localhost towhee]# pip3 show towhee
Name: towhee
Version: 1.1.1
Summary: Towhee is a framework that helps you encode your unstructured data into embeddings.
Home-page: https://github.com/towhee-io/towhee
Author: Towhee Team
Author-email: towhee-team@zilliz.com
License: http://www.apache.org/licenses/LICENSE-2.0
Location: /usr/local/python3/lib/python3.8/site-packages
Requires: numpy, pydantic, requests, tabulate, tenacity, tqdm, twine
Required-by:
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
After towhee 1.0, new interfaces were used, the docs: https://towhee.readthedocs.io/en/latest/pipeline/usage.html#use-towhee-operator

**Comment by junka007** [comment]
TKS
