### ISSUE TITLE
[Bug]: ops.image_embedding.timm  AssertionError

### ISSUE THREAD

**Issue by BetaGo** [towhee-io/towhee#2617]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

If the model used is not trained with images of size 224 x 224, an error will be reported when using `ops.image_embedding.timm` to process images.

## demo code
When using model "vit_base_patch16_224", it works fine,

When using model "vit_base_patch16_384", an error will be reported
```py
from PIL import Image
from urllib.request import urlopen
from towhee import pipe, ops

model_name = "vit_base_patch16_384"   # bad
# model_name = "vit_base_patch16_224" # good

img = Image.open(urlopen(
    'https://huggingface.co/datasets/huggingface/documentation-images/resolve/main/beignets-task-guide.png'
))
img = img.convert('RGB')

p_vit = (
      pipe.input('img')
        .map(
            "img",
            "vec",
            ops.image_embedding.timm(model_name=model_name, device=None),
        )
)

res = p_vit.output('vec')(img)
res.get()
```
### error

```shell
AssertionError: Input image height (224) doesn't match model (384).
```

## possible solution

Through debugging, it should be found that there is a problem with the parameter passing when calling `timm.data.create_transform`. 
When changing `create_transform(**resolve_data_config({}, model=self.model))` on line 112 to `create_transform( **resolve_data_config({}, model=self.model.model))`, everything works fine.

https://towhee.io/image-embedding/timm/src/branch/main/timm_image.py#L112

### Expected Behavior

When I execute the above demo code, there should be no error.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 1.1.1
- OS(Ubuntu or CentOS): Macos13
- CPU/Memory:
- GPU:
- Others:
  - timm version: 0.9.2
```

**Comment by junjiejiangjjj** [comment]
@jaelgu

**Comment by jaelgu** [comment]
Fixed: https://towhee.io/image-embedding/timm/src/branch/main/timm_image.py

**Comment by binbinlv** [comment]
@BetaGo 

Fixed now, could you please have a try?

**Comment by zhfkt** [comment]
I tried and it seems this commit will cause the embedding result change in model `vit_base_patch16_224_in21k`.

```python
conf = AutoConfig.load_config('image-embedding')
conf.model_name = 'vit_base_patch16_224_in21k'
image_embedding_pipeline = AutoPipes.pipeline('image-embedding', conf)


def embedding_ops_func(img):
    return image_embedding_pipeline(img).get()

# preload
def preload_model():
    return embedding_ops_func(sample_jpg_path)

print(preload_model())

```

Use any image for `sample_jpg_path` and you will see the difference.  After I revert `self.model.model` to `self.model`, it will keep the original embedding result.

I believe this commit is a little dangerous and will break some online services.
