### ISSUE TITLE
[Bug]: "Error Code 1314" when trying to download a model from the hub

### ISSUE THREAD

**Issue by ssuwelack** [towhee-io/towhee#2620]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I used the following pipeline to compute an image embedding (from the tutorial):
p = (
    pipe.input('path')
        .map('path', 'img', ops.image_decode())
        .map('img', 'vec', ops.image_embedding.timm(model_name='resnet50'))
        .output('img', 'vec')
    )

On my windows machine, I get the following error when executing the pipeline:
"Error Code 1314 - A required privilege is not held by the client"

This seems to be caused when towhee is trying to set a symlink:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\pathlib.py", line 1255, in symlink_to
    self._accessor.symlink(target, self, target_is_directory)

### Expected Behavior

The pipeline should be executed without errors. It works on my Ubuntu machine.

### Steps To Reproduce

```markdown
1. In Windows 10
2. Execute tutorial for image embeddings
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 1.1.1
- OS(Ubuntu or CentOS): Windows
- CPU/Memory: 32GB
- GPU: 
- Others:
```

**Comment by junjiejiangjjj** [comment]
Can the ~/.towhee directory write files normally?

**Comment by ssuwelack** [comment]
Thanks for the fast reply. Yes, I can write to the towhee directory. The bug still happens if I choose a different TOWHEE_HOME

**Comment by junjiejiangjjj** [comment]
It may be that the Window has disabled the symlink: https://stackoverflow.com/questions/32877260/privlege-error-trying-to-create-symlink-using-python-on-windows-10
