### ISSUE TITLE
[Enhancement]:  ops.image_text_embedding.clip use local model path

### ISSUE THREAD

**Issue by MrRace** [towhee-io/towhee#2628]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

`ops.image_text_embedding.clip` need to support  local model  path. Maybe like `checkpoint_path`  in https://towhee.io/sentence-embedding/transformers

### Why is this needed?

I have downloaded  many  models in a public directory. for example I download `clip-vit-base-patch32` from  `https://huggingface.co/openai/clip-vit-base-patch32` and put the model in `/home/model_zoo/CLIP/`. 
I try the official example : [text_image_search/1_build_text_image_search_engine](https://github.com/towhee-io/examples/blob/afbd207d9e65798d913b8f4eff8ba355000ada84/image/text_image_search/1_build_text_image_search_engine.ipynb). Therefore I want to modify  `ops.image_text_embedding.clip(model_name='clip_vit_base_patch16', modality='image')` to `ops.image_text_embedding.clip(model_name='/home/model_zoo/CLIP/clip-vit-base-patch32', modality='image')` which use local model path, However it fails

**Comment by junjiejiangjjj** [comment]
https://towhee.io/image-text-embedding/clip/src/branch/main/clip.py#L95 
Clip now supports checkpoint_path, make sure the locally cached clip code is the latest version.

**Comment by MrRace** [comment]
> https://towhee.io/image-text-embedding/clip/src/branch/main/clip.py#L95 Clip now supports checkpoint_path, make sure the locally cached clip code is the latest version.

I do not why such different：

![image](https://github.com/towhee-io/towhee/assets/10300313/2fea8727-0ca5-4ac7-b78c-bb23381ff84c)
I also install the with:
```
pip3 install -U towhee towhee.models
```
What do you mean by `locally cached clip code`？I find clip from `/usr/local/lib/python3.8/dist-packages/towhee/models/clip/clip.py`

**Comment by junjiejiangjjj** [comment]
@wxywb

**Comment by wxywb** [comment]
**checkpoint_path** should be your custom trained weights, you also need to specify the model_name to define the model architecture which be compatible with your weights. you can use the model name **clip_vit_base_patch32**, and **checkpoint_path** should be your weights file path.

**Comment by MrRace** [comment]
> **checkpoint_path** should be your custom trained weights, you also need to specify the model_name to define the model architecture which be compatible with your weights. you can use the model name **clip_vit_base_patch32**, and **checkpoint_path** should be your weights file path.

from https://towhee.io/image-text-embedding/clip/src/branch/main/clip.py#L157
we can see the `model_name` can not beyond the four names. When use `checkpoint_path` it seems does not need use  `model_name` anymore.

**Comment by wxywb** [comment]
I realized the problem, because the operator's interface initially designed with non-huggingface operators. And we didn't consider the huggingface style model-loading usage. We will make this huggingface style model-loading in soon, thanks for your advice.

**Comment by jaelgu** [comment]
If the local model is a directory containing `config.json` and weights by [saved_pretrained()](https://huggingface.co/docs/transformers/v4.31.0/en/main_classes/model#transformers.PreTrainedModel.save_pretrained), you can just pass the path to local model directory as `model_name`.
