### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by qweasdzxctt** [towhee-io/towhee#2629]
按照官网的方式去操作，然后这段代码
p_display = p_embed.output('img_path', 'img', 'vec')
DataCollection(p_display('./test/goldfish/*.JPEG')).show()
报错RuntimeError: Load operator failed，有什么解决办法吗

**Comment by junjiejiangjjj** [comment]
Could you show the full code? Are there any other more detailed logs?

**Comment by qweasdzxctt** [comment]
def create_milvus_collection(collection_name, dim):
    if utility.has_collection(collection_name):
        utility.drop_collection(collection_name)

    fields = [
        FieldSchema(name='path', dtype=DataType.VARCHAR, description='path to image', max_length=500,
                    is_primary=True, auto_id=False),
        FieldSchema(name='embedding', dtype=DataType.FLOAT_VECTOR, description='image embedding vectors', dim=dim)
    ]
    schema = CollectionSchema(fields=fields, description='reverse image search')
    collection = Collection(name=collection_name, schema=schema)

    index_params = {
        'metric_type': METRIC_TYPE,
        'index_type': INDEX_TYPE,
        'params': {"nlist": 2048}
    }
    collection.create_index(field_name='embedding', index_params=index_params)
    return collection

connections.connect(host=HOST, port=PORT)


# Create collection
collection = create_milvus_collection(COLLECTION_NAME, DIM)

p_embed = (
    pipe.input('src')
        .flat_map('src', 'img_path', load_image)
        .map('img_path', 'img', ops.image_decode())
        .map('img', 'vec', ops.image_embedding.timm(model_name=MODEL, device=DEVICE))
)
p_display = p_embed.output('img_path', 'img', 'vec')
DataCollection(p_display('./test/goldfish/*.JPEG')).show()
报错RuntimeError: Load operator failed

**Comment by junjiejiangjjj** [comment]
The definition of load_image is not seen, it should be like this in the example：
![image](https://github.com/towhee-io/towhee/assets/14136703/7df78bc8-86e1-426d-b245-52407eb820dd)

**Comment by qweasdzxctt** [comment]
def load_image(x):
    if x.endswith('csv'):
        with open(x) as f:
            reader = csv.reader(f)
            next(reader)
            for item in reader:
                yield item[1]
    else:
        for item in glob(x):
            yield item


# Embedding pipeline
p_embed = (
    pipe.input('src')
        .flat_map('src', 'img_path', load_image)
        .map('img_path', 'img', ops.image_decode())
        .map('img', 'vec', ops.image_embedding.timm(model_name=MODEL, device=DEVICE))
)

p_display = p_embed.output('img_path', 'img', 'vec')
DataCollection(p_display('./test/goldfish/*.JPEG')).show()
一样的报错RuntimeError: Load operator failed

**Comment by junjiejiangjjj** [comment]
![image](https://github.com/towhee-io/towhee/assets/14136703/9d2c2938-6780-4658-b41e-e931b597708c)
What are the actual values set for these two variables?

**Comment by junjiejiangjjj** [comment]
Try this code, it runs normally on my local machine."
```python
from towhee import ops, pipe, DataCollection
from glob import glob


# Load image path
def load_image(x):
    if x.endswith('csv'):
        with open(x) as f:
            reader = csv.reader(f)
            next(reader)
            for item in reader:
                yield item[1]
    else:
        for item in glob(x):
            yield item

# Embedding pipeline
p_embed = (
    pipe.input('src')
        .flat_map('src', 'img_path', load_image)
        .map('img_path', 'img', ops.image_decode())
        .map('img', 'vec', ops.image_embedding.timm(model_name='resnet50'))
)

p_display = p_embed.output('img_path', 'img', 'vec')
DataCollection(p_display('./test/goldfish/*.JPEG')).show()
```

**Comment by qweasdzxctt** [comment]
MODEL = 'resnet50'
DEVICE = None
