### ISSUE TITLE
[Bug]: towhee build docker image error with a local private BERT model

### ISSUE THREAD

**Issue by drow931** [towhee-io/towhee#2637]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When executing towhee.build_docker_image, the op contains a local private BERT model, and the following error occurs:
factory.py-factory:118 - ERROR: Loading operator with error: yyyy/chinese-bert-wwm-ext is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'

Which level directory in the docker should this model be copied to?

<img width="1194" alt="image" src="https://github.com/towhee-io/towhee/assets/11514434/465791a4-7136-4695-8fb0-65959f3c168c">

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS): centos7
- CPU/Memory:
- GPU: T4
- Others: cuda 11.7
```

**Comment by junjiejiangjjj** [comment]
Use `towhee.build_pipeline_model` to create Triton models without using Docker.  wiki: https://towhee.readthedocs.io/en/latest/triton/triton.html

And then build a docker image to run the models,  need to install some deps 
Some example dockerfiles: https://github.com/towhee-io/towhee/tree/main/towhee/serve/triton/dockerfiles

**Comment by drow931** [comment]
nice
