### ISSUE TITLE
How to use zilliz cloud url and token

### ISSUE THREAD

**Issue by bhuvneshsaini** [towhee-io/towhee#2638]
How to use zilliz cloud uri and token in 
ops.ann_insert.milvus_client(host, port, collection_name, user= None, password=None, collection_schema=None, index_params=None)

**Comment by Chiiizzzy** [comment]
Hi @bhuvneshsaini , try `towhee.ops.ann_insert.milvus_client(collection_name='test_collection', uri=<your-uri>, token=<your-token>)`. Please clear your local ann-insert namespce cache  in `.towhee` directory and re-download the operator from hub.

**Comment by bhuvneshsaini** [comment]
How to clear from cache through programming as i am using this command in pipeline.

**Comment by junjiejiangjjj** [comment]
https://towhee.readthedocs.io/en/latest/operator/usage.html 
Use the `latest()` interface, which will update the operator to the latest.
![image](https://github.com/towhee-io/towhee/assets/14136703/5a715570-c1e3-4844-9d9d-e63ee47fd7e4)
