### ISSUE TITLE
[Bug]: interface hangs when embedding with not existed video

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#264]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

did not return

```
>>> video_vec = p("/Users/binbin/Towhee_projects/binbin1.mp4")
OpenCV: Couldn't read video stream from file "/Users/binbin/Towhee_projects/binbin1.mp4"

>>> video_vec = p("/Users/binbin/Towhee_projects/")
hangs here

```

### Expected Behavior

Report error just like image embedding

### Steps To Reproduce

```markdown
1 setup env and install towhee:

 python
python3 -m venv towhee-test-env
pip install -U pip
pip install towhee
``` 

2  into python env: python3:
video_path with no existed video

``` python
from towhee import pipeline
p = pipeline('towhee/video_embedding_resnet50')
video_vec = p(video_path)
```
```


### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.2
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by binbinlv** [comment]
StStill exists in 0.2.2 (release target for 0.3)

**Comment by fzliu** [comment]
We are deprecating the existing video embedding pipeline; a newer and much improved version will be released later down the road.
