### ISSUE TITLE
[Bug]: Run example reverse_image_search met a ModuleNotFoundError

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2644]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Run example reverse_image_search met a ModuleNotFoundError.
https://github.com/towhee-io/examples/blob/main/image/reverse_image_search/2_deep_dive_image_search.ipynb

![image](https://github.com/towhee-io/towhee/assets/109071306/6b899c81-0987-4621-8d1b-22f79dd52052)

![image](https://github.com/towhee-io/towhee/assets/109071306/1e671fdd-3fdc-4e8b-9cc1-e7d576d01648)

### Expected Behavior

pass

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):1.1.1
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by shiyu22** [comment]
Added the package in [op](https://towhee.io/object-detection/yolov5/src/branch/main/requirements.txt#L8), you can remove the floder `~/.towhee/operators/object-detection/yolov5` and try again.

**Comment by NicoYuan1986** [comment]
same: https://github.com/towhee-io/examples/blob/main/image/visualization/under_the_hood_anns_index.ipynb

![image](https://github.com/towhee-io/towhee/assets/109071306/e4f7b6f7-f608-4d6f-8362-8b1f1f7bd7e7)

**Comment by jaelgu** [comment]
> same: https://github.com/towhee-io/examples/blob/main/image/visualization/under_the_hood_anns_index.ipynb
> 
> ![image](https://user-images.githubusercontent.com/109071306/256772177-e4f7b6f7-f608-4d6f-8362-8b1f1f7bd7e7.png)

Should be fixed too with latest yolo operator. Can you check again? @NicoYuan1986

**Comment by NicoYuan1986** [comment]
Verify fixed.
