### ISSUE TITLE
[Bug]: molecular search failed reporting a metric type not match error

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2645]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

molecular search failed reporting a metric type not match error.

https://github.com/towhee-io/examples/blob/main/medical/molecular_search/2_deep_dive_molecular_search.ipynb

![image](https://github.com/towhee-io/towhee/assets/109071306/796ab30b-328e-4c62-9ad0-5d7a010a4f58)

![image](https://github.com/towhee-io/towhee/assets/109071306/f22528b4-0934-49c2-8e6a-336c39306cb2)

### Expected Behavior

pass

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):1.1.1
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
binary only supports hamming and jaccard at present( delete TANIMOTO/SUPERSTRUCTURE/SUBSTRUCTURE) .  @shiyu22 
But it may change in the future.

**Comment by jaelgu** [comment]
I will add requirement for milvus version.

**Comment by jaelgu** [comment]
TANIMOTO/SUPERSTRUCTURE/SUBSTRUCTURE is still in the latest release version but not in the latest Milvus.

**Comment by NicoYuan1986** [comment]
Fixed.
