### ISSUE TITLE
[Bug]: video_deduplication_at_segment_level run failed with an attribute error

### ISSUE THREAD

**Issue by NicoYuan1986** [towhee-io/towhee#2646]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://github.com/towhee-io/examples/blob/main/video/video_copy_detection/segment_level/video_deduplication_at_segment_level.ipynb

![image](https://github.com/towhee-io/towhee/assets/109071306/9275cd71-aa9c-4b08-9fe7-107e7170e280)

### Expected Behavior

pass

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):1.1.1
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by NicoYuan1986** [comment]
same error:
https://github.com/towhee-io/examples/blob/main/video/video_copy_detection/video_level/video_deduplication_at_video_level.ipynb

![image](https://github.com/towhee-io/towhee/assets/109071306/1b14dfc8-d1b9-404e-9a86-585609e399d3)
![image](https://github.com/towhee-io/towhee/assets/109071306/c695da97-0f5b-43f1-88d8-684ee6703a13)

**Comment by jaelgu** [comment]
@zc277584121 Can you take a look at this issue?

**Comment by junjiejiangjjj** [comment]
https://github.com/junjiejiangjjj/examples/blob/3e61b1b5f4f4181a771ef3b4ae939130c4786af1/video/text_video_retrieval/1_text_video_retrieval_engine.ipynb
You can refer to the implementation here for reference

**Comment by jaelgu** [comment]
@NicoYuan1986 Fixed by https://github.com/towhee-io/examples/pull/222. Please retry.

**Comment by NicoYuan1986** [comment]
verify Fixed.
