### ISSUE TITLE
[Feature]: 添加java接口

### ISSUE THREAD

**Issue by wwy2509660419** [towhee-io/towhee#2649]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

由于目前我是java开发，在使用milvus向量数据库进行人脸检索，我自行训练的模型向量数据在milvus中检索识别率略低，我想接触一下Towhee的图像Embedding流水线进行向量生成存入milvus库中进行检索

**Comment by junjiejiangjjj** [comment]
You can build an http service using towhee, which can then be remotely accessed from Java.
