### ISSUE TITLE
[Feature]: Allow pipeline to drop output node

### ISSUE THREAD

**Issue by jaelgu** [towhee-io/towhee#2650]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

Sometimes we need to combine pipelines, however all auto pipelines are RuntimePipeline, which is not allowed in concat.
Can we allow a runtime pipeline to drop output node, which makes it a regular pipeline?

**Comment by junjiejiangjjj** [comment]
https://towhee.readthedocs.io/en/latest/pipeline/usage.html#pipeline-act-as-node  use it to combine pipelines

**Comment by Chiiizzzy** [comment]
Currently can be solved by pipeline-as-operator, will support disabling pre-load in the future to prevent duplicated loading of model in the future.
