### ISSUE TITLE
[Bug]: TypeError: constr() got an unexpected keyword argument 'regex'

### ISSUE THREAD

**Issue by pyftxdy** [towhee-io/towhee#2654]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In my project I have to use pydantic==2.1.*
But towhee needs to use pydantic<2 how can I solve it

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
The changes in pydantic are too substantial, we have not yet adapted to them.
