### ISSUE TITLE
[Bug]: image color of DataCollection output was wrong.

### ISSUE THREAD

**Issue by no251-1** [towhee-io/towhee#2656]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The color of image was wrong. 

Here is the code.

```python
p_display = p_embed.output('img_path', 'img', 'vec')
DataCollection(p_display('./test/OM/*.JPG')).show()
```
![image](https://github.com/towhee-io/towhee/assets/36976375/4d103df9-9621-4e38-845d-86e20e62d12d)

here is the original image.
![images_74_ 219, 1596, 1203, 2529 _0](https://github.com/towhee-io/towhee/assets/36976375/4ff8187c-d94b-4c23-a7b6-51f455908f76)

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): V1.1.0
- OS(Ubuntu or CentOS): Windows
- CPU/Memory: i5/32GB
- GPU: RX640
- Others:
```

### Anything else?

I don't know why. Maybe it is related with my computer or CV2.

**Comment by no251-1** [comment]
> 

thanks. It works when i add 'rgb' into `ops.image_decode('rgb')`.
```python
p_embed = (
    pipe.input('src')
        .flat_map('src', 'img_path', load_image)
        .map('img_path', 'img', ops.image_decode('rgb'))
        .map('img', 'vec', ops.image_embedding.timm(model_name=MODEL, device=DEVICE))
)
```

but for the code below, i still don't know how to solve it.
```python
p_search_img = (
    p_search_pre.map('pred', 'pred images', read_images)
                .output('img', 'pred images')
)
DataCollection(p_search_img('test/goldfish/*.JPEG')).show()
```

**Comment by junjiejiangjjj** [comment]
How do you define read_images, the rgb configuration should be set here.
