### ISSUE TITLE
[Feature]: AWS Lambda support | pre download model or specify the path where the models will be downloaded

### ISSUE THREAD

**Issue by BenSpex** [towhee-io/towhee#2657]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

I want to integrate a Towhee Pipeline into a lambda function. 

However towhee is downloading the ops and models required on the first run to `~/.towhee` a folder that can not be created during a lambda call. 

### Describe the solution you'd like.

Pre download the ops needed and store them with the python package. 

### Describe an alternate solution.

Specify the download folder eg. /tmp/.towhee

**Comment by junjiejiangjjj** [comment]
You can adjust the cache directory of towhee by setting the TOWHEE_HOME environment variable.

**Comment by BenSpex** [comment]
@junjiejiangjjj 
This is not really a great solution for this problem. 
It works kind of, but it actually then also installs additional dependencies via pip on the fly, which then fails, as again pip is not allowed to write. 

And it then fails with module OpenAI not found. 

![image](https://github.com/towhee-io/towhee/assets/52712273/54c93ca7-d5a3-4315-a8e8-facd6a8286a3)


It would be great to change the logic of the additional ops and modules, and have the option to do something like 
`pip install towhee[openai, milvus]` etc.

**Comment by BenSpex** [comment]
@junjiejiangjjj 
Quick Update
Even with OpenAI installed before the call of the code, the ops still goes ahead and tries to install it again: 

![image](https://github.com/towhee-io/towhee/assets/52712273/db9f6bd7-52c6-47a1-b364-1d95e4e7b940)
 
 Which to no surprise fails. 
 I really hope that there is a different path forward to be able to use towhee within Lambda calls

**Comment by junjiejiangjjj** [comment]
One way is to change pip's installation path through the PIP_TARGET environment variable and set PYTHONPATH when starting python.

**Comment by junjiejiangjjj** [comment]
Or run towhee locally first, then copy the files under ~/.towhee to the actual running environment, and make sure the relevant dependencies are installed properly.
