### ISSUE TITLE
[Bug]: ValidationError: 101 validation errors for PointStruct vector -> 0   value is not a valid float (type=type_error.float)

### ISSUE THREAD

**Issue by zeynepiskndr** [towhee-io/towhee#2661]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```
vectors = []
for image in images:
     img = cv2.imread(f"{saved_images_path}/{image}")
     image_embedding = img_encoder(img)
     vectors.append(image_embedding)
```

this way I create my vectors and throw them into the vectors array. then I reformat it to be float64.

`np_vectors = np.array(vectors,dtype="float64")
`
Finally, I export these vectors to qrant, but I get an invalid float error.

```
import numpy as np
from qdrant_client.models import PointStruct

qdrant_client.upsert(
     collection_name=my_collection,
     points=[
         PointStruct(
             id=i,
             vector=np_vectors.tolist(),
             payload=payload
         )
         for i in index
     ]
)
```

### Expected Behavior

The vectors I created are working without error by qdrant.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):last version
- OS(Ubuntu or CentOS):Google Cloud vertexAI
- CPU/Memory:8 vCPUs, 52 GB RAM
- GPU:No
- Others:
```

**Comment by junjiejiangjjj** [comment]
Check if np_vectors matches expectations.

**Comment by zeynepiskndr** [comment]
@junjiejiangjjj Thank you very much for your answer, but I don't understand what you mean by expectations.
if you are talking about np_vectors type I checked and it is fload64.

**Comment by junjiejiangjjj** [comment]
I don't know about qdrant, you should ask over there.

**Comment by zeynepiskndr** [comment]
I am grateful @junjiejiangjjj
