### ISSUE TITLE
[Bug]: How to actively release video memory

### ISSUE THREAD

**Issue by boatingMen** [towhee-io/towhee#2671]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When the text search function is recycled, the video memory keeps rising during the process of video turning, and I want to actively release the video memory

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
What version of towhee is it, and can you also paste the relevant code?
