### ISSUE TITLE
Embedding模型加载失败

### ISSUE THREAD

**Issue by panxiaohuan9** [towhee-io/towhee#2672]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

linux系统中将模型修改为本地下载好的模型，模型加载失败，同样的方法在window系统中可以加载成功
出错代码：
 self.sentence_embedding_pipe = (
            pipe.input('sentence')
                .map('sentence', 'embedding', ops.sentence_embedding.sbert(model_name='../model/all-MiniLM-L12-v2'))
                .map('embedding', 'embedding', ops.towhee.np_normalize())
                .output('embedding')
            )

错误信息：
RuntimeError: Node-sentence-embedding/sbert-0 runs failed, error msg: Create sentence-embedding/sbert-0 operator sentence-embedding/sbert:main with args None and kws {'model_name': '../model/all-MiniLM-L12-v2'} failed, err: Load operator failed, Traceback (most recent call last):
  File "/soft/anaconda3/envs/qa/lib/python3.8/site-packages/towhee/runtime/nodes/node.py", line 88, in initialize
    self._op = self._op_pool.acquire_op(
  File "/soft/anaconda3/envs/qa/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 106, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag, latest)
  File "/soft/anaconda3/envs/qa/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 158, in load_operator
    raise RuntimeError('Load operator failed')
RuntimeError: Load operator failed

### Steps To Reproduce

```markdown
linux 
python3.8
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
Try running these codes to see if they work. 
```python
from sentence_transformers import SentenceTransformer
model  = SentenceTransformer(model_name_or_path='../model/all-MiniLM-L12-v2')
```

**Comment by jaelgu** [comment]
@panxiaohuan9 hi I've just tried in linux and it works well:
<img width="887" alt="image" src="https://github.com/towhee-io/towhee/assets/86251631/9fa09eaf-5d75-4ea3-9b95-9b0144d4404b">

Here are some suggestions:
1. Make sure the model path `../model/all-MiniLM-L12-v2` is valid in your linux.
2. Check your Towhee version in linux
3. Force op re-download and try again: `ops.sentence_embedding.sbert(model_name='../model/all-MiniLM-L12-v2').latest()`

**Comment by panxiaohuan9** [comment]
towhee 版本  1.1.1

**Comment by panxiaohuan9** [comment]
sentence_transformers 可以运行成功，towhee运行失败
from sentence_transformers import SentenceTransformer
# model  = SentenceTransformer(model_name_or_path='dpr-ctx_encoder-single-nq-base')
model = SentenceTransformer('all-MiniLM-L12-v2')
# model = SentenceTransformer('ctx_encoder-single-nq-base')
passages = [
    "London [SEP] London is the capital and largest city of England and the United Kingdom.",
    "Paris [SEP] Paris is the capital and most populous city of France.",
    "Berlin [SEP] Berlin is the capital and largest city of Germany by both area and population."
]
passage_embeddings = model.encode(passages)
print(passage_embeddings)
print(model)

[[ 8.4761180e-02  2.3563143e-02  8.8695399e-02 ...  4.8111290e-02
  -7.1252971e-03  4.8900926e-03]
 [ 6.1530240e-02  3.4760007e-05 -2.7074054e-02 ...  5.6621548e-02
   7.3537114e-03 -9.7967293e-03]
 [ 7.7983916e-02  9.1143958e-02 -5.6123774e-02 ...  7.0890456e-02
  -7.6465689e-02  5.4667187e-03]]
SentenceTransformer(
  (0): Transformer({'max_seq_length': 128, 'do_lower_case': False}) with Transformer model: BertModel 
  (1): Pooling({'word_embedding_dimension': 384, 'pooling_mode_cls_token': False, 'pooling_mode_mean_tokens': True, 'pooling_mode_max_tokens': False, 'pooling_mode_mean_sqrt_len_tokens': False})
  (2): Normalize()
)
towhee 运行失败
from towhee import pipe, ops
p = (
    pipe.input('question')
        .map('question', 'vec', ops.sentence_embedding.sbert(model_name='all-MiniLM-L12-v2'))
        # .map('question', 'vec', ops.text_embedding.dpr(model_name='facebook/dpr-ctx_encoder-single-nq-base'))
        .output())  
print(p('how are you, i am fine, thanks.'))
出错信息
2023-11-13 13:05:36,907 - 140345618888512 - hub_utils.py-hub_utils:443 - ERROR: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')), Traceback (most recent call last):
。。。。。。
RuntimeError: Node-sentence-embedding/sbert-0 runs failed, error msg: Create sentence-embedding/sbert-0 operator sentence-embedding/sbert:main with args None and kws {'model_name': 'all-MiniLM-L12-v2'} failed, err: Load operator failed, Traceback (most recent call last):
  File "/soft/anaconda3/envs/qa/lib/python3.8/site-packages/towhee/runtime/nodes/node.py", line 88, in initialize
    self._op = self._op_pool.acquire_op(
  File "/soft/anaconda3/envs/qa/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_pool.py", line 106, in acquire_op
    op = self._op_loader.load_operator(hub_op_id, op_args, op_kws, tag, latest)
  File "/soft/anaconda3/envs/qa/lib/python3.8/site-packages/towhee/runtime/operator_manager/operator_loader.py", line 158, in load_operator
    raise RuntimeError('Load operator failed')
RuntimeError: Load operator failed

**Comment by panxiaohuan9** [comment]
![678973F7-119A-4c0a-BC18-A8898A8DF719](https://github.com/towhee-io/towhee/assets/51013515/a15c4b8e-46e1-4ab5-9284-b49f64bc3e49)

**Comment by junjiejiangjjj** [comment]
It seems to be a network problem.   Setting the environment variable TRANSFORMERS_OFFLINE=1 to use huggingface offline mode.

**Comment by panxiaohuan9** [comment]
> It seems to be a network problem. Setting the environment variable TRANSFORMERS_OFFLINE=1 to use huggingface offline mode.

linux系统这个是在哪设置？

**Comment by panxiaohuan9** [comment]
> It seems to be a network problem. Setting the environment variable TRANSFORMERS_OFFLINE=1 to use huggingface offline mode.

![image](https://github.com/towhee-io/towhee/assets/51013515/12619c7e-0fdb-4295-a0ed-c599f35785b3)
![image](https://github.com/towhee-io/towhee/assets/51013515/39dc651a-ae92-4170-9a1a-8716281f8670)

**Comment by junjiejiangjjj** [comment]
The model_name parameter specifies the path to the locally downloaded model.

**Comment by panxiaohuan9** [comment]
是本地模型路径
![image](https://github.com/towhee-io/towhee/assets/51013515/c70879b4-aacc-4662-b7aa-2cc693fe830d)

**Comment by jaelgu** [comment]
Do you have sbert folder under `~/.towhee/operators/sentence-embedding`?

**Comment by panxiaohuan9** [comment]
没有找到，这个模型必须放到towhee/operators/这个路径吗？
![image](https://github.com/towhee-io/towhee/assets/51013515/edf83f47-c7d6-49d0-90ed-67c0ecf8ff51)

**Comment by jaelgu** [comment]
> 没有找到，这个模型必须放到towhee/operators/这个路径吗？ ![image](https://user-images.githubusercontent.com/51013515/282649605-edf83f47-c7d6-49d0-90ed-67c0ecf8ff51.png)

No, you've checked the incorrect location. `~/.towhee`, which is usually under the user's home directory, is the towhee cache where operators are saved. An operator (e.g. ops.sentence_embedding.sbert) will be downloaded the first time you run it.

**Comment by panxiaohuan9** [comment]
没有这个文件.towhee，使用ops方式，我在这个服务器上从来就没有下载模型成功过，都是网络错误
