### ISSUE TITLE
[Bug]: ImportError: cannot import name 'AutoPipes' from partially initialized module 'towhee' (most likely due to a circular import)

### ISSUE THREAD

**Issue by mechigonft** [towhee-io/towhee#2685]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

ImportError: cannot import name 'AutoPipes' from partially initialized module 'towhee' (most likely due to a circular import) 

### Expected Behavior

ImportError: cannot import name 'AutoPipes' from partially initialized module 'towhee' (most likely due to a circular import) 

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
Ensure there is no 'towhee.py' file in your working directory.

**Comment by mechigonft** [comment]
thanks
