### ISSUE TITLE
[Enhancement]: HTTP API should support posting video / image files to compute embeddings and other operations.

### ISSUE THREAD

**Issue by fishfree** [towhee-io/towhee#2691]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

https://towhee.readthedocs.io/en/main/serving/api.html can only support posting texts.

### Why is this needed?

Towhee is famours for its multimodalities.

**Comment by junjiejiangjjj** [comment]
You can use BYTES io to post image/video: https://towhee.readthedocs.io/en/main/serving/api.html#towhee.serve.io.BYTES
