### ISSUE TITLE
[Bug]: When building the triton backend, using custom operators may result in errors

### ISSUE THREAD

**Issue by bug400400** [towhee-io/towhee#2693]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

@register(name='embedding')
class Embedding(NNOperator):
    def __init__(self):

    def __call__(self, object, type, model):
        return vec

embedding_pipe = (
    pipe.input('object')
        .map('object', 'vec', ops.embedding())
        .output('vec')
)

towhee.build_docker_image(
    dc_pipeline=embedding_pipe,
    image_name='triton_embedding:v1.0',
    cuda_version='11.7',
    format_priority=['onnx'],
    parallelism=4,
    inference_server='triton'
)

but it will go to the hub to download the operator
![image](https://github.com/towhee-io/towhee/assets/39868140/69ef9120-3013-48c4-91f0-71366fc55388)

### Expected Behavior

build success

### Steps To Reproduce

```markdown
@register(name='embedding')
class Embedding(NNOperator):
    def __init__(self):
      ####
    def __call__(self, object, type, model):
        ####
        return vec

embedding_pipe = (
    pipe.input('object')
        .map('object', 'vec', ops.embedding())
        .output('vec')
)

towhee.build_docker_image(
    dc_pipeline=embedding_pipe,
    image_name='triton_embedding:v1.0',
    cuda_version='11.7',
    format_priority=['onnx'],
    parallelism=4,
    inference_server='triton'
)

but it will go to the hub to download the operator
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS): Ubuntu 
- CPU/Memory: CPU
- GPU:
- Others:
```

**Comment by bug400400** [comment]
i find ，while build_docker_image，REGISTRY: Dict[str, Any] ，is null。

**Comment by junjiejiangjjj** [comment]
Only supports hub operators and lambda function when using triton backend

**Comment by bug400400** [comment]
Can this feature be added？I think this feature is very common in projects

**Comment by bug400400** [comment]
我找到了临时规避的方案，需要在/usr/local/bin/triton_builder和model.py文件中加入@register的代码

**Comment by bug400400** [comment]
> Only supports hub operators and lambda function when using triton backend

Can this feature be added？I think this feature is very common in projects.
