### ISSUE TITLE
cannot import name 'pipe' from partially initialized module 'towhee' (most likely due to a circular import)

### ISSUE THREAD

**Issue by zyc1128** [towhee-io/towhee#2695]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

tietle

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jaelgu** [comment]
@zyc1128 Can you share your code to help us reproduce and which towhee version do you use?

**Comment by zyc1128** [comment]
> @zyc1128 Can you share your code to help us reproduce and which towhee version do you use?
I have tried a lot of versions from 0.5.0 to 1.1.3 .When I run "from towhee import pipe" this four-word-code,there is an importError: cannot import name 'pipe' from partially initialized module 'towhee' (most likely due to a circular import).Maybe I am weak in Python,but that is too weired.Only four words.

**Comment by zyc1128** [comment]
> @zyc1128 Can you share your code to help us reproduce and which towhee version do you use?

My python version is 3.9.8 and  I want to use towhee to generate embeddings of images and search with Milvus.

**Comment by junjiejiangjjj** [comment]
Make sure there is no towhee.py in your workspace.

**Comment by zhaoyuchen1128** [comment]
> Make sure there is no towhee.py in your workspace.

Thanks,but where to set  variables such as downloading path?The doc is not clear.

**Comment by junjiejiangjjj** [comment]
> > Make sure there is no towhee.py in your workspace.
> 
> Thanks,but where to set variables such as downloading path?The doc is not clear.

Use the environment variable TOWHEE_HOME to change the download path

**Comment by zyc1128** [comment]
> > > Make sure there is no towhee.py in your workspace.
> > 
> > 
> > Thanks,but where to set variables such as downloading path?The doc is not clear.
> 
> Use the environment variable TOWHEE_HOME to change the download path

Is there any doc that describes these variables?And I have reviewed the issues about how to config the local models,still confused.

**Comment by zyc1128** [comment]
> > > Make sure there is no towhee.py in your workspace.
> > 
> > 
> > Thanks,but where to set variables such as downloading path?The doc is not clear.
> 
> Use the environment variable TOWHEE_HOME to change the download path

I  can not get access to huggingface and is there any way to run models from anything like Ollama or local models downloaded from modelscope?

**Comment by junjiejiangjjj** [comment]
Only supports models on huggingface
