### ISSUE TITLE
[Bug]: image_embedding is not define

### ISSUE THREAD

**Issue by Nicksxs** [towhee-io/towhee#2697]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

```python
from towhee import AutoPipes, AutoConfig

# set MilvusInsertConfig for the built-in insert_milvus pipeline
insert_conf = AutoConfig.load_config('insert_milvus')
insert_conf.collection_name = 'text_image_search'

insert_pipe = AutoPipes.pipeline('insert_milvus', insert_conf)

# generate embedding
embedding = image_embedding('./test1.png').get()[0]

# insert text and embedding into Milvus
insert_pipe(['./test1.png', embedding])
```

notice 
    embedding = image_embedding('./test.jpg').get()[0]
                ^^^^^^^^^^^^^^^
NameError: name 'image_embedding' is not defined

### Expected Behavior

will insert image vector to milvus

### Steps To Reproduce

```markdown
1. just run code above
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 1.1.3
- OS(Ubuntu or CentOS): MacOS 14.3
- CPU/Memory: Apple M3 Pro
- GPU: Apple M3 Pro
- Others:
- python version: 3.12.1
```

**Comment by junjiejiangjjj** [comment]
Please take a look at the documentation   https://towhee.readthedocs.io/en/latest/user_guide/10-minutes-to-towhee.html

**Comment by Nicksxs** [comment]
> Please take a look at the documentation https://towhee.readthedocs.io/en/latest/user_guide/10-minutes-to-towhee.html

https://towhee.io/tasks/detail/pipeline/text-image-search

**Comment by junjiejiangjjj** [comment]
image_pipe  -> image_embedding

<img width="442" alt="image" src="https://github.com/user-attachments/assets/b5660da9-7675-4a04-9b4a-bbb08f2fbd5f">
