### ISSUE TITLE
If I use moganet to train a model, and then use the model for feature extraction and image retrieval, how should I apply this framework?

### ISSUE THREAD

**Issue by watertianyi** [towhee-io/towhee#2699]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

If I use moganet to train a model, and then use the model for feature extraction and image retrieval, how should I apply this framework?

### Describe the solution you'd like.

If I use moganet to train a model, and then use the model for feature extraction and image retrieval, how should I apply this framework?

### Describe an alternate solution.

If I use moganet to train a model, and then use the model for feature extraction and image retrieval, how should I apply this framework?

### Anything else? (Additional Context)

If I use moganet to train a model, and then use the model for feature extraction and image retrieval, how should I apply this framework?

**Comment by junjiejiangjjj** [comment]
hi @goldwater668 , towhee integrates image models through [timm](https://github.com/huggingface/pytorch-image-models). If your model can be called through timm, use the following code:
```python
from towhee import pipe, ops, DataCollection

p = (
    pipe.input('path')
        .map('path', 'img', ops.image_decode())
        .map('img', 'vec', ops.image_embedding.timm(model_name='model_name', checkpoint_path="your local weights"))
        .output('img', 'vec')
)

DataCollection(p('towhee.jpeg')).show()
```
If not, you need to implement an operator yourself, https://towhee.readthedocs.io/en/latest/operator/usage.html#custom-operators

**Comment by goldwater668** [comment]
@junjiejiangjjj  
https://github.com/Westlake-AI/MogaNet
This is the warehouse of the model. I saw the following call. It should support timm. If you have time, you can help and see if it can be called directly.

from timm.models import create_model, apply_test_time_pool, load_checkpoint, is_model, list_models
from timm.data import create_dataset, create_loader, resolve_data_config, RealLabelsImagenet
from timm.utils import accuracy, AverageMeter, natural_key, setup_default_logging, set_jit_legacy
checkpoint = torch.load(checkpoint_path)
model = create_model(
        "moganet_xtiny",
        pretrained=False,
        num_classes=2,
        in_chans=3,
        global_pool=None,
        scriptable=False,
        mem_index=[10],
        K=1024)
model.load_state_dict(checkpoint["state_dict"], strict=True)
model = model.cuda()
model.eval()

transform = create_transform(input_size=(3, 224, 224),mean=(0.485, 0.456, 0.406),std=(0.229, 0.224, 0.225),crop_pct=0.9)
for root, subdirs, files in os.walk(folder, topdown=False, followlinks=True):
    rel_path = os.path.relpath(root, folder) if (root != folder) else ''
    label = os.path.basename(rel_path) if True else rel_path.replace(os.path.sep, '_')
    for f in files:
        base, ext = os.path.splitext(f)
        if ext.lower() in ['.png', '.jpg', '.jpeg']:
            image_path = os.path.join(root,f)
            img=Image.open(image_path)
            img = img.convert("RGB")
            input_image = transform(img).unsqueeze(0)
            input_image = Variable(input_image).to(DEVICE)
            out = model(input_image)
            img_num+=1
            classes = ('NG', 'OK')
            _, pred = torch.max(out.data, 1)

**Comment by junjiejiangjjj** [comment]
It seems that you need to run it in the directory of this project.
```shell
git clone https://github.com/Westlake-AI/MogaNet 
cd MogaNet 
```

```python
import models
from towhee import pipe, ops, DataCollection

p = (
    pipe.input('path')
        .map('path', 'img', ops.image_decode())
        .map('img', 'vec', ops.image_embedding.timm(model_name='moganet_xtiny', checkpoint_path="your local weights"))
        .output('img', 'vec')
)

DataCollection(p('towhee.jpeg')).show()
```

**Comment by goldwater668** [comment]
@junjiejiangjjj I see that your pipeline only has ConvNeXt and no ConvNeXt V2. Can ConvNeXt V2 be called directly from your place?

**Comment by goldwater668** [comment]
@junjiejiangjjj 
I entered and modified the number of channels to 4 and the number of categories to 14 on Moganet. I trained my own model and then performed inference without any problems. However, various problems occurred when using towhee. Of course, I also registered my own model. I don’t know what to do with it. No, you can run it using the official model without modifying the number of channels and categories.
The following is the code for inference：
`import os
import time
import cv2
import torch
import random
import numpy as np
from model.moganet import moganet_xtiny
import torch.nn.functional as F
import copy


model = moganet_xtiny(num_classes=14)
checkpoint = torch.load('model.th')
model.load_state_dict(checkpoint['state_dict'],strict=False)
model.cuda()
model.eval()

path = ''
pic_name = os.listdir(path)
# random.shuffle(pic_name)

nums = 0
for i in range(len(pic_name)):
    pic = pic_name[i]
    print(path + pic)
    img = cv2.imread(path + pic, 0)
    img_show = copy.deepcopy(img)

    img_h, img_w = img.shape
    if img_h !=148 or img_w != 220:
        img = cv2.resize(img, (220, 148))
        img_h, img_w = img.shape


    img1 = img[0:int(img_h / 2), 0:int(img_w / 2)]
    img2 = img[0:int(img_h / 2), int(img_w / 2):img_w]
    img3 = img[int(img_h / 2):img_h, 0:int(img_w / 2)]
    img4 = img[int(img_h / 2):img_h, int(img_w / 2):img_w]


    mean = (0., 0., 0., 0.)
    img1 = np.array(img1, np.float32) / 255 - mean[0]
    img2 = np.array(img2, np.float32) / 255 - mean[1]
    img3 = np.array(img3, np.float32) / 255 - mean[2]
    img4 = np.array(img4, np.float32) / 255 - mean[3]

    input = np.array([img1, img2, img3, img4], np.float32)
    print("input:",input.shape)
    input = torch.from_numpy(input).unsqueeze(0).cuda()
    print("input:",input.shape)
    t1 = time.time()
    pre= model(input)
    print(pre.shape)`


import cv2,torch
import numpy as np
from typing import Union
from towhee import register,operator,DataCollection,ops,pipe
from towhee.types import Image
@register
class ImageDecodeCV2_moganet(operator.PyOperator):
    def __init__(self, mode='BGR'):
        mode = mode.upper()
        if mode not in ['BGR', 'RGB']:
            raise RuntimeError("Mode only support BRG and RGB")
        self._mode = mode
    def __call__(self, image_path: str):
        img = cv2.imread(image_path,0)
        img_h, img_w = img.shape

        if img_h !=148 or img_w != 220:
            img = cv2.resize(img, (220, 148))
            img_h, img_w = img.shape
        img1 = img[0:int(img_h / 2), 0:int(img_w / 2)]
        img2 = img[0:int(img_h / 2), int(img_w / 2):img_w]
        img3 = img[int(img_h / 2):img_h, 0:int(img_w / 2)]
        img4 = img[int(img_h / 2):img_h, int(img_w / 2):img_w]


        mean = (0., 0., 0., 0.)
        img1 = np.array(img1, np.float32) / 255 - mean[0]
        img2 = np.array(img2, np.float32) / 255 - mean[1]
        img3 = np.array(img3, np.float32) / 255 - mean[2]
        img4 = np.array(img4, np.float32) / 255 - mean[3]
        
        input = np.array([img1, img2, img3, img4], np.float32)
        # input = torch.from_numpy(input).unsqueeze(0).cuda()
        print("input:",input.shape)
        return input
from model.moganet import moganet_xtiny
@register
class MogaNet(operator.NNOperator):
    def __init__(self):
        self.model = moganet_xtiny(num_classes=14)
        checkpoint = torch.load('model.th')
        self.model.load_state_dict(checkpoint['state_dict'],strict=False)
        # self.model.cuda()
        self.model.eval()

    def __call__(self, input):
        input = torch.from_numpy(input).unsqueeze(0)
        embeddings = self.model(input).squeeze(0).detach().numpy()
        print(embeddings.shape)
        return embeddings
class Extract_features:
    def __init__(self,model_name,device,checkpoint_path):
        self.image_embedding_pipe = (
            pipe.input('path')
                .map('path', 'img',  ops.ImageDecodeCV2_moganet())
                .map('img', 'embedding', ops.MogaNet())
                # .map('embedding', 'embedding', ops.towhee.np_normalize())
                # .output('embedding')
                
            )

    def extract_feat(self, img_path):
        feat = self.image_embedding_pipe.output('path', 'img', 'embedding')(img_path)
        return feat
    
#3.准备数据集
from glob import glob
# patterns of image paths
INSERT_SRC = './train/*/*.JPEG'
QUERY_SRC = './test/*/*.JPEG'
QUERY_SRC = ‘/test/*/*.jpg'
to_insert = glob(INSERT_SRC)
to_test = glob(QUERY_SRC)
to_test[0]

# 4.显示图像及编码
# MODEL_NAME = "resnet50"
MODEL_NAME = 'moganet_xtiny'
checkpoint_path = "model.th"
device = 'cuda:0'
MODEL = Extract_features(MODEL_NAME,device,checkpoint_path)
# Warm up the model to build image
path = '3.jpg'
p_display=MODEL.extract_feat(path)
# # Display embedding result, no need for implementation

DataCollection(p_display).show()

**Comment by goldwater668** [comment]
```
from models.moganet import moganet_xtiny
@register
class MogaNet_model(operator.NNOperator):
    def __init__(self):
        # checkpoint_path = "./weights/moga_0305B/moga/save_temp/model.th"
        checkpoint_path="./weights/moganet_xtiny_sz224_8xbs128_ep300.pth.tar"
        self.model = moganet_xtiny(num_classes=1000,in_channels=3)
        checkpoint = torch.load(checkpoint_path)
        self.model.load_state_dict(checkpoint['state_dict'],strict=False)
        # self.model.cuda()
        self.model.eval()

    def __call__(self, input):
        # input = torch.from_numpy(input).unsqueeze(0)
        embeddings = self.model(input)
        print(embeddings.shape)
        return embeddings
class Extract_features:
    def __init__(self,model_name,checkpoint_path):
        self.image_embedding_pipe = (
            pipe.input('path')
                .map('path', 'img', ops.image_decode())
                .map('img', 'embedding', ops.MogaNet_model())
                .map('embedding', 'embedding', ops.towhee.np_normalize())
        )
        # self.image_embedding_pipe = (
        #     pipe.input('path')
        #         .map('path', 'img', ops.image_decode.cv2('rgb'))
        #         .map('img', 'embedding', ops.image_embedding.timm(model_name=model_name,
        #                                                           checkpoint_path=checkpoint_path,
        #                                                           num_classes=1000
        #                                                         ))
        #         .map('embedding', 'embedding', ops.towhee.np_normalize())
        # )
    def extract_feat(self, img_path):
        feat = self.image_embedding_pipe.output('embedding')(img_path)
        print("feat:",feat)
        return feat
```
The error is reported as follows:
/media/hjq/EC3C5BDA3C5B9E80/win10/hjq_code/gpt/CV/MogaNet/test0913.py:45: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  checkpoint = torch.load(checkpoint_path)
*****forward_features******
Traceback (most recent call last):
  File "/media/hjq/EC3C5BDA3C5B9E80/win10/hjq_code/gpt/CV/MogaNet/test0913.py", line 96, in <module>
    p_display=MODEL.extract_feat(path)
  File "/media/hjq/EC3C5BDA3C5B9E80/win10/hjq_code/gpt/CV/MogaNet/test0913.py", line 73, in extract_feat
    feat = self.image_embedding_pipe.output('embedding')(img_path)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py", line 159, in __call__
    return self._call(*inputs, profiler=False, tracer=False)[0]
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py", line 177, in _call
    return graph(inputs), [graph.time_profiler] if profiler else None, [graph.data_queues] if tracer else None
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py", line 116, in __call__
    return f.result()
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py", line 34, in result
    ret = self._graph.result()
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/towhee/runtime/runtime_pipeline.py", line 95, in result
    raise RuntimeError(errs)
RuntimeError: Node-MogaNet-model-1 runs failed, error msg: conv2d() received an invalid combination of arguments - got (Image, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias = None, tuple of ints stride = 1, tuple of ints padding = 0, tuple of ints dilation = 1, int groups = 1)
      didn't match because some of the arguments have invalid types: (Image, Parameter, Parameter, tuple of (int, int), tuple of (int, int), tuple of (int, int), int)
 * (Tensor input, Tensor weight, Tensor bias = None, tuple of ints stride = 1, str padding = "valid", tuple of ints dilation = 1, int groups = 1)
      didn't match because some of the arguments have invalid types: (Image, Parameter, Parameter, tuple of (int, int), tuple of (int, int), tuple of (int, int), int)
, Traceback (most recent call last):
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/towhee/runtime/nodes/node.py", line 158, in _call
    return True, self._op(*inputs), None
  File "/media/hjq/EC3C5BDA3C5B9E80/win10/hjq_code/gpt/CV/MogaNet/test0913.py", line 52, in __call__
    embeddings = self.model(input)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/hjq/EC3C5BDA3C5B9E80/win10/hjq_code/gpt/CV/MogaNet/models/moganet.py", line 790, in forward
    x = self.forward_features(x)
  File "/media/hjq/EC3C5BDA3C5B9E80/win10/hjq_code/gpt/CV/MogaNet/models/moganet.py", line 763, in forward_features
    x, hw_shape = patch_embed(x)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/hjq/EC3C5BDA3C5B9E80/win10/hjq_code/gpt/CV/MogaNet/models/moganet.py", line 479, in forward
    x = self.projection(x)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d() received an invalid combination of arguments - got (Image, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias = None, tuple of ints stride = 1, tuple of ints padding = 0, tuple of ints dilation = 1, int groups = 1)
      didn't match because some of the arguments have invalid types: (Image, Parameter, Parameter, tuple of (int, int), tuple of (int, int), tuple of (int, int), int)
 * (Tensor input, Tensor weight, Tensor bias = None, tuple of ints stride = 1, str padding = "valid", tuple of ints dilation = 1, int groups = 1)
      didn't match because some of the arguments have invalid types: (Image, Parameter, Parameter, tuple of (int, int), tuple of (int, int), tuple of (int, int), int)

, Traceback (most recent call last):
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/towhee/runtime/nodes/node.py", line 171, in process
    self.process_step()
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/towhee/runtime/nodes/_map.py", line 63, in process_step
    assert succ, msg
AssertionError: conv2d() received an invalid combination of arguments - got (Image, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias = None, tuple of ints stride = 1, tuple of ints padding = 0, tuple of ints dilation = 1, int groups = 1)
      didn't match because some of the arguments have invalid types: (Image, Parameter, Parameter, tuple of (int, int), tuple of (int, int), tuple of (int, int), int)
 * (Tensor input, Tensor weight, Tensor bias = None, tuple of ints stride = 1, str padding = "valid", tuple of ints dilation = 1, int groups = 1)
      didn't match because some of the arguments have invalid types: (Image, Parameter, Parameter, tuple of (int, int), tuple of (int, int), tuple of (int, int), int)
, Traceback (most recent call last):
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/towhee/runtime/nodes/node.py", line 158, in _call
    return True, self._op(*inputs), None
  File "/media/hjq/EC3C5BDA3C5B9E80/win10/hjq_code/gpt/CV/MogaNet/test0913.py", line 52, in __call__
    embeddings = self.model(input)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/hjq/EC3C5BDA3C5B9E80/win10/hjq_code/gpt/CV/MogaNet/models/moganet.py", line 790, in forward
    x = self.forward_features(x)
  File "/media/hjq/EC3C5BDA3C5B9E80/win10/hjq_code/gpt/CV/MogaNet/models/moganet.py", line 763, in forward_features
    x, hw_shape = patch_embed(x)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/media/hjq/EC3C5BDA3C5B9E80/win10/hjq_code/gpt/CV/MogaNet/models/moganet.py", line 479, in forward
    x = self.projection(x)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/container.py", line 219, in forward
    input = module(input)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 458, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/hjq/anaconda3/envs/image_search/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
TypeError: conv2d() received an invalid combination of arguments - got (Image, Parameter, Parameter, tuple, tuple, tuple, int), but expected one of:
 * (Tensor input, Tensor weight, Tensor bias = None, tuple of ints stride = 1, tuple of ints padding = 0, tuple of ints dilation = 1, int groups = 1)
      didn't match because some of the arguments have invalid types: (Image, Parameter, Parameter, tuple of (int, int), tuple of (int, int), tuple of (int, int), int)
 * (Tensor input, Tensor weight, Tensor bias = None, tuple of ints stride = 1, str padding = "valid", tuple of ints dilation = 1, int groups = 1)
      didn't match because some of the arguments have invalid types: (Image, Parameter, Parameter, tuple of (int, int), tuple of (int, int), tuple of (int, int), int)

**Comment by junjiejiangjjj** [comment]
hi @goldwater668 , if you change the channels, you also need to change it when initializing the model.
![image](https://github.com/user-attachments/assets/215ac2b8-0bf2-40fd-ab00-b388b3a5f0bb)

**Comment by goldwater668** [comment]
@junjiejiangjjj 
Thank you for your timely reply. I have modified it as follows and the verification has passed.
`
@register
class ImageDecodeCV2_moganet(operator.PyOperator):
    def __init__(self, mode=False):
        self.mode=mode
        print("model:",mode)
    def __call__(self, image_path: str):
        if self.mode:
           bgr_cv_image = cv2.imread(image_path)
           rgb_cv_image = cv2.cvtColor(bgr_cv_image, cv2.COLOR_BGR2RGB)
           return Image(rgb_cv_image, 'RGB')
        else:
           input = read_image(image_path)
        return input
def read_image(image_path):
    img = cv2.imread(image_path,0)
    img_h, img_w = img.shape

    if img_h !=148 or img_w != 220:
        img = cv2.resize(img, (220, 148))
        img_h, img_w = img.shape
    img1 = img[0:int(img_h / 2), 0:int(img_w / 2)]
    img2 = img[0:int(img_h / 2), int(img_w / 2):img_w]
    img3 = img[int(img_h / 2):img_h, 0:int(img_w / 2)]
    img4 = img[int(img_h / 2):img_h, int(img_w / 2):img_w]


    mean = (0., 0., 0., 0.)
    img1 = np.array(img1, np.float32) / 255 - mean[0]
    img2 = np.array(img2, np.float32) / 255 - mean[1]
    img3 = np.array(img3, np.float32) / 255 - mean[2]
    img4 = np.array(img4, np.float32) / 255 - mean[3]
    
    input = np.array([img1, img2, img3, img4], np.float32)
    input = torch.from_numpy(input).unsqueeze(0).cuda()
    print("input:",input.shape)
    return input
@register
class MogaNet_model(operator.NNOperator):
    def __init__(self,device, num_classes,in_channels,checkpoint_path=None):
        self.device = device
        self.model = moganet_xtiny(num_classes=num_classes,in_channels=in_channels)
        checkpoint = torch.load(checkpoint_path)
        self.model.load_state_dict(checkpoint['state_dict'],strict=False)
        self.model.eval()
        self.model.to(device)

    def convert_img(self, img: 'towhee.types.Image'):
        img = PILImage.fromarray(img.astype('uint8'), 'RGB')
        return img
    def __call__(self, input):
        if isinstance(input, torch.Tensor):
            pre= self.model.forward_features(input)
        else:
            self.tfms = create_transform(**resolve_data_config({}, model=self.model))
            img = self.convert_img(input) if isinstance(input, numpy.ndarray) else input.convert('RGB')
            img = self.tfms(img)
            inputs = torch.stack([img])
            pre= self.model.forward_features(inputs.cuda())
        pre = pre.to('cpu')
        if pre.dim() == 4:
                global_pool = nn.AdaptiveAvgPool2d(1)
                features = global_pool(pre)
                features = features.flatten(1)
        # print(features.shape)
        # print(features.squeeze(0).detach().numpy().shape)
        embeddings = features.squeeze(0).detach().numpy()
        return embeddings

class Extract_features:
    def __init__(self,device, num_classes,in_channels,checkpoint_path,mode=False):
        self.image_embedding_pipe = (
            pipe.input('path')
                .map('path', 'img', ops.ImageDecodeCV2_moganet(mode=mode))
                .map('img', 'embedding', ops.MogaNet_model(device, num_classes,in_channels,checkpoint_path=checkpoint_path))
                .map('embedding', 'embedding', ops.towhee.np_normalize())
        )
    def extract_feat(self, img_path):
        feat = self.image_embedding_pipe.output('embedding')(img_path)
        print("feat:",feat)
        return feat`
The dimension of extracted features here is 192 dimensions. Can this dimension be changed to 768 dimensions? How to change it? Is it determined by the training model?

**Comment by junjiejiangjjj** [comment]
This is determined by the model. This model has these specifications
![image](https://github.com/user-attachments/assets/18a66783-d879-42c3-9806-575f0cc69336)

**Comment by goldwater668** [comment]
@junjiejiangjjj 
The following is the result of inserting data and retrieving it. There are more than 4,000 retrieved data. The following is the time-consuming and concurrency of 1, 5, 10, and 20 images in each category. Is there any plan to optimize the time-consuming and concurrency? Woolen cloth
Single image storage
mAP@10: 0.9694069575648523
qps: 12.297192555948484
res: 4446
Time taken: 361.54593658447266

5 images in the database:
mAP@10: 0.9747572724546408
qps: 29.021526577717232
res: 4446
Time taken: 153.19662761688232

10 images in the database:
mAP@10: 0.9840112210726246
qps: 28.206053224578568
res: 4446
Time taken: 157.62573957443237

20 images in the database:
mAP@10: 0.9884930899185285
qps: 27.372619227329775
res: 4446
Time taken:162.42508482933044

**Comment by junjiejiangjjj** [comment]
Towhee accelerates model inference through [Triton Server](https://towhee.readthedocs.io/en/latest/triton/triton.html) , but only supports a subset of models. For your own models, you can consider converting them to ONNX to accelerate inference.

**Comment by goldwater668** [comment]
@junjiejiangjjj 
Where is the similarity threshold for retrieval set?

**Comment by goldwater668** [comment]
@junjiejiangjjj 
Where can I check the similarity threshold? How to set the similarity measurement threshold? What should I do if I want to extract feature points from surf in opencv and store them in the database?

**Comment by junjiejiangjjj** [comment]
I don't quite understand your question. Could you look at these cases to see if there are any similar scenarios to yours? https://github.com/towhee-io/examples

**Comment by junjiejiangjjj** [comment]
> @junjiejiangjjj The first thing is where to set the top5 threshold in accuracy? Can the top5 similarities be printed out?
> 
> The second thing is whether I use traditional algorithms for feature extraction and then vector retrieval, such as surf feature point extraction in opencv

1. When searching, just set the top 5
```python
# Search pipeline
p_search_pre = (
        p_embed.map('vec', ('search_res'), ops.ann_search.milvus_client(
                    host=HOST, port=PORT, limit=TOPK,
                    collection_name=COLLECTION_NAME))
               .map('search_res', 'pred', lambda x: [str(Path(y[0]).resolve()) for y in x])
#                .output('img_path', 'pred')
)
p_search = p_search_pre.output('img_path', 'pred')
```

2. Milvus stores this information through scalars

You can refer to this example
https://github.com/towhee-io/examples/blob/main/image/reverse_image_search/1_build_image_search_engine.ipynb

**Comment by goldwater668** [comment]
@junjiejiangjjj 
The first thing is not to print this, what is the score of each similarity of the top5 or the distance of the similarity?

**Comment by goldwater668** [comment]
@junjiejiangjjj 
 INDEX_TYPE = 'HNSW'
METRIC_TYPE = 'IP'
pymilvus.exceptions.MilvusException: <MilvusException: (code=65535, message=fail to search on QueryNode 10: worker(10) query failed: metric type not match: invalid parameter[expected=IP][actual=L2])>
