### ISSUE TITLE
在对视频进行向量化时如何对多个视频同时进行处理？

### ISSUE THREAD

**Issue by Terran0629** [towhee-io/towhee#2701]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

towhee团队你们好。经过测试，如果一条一条视频进行处理，使用cpu的效率和使用gpu的效率差不多，甚至cpu略快于gpu。假设我现在有数十万条视频数据，我该如何对数据进行批处理呢？如果一条条进行处理不仅费时还无法利用gpu的性能。

**Comment by junjiejiangjjj** [comment]
hi @Terran0629 , the performance bottleneck of video processing is video decoding. https://towhee.io/video-decode/VPF, this decoding operator uses GPU to accelerate video decoding.  You can also process multiple videos at once through the batch interface

**Comment by Terran0629** [comment]
您好，有没有具体的例子可以提供一下呢
