### ISSUE TITLE
目前使用clip4clip在时间均匀采样下只能提取12帧吗

### ISSUE THREAD

**Issue by Terran0629** [towhee-io/towhee#2702]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

我想知道clip4clip对一段视频进行向量化时最多只能提取12帧，多余12帧的话会报错

i

```
mport towhee
from towhee import pipe,ops
from time import time

device = 'cpu'
pipes = (
    pipe.input('path')
    .map('path','flames',ops.video_decode.ffmpeg(sample_type='uniform_temporal_subsample', args={'num_samples': 12})) #
    .map('flames','vec',ops.video_text_embedding.clip4clip(model_name='clip_vit_b32', modality='video', device=device))
    .output('vec')
)
# video_path = r'E:\video_danganguan\0451-2001-006-1139.mp4'
video_path = r'E:\data\video\cartoon.mp4'
s = time()
a = pipes(video_path)
e = time()
print('time:',e-s)

```

**Comment by junjiejiangjjj** [comment]
hi @Terran0629 , the code limits the max frame to 12： https://towhee.io/video-text-embedding/clip4clip/src/branch/main/clip4clip.py

**Comment by Terran0629** [comment]
> hi ，代码将最大帧限制为 12：https://towhee.io/video-text-embedding/clip4clip/src/branch/main/clip4clip.py

Thanks for your reply! I'm modifying the frame rate in the source code, so it shouldn't affect its functionality, right?

**Comment by junjiejiangjjj** [comment]
Changing the frame rate does not affect the model's operation, but the model was trained with 12 frames, so altering it may impact the results.
