### ISSUE TITLE
[Bug]: ERROR: 404 Client Error: Not Found for url

### ISSUE THREAD

**Issue by Bowei-Jiang** [towhee-io/towhee#2703]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
When I tried to run:
 p_add = (
    pipe.input('video_path')
    .map('video_path', 'frames', ops.video_decode.ffmpeg(sample_type='uniform_temporal_subsample', args={'num_samples': 12}))
    .map('frames', 'vec', ops.video_text_embedding.clip4clip(model_name='clip_vit_b32', modality='video', device='cuda:1'))
    .map(('video_path', 'vec'), (), ops.ann_insert.milvus_client(host='127.0.0.1', port='19530', collection_name='text_video_search'))
    .output()
)

this error occured:
2024-09-14 14:21:50,016 - 139958348993728 - hub_utils.py-hub_utils:443 - ERROR: 404 Client Error: Not Found for url: https://towhee.io/towhee-api/v1/repos/image-text-embedding/clip4clip/tree?recursive=true&ref=main, Traceback (most recent call last):

### Expected Behavior

I am wondering whether the url "https://towhee.io/towhee-api/v1/repos/image-text-embedding/clip4clip/tree?recursive=true&ref=main" is unreachable or not?

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
hi @Bowei-Jiang , what version of towhee are you using? 1.1.3 works fine.

**Comment by Bowei-Jiang** [comment]
> hi @Bowei-Jiang , what version of towhee are you using? 1.1.3 works fine.

I use 1.1.3，but it is still unreachable, I suppose that it maybe the firewall. 
I am wondering whether I can download the required data in the url by wget or other ways?
