### ISSUE TITLE
[Feature]: About function:  ops.video_text_embedding.clip4clip(model_name='clip_vit_b32', modality='video', device='cuda:1')

### ISSUE THREAD

**Issue by Bowei-Jiang** [towhee-io/towhee#2704]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

I download clip model on machine, and I want to load local clip model to run the function "ops.video_text_embedding.clip4clip()".

For example, my codes are: "ops.video_text_embedding.clip4clip(model_name='/root/data/clip_model/clip-vit-large-patch14', modality='video', device='cuda:1')", however, this error occurs:

ValueError: Invalid model name '/root/data/clip_model/clip-vit-large-patch14', 

Could anyone tell me how can I load the local clip model when running ops.video_text_embedding.clip4clip() ?

**Comment by junjiejiangjjj** [comment]
hi @Bowei-Jiang , you can specify your weight through the weight_path parameter : ops.video_text_embedding.clip4clip(model_name='clip_vit_b32', modality='video', `weight_path="your weights"`,  device='cuda:1')

**Comment by Bowei-Jiang** [comment]
> hi @Bowei-Jiang , you can specify your weight through the weight_path parameter : ops.video_text_embedding.clip4clip(model_name='clip_vit_b32', modality='video', `weight_path="your weights"`, device='cuda:1')

OK, thanks a lot
