### ISSUE TITLE
Is this repo maintained? 

### ISSUE THREAD

**Issue by pranavchaturved** [towhee-io/towhee#2705]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

It's been a while since the last commit. Just want to understand if this is still being actively maintained.

### Why is this needed?

This helps in deciding if we should go ahead with using this repo or look for alternatives that are actively maintained. 

### Anything else?

That'

**Comment by junjiejiangjjj** [comment]
hi @pranavchaturved , towhee is still under maintenance, but no new features are being developed.

**Comment by pranavchaturved** [comment]
Thanks for the information.
