### ISSUE TITLE
[Bug]: requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://towhee.io/towhee-api/v1/repos/image-text-embedding/clip4clip/tree?recursive=true&ref=main

### ISSUE THREAD

**Issue by Bowei-Jiang** [towhee-io/towhee#2707]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The error occurs in the function **branch_tree** in  "/towhee/utils/hub_utils.py"  when I run  method  ops.video_text_embedding.clip4clip(model_name="clip_vit_b32", modality='video',device='cuda')):
```
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://towhee.io/towhee-api/v1/repos/image-text-embedding/clip4clip/tree?recursive=true&ref=main

2024-09-19 08:31:31,361 - 140288235734208 - operator_loader.py-operator_loader:134 - ERROR: Fetch op image-text-embedding/clip4clip:main info failed
```

Then, I use requests methods to test this url on both linux and windows environment:
```
import requests
url = "https://towhee.io/towhee-api/v1/repos/image-text-embedding/clip4clip/tree?recursive=true&ref=main"
r = requests.get(url)
print(r.text) 
```
but I got this result:
```
{"documentation_url":"https://towhee.io/api/swagger","errors":null,"message":"Not Found"}
```

I doubt that this url is not available, could anyone tell me what's wrong with it?

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by junjiejiangjjj** [comment]
`ops.video_text_embedding.clip4clip(model_name="clip_vit_b32", modality='video',device='cuda'))` the corresponding link should be this: https://towhee.io/towhee-api/v1/repos/video-text-embedding/clip4clip/tree?recursive=true&ref=main   it's strange that you used the wrong address. I tested it myself and there is no problem.

**Comment by Bowei-Jiang** [comment]
> `ops.video_text_embedding.clip4clip(model_name="clip_vit_b32", modality='video',device='cuda'))` the corresponding link should be this: https://towhee.io/towhee-api/v1/repos/video-text-embedding/clip4clip/tree?recursive=true&ref=main it's strange that you used the wrong address. I tested it myself and there is no problem.

Got it, thanks a lot!
