### ISSUE TITLE
[Bug]: Embedding is failed for "Image" type object with pipeline "shiyu/img_object_embedding_pytorch_yolov5_resnet50"

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#304]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Embedding is failed for "Image" type object with pipeline "shiyu/img_object_embedding_pytorch_yolov5_resnet50" reporting:

Can't convert object of type 'Image' to 'str' for 'filename'

```
>>> embedding = embedding_pipeline(img)
Using cache found in /Users/binbin/.cache/torch/hub/ultralytics_yolov5_master
YOLOv5 🚀 2021-12-1 torch 1.10.0 CPU

Fusing layers...
Model Summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape...
/Users/binbin/Towhee_projects/towhee-test-env/lib/python3.8/site-packages/torch/autocast_mode.py:141: UserWarning: User provided device_type of 'cuda', but CUDA is not available. Disabling
  warnings.warn('User provided device_type of \'cuda\', but CUDA is not available. Disabling')
Can't convert object of type 'Image' to 'str' for 'filename'
```

### Expected Behavior

Embedding is successful

### Steps To Reproduce

```markdown
from PIL import Image
from towhee import pipeline

img = Image.new(mode="RGB", size=(200, 200), color=(155, 155, 155))
pipeline_name = "shiyu/img_object_embedding_pytorch_yolov5_resnet50"
embedding_pipeline = pipeline(pipeline_name)
embedding = embedding_pipeline(img)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.2.2
- OS(Ubuntu or CentOS): mac
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by shiyu22** [comment]
Actually, the input of the pipeline of `img_object_embedding_pytorch_yolov5_resnet50` is the path of the image, which is the str format, and what you input is the PIL.Image format, do you need to input PIL.imag?

**Comment by binbinlv** [comment]
Yes, other pipelines are supported like "image-embedding", and it is convenient to create tested images automatically. So it is good if could handle this scenario. 

Thanks.

**Comment by shiyu22** [comment]
If add the input of PIL.image, it will be another pipeline, but I think people who do object detection should have local images, so they will use the path of the input image.

If there is an actual scenario for this demand, I will write a new pipeline, but there is no plan at this time.

**Comment by binbinlv** [comment]
OK, close it.
