### ISSUE TITLE
[Bug]: Pipeline "towhee/video_embedding_resnet50" hangs when embedding avi type video

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#306]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pipeline "towhee/video_embedding_resnet50" hangs when embedding avi type video

### Expected Behavior

Embedding successfully

### Steps To Reproduce

```python
from towhee import pipeline
p = pipeline('towhee/video_embedding_resnet50')
video_path_1 = "/Users/binbin/Towhee_projects/test.avi"
video_path_1_vec = p(video_path_1)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.2.3.dev3
- OS(Ubuntu or CentOS): mac
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by Ashvith** [comment]
Maybe there's more code after `video_path_1`?
I believe this must be it?
```python
video_path_1_vec = p(video_path_1)
```

**Comment by binbinlv** [comment]
> Maybe there's more code after `video_path_1`? I believe this must be it?
> 
> ```python
> video_path_1_vec = p(video_path_1)
> ```

Yes, thanks for remind.

**Comment by fzliu** [comment]
We are deprecating the existing video embedding pipeline; a newer and much improved version will be released later down the road.
