### ISSUE TITLE
TODO: How to pass the directory of a weight file to an operator

### ISSUE THREAD

**Issue by Chiiizzzy** [towhee-io/towhee#314]
Say we have an operator which takes the path of a model weight file as the init arg like following:
<img width="614" alt="截屏2021-12-10 下午5 16 22" src="https://user-images.githubusercontent.com/72550076/145549013-8ed9ae6f-a961-4feb-9ab3-1879b9faf861.png">
If the user provides the weight file in the operator repo, which in this case is `clmr_magnatagatune&towhee$main/checkpoints/clmr_checkpoint_10000.pt`
How do we deal with the init arg in pipeline yaml file?
We cannot use abs path since the different users have different user directory, we cannot user relative path since we don't know the under which directory will the users run the pipeline.

**Comment by Chiiizzzy** [comment]
Issue brought up by @jaelgu and @Chiiizzzy 
@fzliu @junjiejiangjjj @guo1

**Comment by junjiejiangjjj** [comment]
![image](https://user-images.githubusercontent.com/14136703/145555456-39036460-f0e7-42b5-8f8a-1ceab2482140.png)
We could do it like this, so in the pipeline's YAML file, the init arg  `model_name: a` or `model_name: b`
