### ISSUE TITLE
[Enhancement]: Pipeline and operator updates should be automatically downloaded even if a cached version exists

### ISSUE THREAD

**Issue by fzliu** [towhee-io/towhee#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

If a repository (either pipeline or operator) on the Towhee hub is updated, the changes are not automatically reflected during local runs if a prior version of said repository exists.

### Why is this needed?

This seems to be unintended behavior.

**Comment by Chiiizzzy** [comment]
Now replace download with git, every time we run a pipeline or call an operator, towhee will automatically get the latest version on your branch.
