### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by zc277584121** [towhee-io/towhee#337]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/17022025/147184726-15e9a643-693c-48f0-affa-34228c4d5f82.png)
concat can not deal with ndarray

### Expected Behavior

Concat op need support ndarray

### Steps To Reproduce

```markdown
from towhee import pipeline
img_path = # image path
embedding_pipeline = pipeline('towhee/eff_b7_concat_swin_large')
embedding = embedding_pipeline(img_path)
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by zc277584121** [comment]
@filip-halt

**Comment by filip-halt** [comment]
Running that code gives me the following error: `RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0`
