### ISSUE TITLE
[Bug]: Can't pip install towhee

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I failed to install towhee with miniconda, where python version 3.8
<img width="975" alt="截屏2021-12-25 下午3 28 56" src="https://user-images.githubusercontent.com/34296482/147380082-35fb3340-fc5f-4f02-bc3e-6a2fc5c62225.png">

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS): 
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by jingkl** [comment]
Python version 3.9 has the same problem

**Comment by fzliu** [comment]
Can you elaborate?

**Comment by Chiiizzzy** [comment]
When install towhee from `test.pypi` please specify `--extra-index-url https://pypi.org/simple`, because `test.pypi` lacks some packages.

**Comment by fzliu** [comment]
> When install towhee from `test.pypi` please specify `--extra-index-url https://pypi.org/simple`, because `test.pypi` lacks some packages.

@jingkl Does this fix your issue?

**Comment by jingkl** [comment]
> --extra-index-url https://pypi.org/simple

![Uploading 截屏2021-12-25 下午4.20.26.png…]()

**Comment by jingkl** [comment]
> > 当安装拖着`test.pypi`请指定`--extra-index-url https://pypi.org/simple`，因为`test.pypi`缺少一些包。
> 
> @jingkl这能解决你的问题吗？

It still doesn't seem to be possible

**Comment by jingkl** [comment]
> > 当安装拖着`test.pypi`请指定`--extra-index-url https://pypi.org/simple`，因为`test.pypi`缺少一些包。
> 
> @jingkl这能解决你的问题吗？

It still doesn't seem to be possible

**Comment by jingkl** [comment]
<img width="1297" alt="截屏2021-12-25 下午4 27 16" src="https://user-images.githubusercontent.com/34296482/147380901-50f584a1-b7b5-4ac2-ac75-77edf8d7fa99.png">
