### ISSUE TITLE
[Enhancement]: Error reporting logs should be more accurate

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#349]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?
pipelines："towhee/image-embedding-efficientnetb5"

The content of the error report has nothing to do with the lack of uploading images

 Test script：

```
   def test_embedding_no_obj_image(self, pipeline_name):
        """
        target: test embedding for no object image
        method:  embedding with no object image
        expected: raise exception for empty result
        """
        img = "../../towhee_logo.png"
        embedding_pipeline = pipeline(pipeline_name)
        try:
            embedding = embedding_pipeline(img)
        except RuntimeError as e:
            assert "Unkown error" in str(e)

        return True
```
error log：

<img width="1431" alt="截屏2021-12-27 下午2 59 42" src="https://user-images.githubusercontent.com/34296482/147444069-527f2a87-0f9c-4a9f-b144-f105ae86a413.png">

**Comment by fzliu** [comment]
#347
