### ISSUE TITLE
[Bug]:  All the towhee image pipelines are crashed when embedding an image on windows10 client

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

All the towhee embedding is crashed in windows client:

```
>>> from towhee import pipeline
>>> img_path = r'C:\Users\zilliz\Desktop\towhee-images\1.jpg'
>>> embedding_pipeline = pipeline('towhee/image-embedding-swinbase')
Downloading image_embedding_swinbase.yaml: 100%|██████████████████████████████████| 1.59k/1.59k [00:00<00:00, 534kiB/s]
Downloading .gitignore: 100%|█████████████████████████████████████████████████████| 3.10k/3.10k [00:00<00:00, 254kiB/s]
Downloading README.md: 100%|██████████████████████████████████████████████████████| 1.53k/1.53k [00:00<00:00, 191kiB/s]
Downloading readme_res/pipeline.png: 100%|██████████████████████████████████████████| 220k/220k [00:00<00:00, 686kiB/s]
>>> embedding = embedding_pipeline(img_path)
```
Python terminal exited here

### Expected Behavior

Embedding successfully

### Steps To Reproduce

```markdown
1 install latest towhee image

pip install -i https://test.pypi.org/simple/ towhee==0.3.1.dev19

2 run the following script

from towhee import pipeline
img_path = r'C:\Users\zilliz\Desktop\towhee-images\1.jpg'
embedding_pipeline = pipeline('towhee/image-embedding-swinbase')
embedding = embedding_pipeline(img_path)


Tried all the other image pipelines
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.3.1.dev19
- Python: 3.8
- OS(Ubuntu or CentOS): Windows  10.0.19043.1415
- CPU/Memory: 
- GPU: 
- Others:
```

**Comment by fzliu** [comment]
This might also be due to the missing index URL (#346).

**Comment by binbinlv** [comment]
It is not for the reason with #346.

Install using "pip install towhee==0.4.0rc1", it crashed again when embedding.

(install and pipeline download are successful.

**Comment by fzliu** [comment]
Fixed by: #377

<img width="839" alt="Screen Shot 2021-12-30 at 9 25 46 PM" src="https://user-images.githubusercontent.com/6334158/147756062-27cdd53d-5307-4dde-8fab-fa3a91b03574.png">

**Comment by fzliu** [comment]
FYI, Visual C++ redistributable  is required for Windows support. I used [this installer](https://download.visualstudio.microsoft.com/download/pr/d3cbdace-2bb8-4dc5-a326-2c1c0f1ad5ae/9B9DD72C27AB1DB081DE56BB7B73BEE9A00F60D14ED8E6FDE45DAB3E619B5F04/VC_redist.x64.exe)

**Comment by binbinlv** [comment]
Verified in towhee 0.3.1.dev31, and fixed.

So closed.
