### ISSUE TITLE
[Enhancement] Need to print a message indicating that vector generation is complete

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#352]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?
towhee version：0.3.1dev19
Now the vector generation will finish with warning

<img width="1423" alt="截屏2021-12-27 下午4 23 36" src="https://user-images.githubusercontent.com/34296482/147451565-a3df0853-6952-4127-be8d-4182890d1aab.png">

**Comment by jaelgu** [comment]
#close

**Comment by fzliu** [comment]
Are you requesting us to suppress the warning or to notify the user upon completion?

**Comment by jingkl** [comment]
> Are you requesting us to suppress the warning or to notify the user upon completion?

Cancellation of warnings and notification of users upon completion are both required
