### ISSUE TITLE
[Bug]: Towhee install failed when installing the latest test pypi image directly

### ISSUE THREAD

**Issue by binbinlv** [towhee-io/towhee#354]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Towhee install failed when installing the latest test pypi image directly:

pip install -i https://test.pypi.org/simple/ towhee==0.3.1.dev19
Looking in indexes: https://test.pypi.org/simple/
Collecting towhee==0.3.1.dev19
  Downloading https://test-files.pythonhosted.org/packages/32/e1/f6de6b31c9f8b575513ac8ac82504541b8688bd29821adf85e44bf4d98cb/towhee-0.3.1.dev19-py3-none-any.whl (293 kB)
     |████████████████████████████████| 293 kB 70 kB/s
ERROR: Could not find a version that satisfies the requirement tqdm>=4.59.0 (from towhee) (from versions: none)
ERROR: No matching distribution found for tqdm>=4.59.0

2. If installing the former release version firstly, and then install the latest test pypi image, it could install successfully.

### Expected Behavior

Towhee is installed successfully when installing the latest test pypi image directly

### Steps To Reproduce

```markdown
1. Create virtual env

2. pip install -i https://test.pypi.org/simple/ towhee==0.3.1.dev19
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.3.1.dev19
- OS(Ubuntu or CentOS): Ubuntu 18.04
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
assign @fzliu

**Comment by fzliu** [comment]
What version of Python are you using?

**Comment by binbinlv** [comment]
Python 3.9.7

**Comment by fzliu** [comment]
Can you try adding the extra index URL a-la #346?

**Comment by binbinlv** [comment]
OK， trying.

**Comment by binbinlv** [comment]
OK， it is good when using "pip install -i https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple towhee==0.3.1.dev19", so close it.
