### ISSUE TITLE
[Bug]: The pipeline input image does not support png, bmp, gif format “A runtime error will occur”

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

pipeline：towhee/image-embedding-efficientnetb5
Using bmp, png, gif format images, the error appears as shown in the figure：

<img width="1430" alt="截屏2021-12-27 下午5 12 18" src="https://user-images.githubusercontent.com/34296482/147455907-165e84dc-ead5-470a-807f-037d583fecbb.png">
<img width="1433" alt="截屏2021-12-27 下午5 13 57" src="https://user-images.githubusercontent.com/34296482/147456050-55d6ab65-3c5c-42dd-9984-f2d664b9694e.png">
<img width="1431" alt="截屏2021-12-27 下午5 14 11" src="https://user-images.githubusercontent.com/34296482/147456090-147634d4-95a4-4c99-831e-0ad8a46e7ab6.png">

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):towhee==0.3.1.dev19 
- OS(Ubuntu or CentOS):macos
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jingkl** [comment]
pipeline:towhee/image-embedding-efficientnetb7,towhee/image-embedding-swinbase,towhee/image-embedding-swinlarge,towhee/image-embedding-vitlarge Have the same error

**Comment by jingkl** [comment]
I tested by removing the local operator and got this result

> @jingkl It looks like resulted by mode of image. It should be fixed with latest operator. Please delete local operator files and try again.

**Comment by jaelgu** [comment]
This is resulted by the input image mode "RGBA" while these pipelines only support mode of "RGB"

**Comment by shiyu22** [comment]
Added [image-decoder](https://towhee.io/towhee/image-decoder/src/branch/main/image_decoder.py) operator, it solved. You can remove ~/.towhee and try again.

**Comment by jingkl** [comment]
I will try in the latest version
