### ISSUE TITLE
[Bug]: Instantiating the pipeline 'music-encoder' returns "Incorrect pipeline format" error

### ISSUE THREAD

**Issue by timshen** [towhee-io/towhee#362]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
![Screen Shot 2021-12-28 at 2 55 48 PM](https://user-images.githubusercontent.com/2637142/147540182-ecab4b62-de8f-4517-8521-535f647d95ee.png)

### Expected Behavior

should successfully instantiate the pipeline

### Steps To Reproduce

```markdown
1. pip install towhee
2. enter python
3. >>> from towhee import pipeline
   >>> embedding_pipeline = pipeline('music-encoder')
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS): MacOS 11.3
- CPU/Memory:
- GPU:
- Others:
```

**Comment by fzliu** [comment]
Fixed via https://github.com/towhee-io/towhee-docs/pull/104.
