### ISSUE TITLE
[Bug]: The pipeline list page shows no pipeline

### ISSUE THREAD

**Issue by timshen** [towhee-io/towhee#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The more pipelines page linked in https://docs.towhee.io/solutions/music-recognition-system displays no pipeline
<img width="1232" alt="Screen Shot 2021-12-28 at 3 07 14 PM" src="https://user-images.githubusercontent.com/2637142/147538572-7945a2e7-69f9-44bd-9e1b-b14eb2129ce9.png">

### Expected Behavior

A page displays all pipelines

### Steps To Reproduce

```markdown
1. go to https://docs.towhee.io/solutions/music-recognition-system/
2. scroll down to bottom
3. click link mentioned by "In the music recognition system, audio fingerprints can be extracted through a Towhee pipeline. We provide a list of different music embedding pipelines here."
4. A new page opened https://hub.towhee.io/pipelines
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by shiyu22** [comment]
Thanks @timshen, and updated it with [#103](https://github.com/towhee-io/towhee-docs/pull/103).
