### ISSUE TITLE
[Bug]: The flag in pipeline "force-download" does not re-download operators

### ISSUE THREAD

**Issue by jaelgu** [towhee-io/towhee#364]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

With towhee installed, run in python:
```
from towhee import pipeline
my_pipeline = pipeline('towhee/image-embedding-resnet50')
my_pipeline('path/to/image')

new_pipeline = pipeline('towhee/image-embedding-resnet50', force-download=True)
new_pipeline('path/to/image')
```

`force-download` only re-download pipeline but not related operator.

### Expected Behavior

`force-download` will re-download pipeline & involved operators from towhee.io

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by filip-halt** [comment]
@fzliu Since we moved runners to multithreaded, this breaks as each thread will attempt to redownload resulting in stuff breaking. We need to figure out some long term plan for this to work now and in the distributed version.

**Comment by Chiiizzzy** [comment]
Now replace download with git, every time we run a pipeline or call an operator, towhee will automatically get the latest version on your branch, therefore we do not need force-download option now
