### ISSUE TITLE
[Bug]: A link in "Reverse image search" document leads to a 404 error 

### ISSUE THREAD

**Issue by timshen** [towhee-io/towhee#366]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

1. Go to https://docs.towhee.io/tutorials/reverse-image-search/
2. Scroll down to bottom
3. Click the link "Please visit [this page](https://docs.towhee.io/solutions/pipelines/image-embedding) a full list of image embedding pipelines Towhee supports."
<img width="756" alt="Screen Shot 2021-12-28 at 7 21 09 PM" src="https://user-images.githubusercontent.com/2637142/147561248-509a41e7-515c-4c20-be6c-07b9df9cc872.png">

Then got a 404 page

<img width="1109" alt="Screen Shot 2021-12-28 at 7 17 54 PM" src="https://user-images.githubusercontent.com/2637142/147561016-307dc758-9401-4e83-95f7-cf79cfcc9223.png">

### Expected Behavior

A right page should be displayed 

### Steps To Reproduce

```markdown
As above
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by shanghaikid** [comment]
I think it is https://docs.towhee.io/tutorials/reverse-image-search, where do you find the link?

**Comment by timshen** [comment]
> I think it is https://docs.towhee.io/tutorials/reverse-image-search, where do you find the link?

Yes, updated the description

**Comment by shiyu22** [comment]
Thanks @timshen, and updated it with [#103](https://github.com/towhee-io/towhee-docs/pull/103).
