### ISSUE TITLE
[Bug]: Test image pipeline  image-embedding-efficientnetb7：Loop test has a "Segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When testing Embedding for 1000 times, only image-embedding-efficientnetb7 shows the problem as shown in the figure
test pipeline:image-embedding-efficientnetb7
test script:
 
  ```
 def test_embedding_more_times(self,pipeline_name):
       for i in range(1000):
            embedding_pipeline = pipeline(pipeline_name)
            try:
                embedding = embedding_pipeline(data_path + "towhee_test_image0.jpg")
            except Exception as e:
                print( f"Failed to embedding: {e}")
            print("--------",i)
       return True
```

<img width="446" alt="截屏2021-12-29 上午11 02 38" src="https://user-images.githubusercontent.com/34296482/147623474-32e1f2cf-a31b-4fcb-aa31-875269c43b63.png">

<img width="507" alt="截屏2021-12-28 下午5 43 56" src="https://user-images.githubusercontent.com/34296482/147623114-11dc26be-1370-42c2-ac8c-1e6291b8aa00.png">

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.4.0rc1
- OS(Ubuntu or CentOS):Ubuntu 18.04.5
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jingkl** [comment]
Modified the test script and the loop got stuck when testing
```
    def test_embedding_more_times(self,pipeline_name):

       embedding_pipeline = pipeline(pipeline_name)
       for i in range(1000):
            try:
                embedding = embedding_pipeline(data_path + "towhee_test_image0.jpg")
            except Exception as e:
                print(f"Failed to embedding: {e}")
            print("--------",i)

       return True
```
<img width="736" alt="截屏2021-12-29 上午11 39 33" src="https://user-images.githubusercontent.com/34296482/147625415-f0654366-95dc-4058-a9d7-c58ff863ef51.png">

**Comment by fzliu** [comment]
Which version of Ubuntu did you use? Is this only the case when running `image-embedding-efficientnetb7` or does this happen for other image embedding pipelines as well?

**Comment by jingkl** [comment]
> 你用的是哪个版本的 Ubuntu？仅在运行时`image-embedding-efficientnetb7`才会出现这种情况，还是其他图像嵌入管道也会出现这种情况？

Ubuntu 18.04.5, only image-embedding-efficientnetb7,All other pipelines are normal

**Comment by jingkl** [comment]
```
    def test_embedding_more_times(self,pipeline_name):

       embedding_pipeline = pipeline(pipeline_name)
       for i in range(1000):
            try:
                embedding = embedding_pipeline(data_path + "towhee_test_image0.jpg")
            except Exception as e:
                print(f"Failed to embedding: {e}")
            print("--------",i)

       return True
```
second time：
<img width="475" alt="截屏2021-12-29 下午2 25 16" src="https://user-images.githubusercontent.com/34296482/147633647-2a5143c6-b574-4336-aeda-7f792f5354dc.png">

**Comment by binbinlv** [comment]
Can not be reproduced steadily each time, so defer it.

**Comment by fzliu** [comment]
Please let us know the machine specifications and exact conditions with which this is error occurs (including if there are any other applications running simultaneously).
