### ISSUE TITLE
Could not find a version that satisfies the requirement towhee==0.4.0rc1

### ISSUE THREAD

**Issue by ThyeeZz** [towhee-io/towhee#376]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/41352919/147746977-245fd884-715f-48e7-b3a8-e7539b3cb066.png)
Could not find a version that satisfies the requirement towhee==0.4.0rc1 or rc2,

macOs, Interl chip, python 3.9.9 

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by Chiiizzzy** [comment]
It seems like an internet connection issue. I cannot reproduce the same error. Could you make sure your internet works fine and try again?

**Comment by ThyeeZz** [comment]
I have installed successfully with command 'sudo pip install ...'
