### ISSUE TITLE
[Bug]: 404 not found for the link on quick start page

### ISSUE THREAD

**Issue by jennyli-z** [towhee-io/towhee#379]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Click the link `here.` on https://docs.towhee.io/get-started/quick-start/
It shows 404 Not Found.

### Expected Behavior

It should show the right content.

### Steps To Reproduce

```markdown
1. Open https://docs.towhee.io/get-started/quick-start/
2. Click here, it will go https://docs.towhee.io/get-started/pipelines/image-embedding then find 404 Not found
```

### Environment

```markdown
- Chrome
```

**Comment by fzliu** [comment]
Fixed via https://github.com/towhee-io/towhee-docs/pull/108.
