### ISSUE TITLE
[Bug]: Typo in the overview

### ISSUE THREAD

**Issue by yhmo** [towhee-io/towhee#388]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In this page: https://docs.towhee.io/
This sentence: "as well as supporting data parallesim and resource management."
The "parallesim" should be "parallelism"

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by shiyu22** [comment]
Updated with [#122](https://github.com/towhee-io/towhee-docs/pull/122).
