### ISSUE TITLE
[Documentation]: Add tutorials

### ISSUE THREAD

**Issue by jaelgu** [towhee-io/towhee#389]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

Jupyter notebooks of tutorials in [docs.towhee.](https://docs.towhee.io/):

1. Image deduplication
2. Music recognition
3. Reverse image search

**Comment by shiyu22** [comment]
Add tutorial for reverse_image_search in notebook #387

**Comment by jaelgu** [comment]
Added tutorial for music recognition in notebook #386
