### ISSUE TITLE
[Enhancement]: In "Install Towhee from source" part, we should git checkout to a release tag after downloading source code.

### ISSUE THREAD

**Issue by JackLCL** [towhee-io/towhee#391]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

link: https://docs.towhee.io/get-started/install#install-towhee-from-source
Original：
$ git clone https://github.com/towhee-io/towhee.git
$ cd towhee
$ python setup.py install

my improvement:
$ git clone https://github.com/towhee-io/towhee.git
$ **git checkout 0.4.0**    # I want to add this command.
$ cd towhee
$ python setup.py install

### Why is this needed?

When I use the original steps to install towhee from the source, I will install a version in development rather than a stable release.

### Anything else?

N/A

**Comment by fzliu** [comment]
Our intention is to allow the user to download the latest (but perhaps not-so-greatest) Towhee code, i.e. the `main` branch.

**Comment by fzliu** [comment]
Fixed via https://github.com/towhee-io/towhee-docs/pull/132.
