### ISSUE TITLE
[Bug]: Broken link in website.

### ISSUE THREAD

**Issue by JackLCL** [towhee-io/towhee#392]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

link: https://docs.towhee.io/tutorials/music-recognition-system
![image](https://user-images.githubusercontent.com/53512883/148076016-ffa05bb8-bfa1-40eb-94d4-1009ba8db35d.png)

![image](https://user-images.githubusercontent.com/53512883/148076064-cb5743f4-170b-4b2d-b367-0d2f9495dc29.png)

### Expected Behavior

Jump to the normal page.

### Steps To Reproduce

```markdown
N/A
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

### Anything else?

N/A

**Comment by JackLCL** [comment]
Is it possible to do a bad link detection robot to detect daily whether there are bad links on the official website?

**Comment by jaelgu** [comment]
@JackLCL Broken links in tutorials are fixed: https://github.com/towhee-io/towhee-docs/pull/120

**Comment by jaelgu** [comment]
@JackLCL git action to auto-check urls: https://github.com/towhee-io/towhee-docs/pull/126
