### ISSUE TITLE
[Documentation]: Need more explanation to the figures

### ISSUE THREAD

**Issue by GuoRentong** [towhee-io/towhee#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

In Tutorial Overview:
'Normally an audio embedding pipeline generates a set of embeddings given an audio path, which composes a unique fingerprint representing the input music.'
We'd better introduce where does these embeddings come from.  In addition, we should explain the figures below.
For example
To explain how the music and snippet are divided into small pieces, how the embeddings are matched, and how do we get the final result via voting.

**Comment by jaelgu** [comment]
updated in https://github.com/towhee-io/towhee-docs/pull/125
