### ISSUE TITLE
[Documentation]: If absolute path is not specified, the quick start image location is not found

### ISSUE THREAD

**Issue by xiaofan-luan** [towhee-io/towhee#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

Read image towhee_logo.png failed
img_path = 'towhee_logo.png', should we just specify the image file location?
![image](https://user-images.githubusercontent.com/83447078/148155333-1bed6fe5-f81b-426f-94fd-8071451a0a9d.png)

**Comment by Chiiizzzy** [comment]
Please run `wget https://github.com/towhee-io/towhee-docs/raw/main/docs/get-started/towhee.jpeg` before running tutorial.

**Comment by xiaofan-luan** [comment]
sure,  I will try and fix it on readme

**Comment by fzliu** [comment]
Fixed (clarified) via https://github.com/towhee-io/towhee-docs/pull/132.
