### ISSUE TITLE
[Help Wanted]: Hit PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by xiaofan-luan** [towhee-io/towhee#400]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![image](https://user-images.githubusercontent.com/83447078/148158995-4d6d0ae2-5695-4fd5-a00a-9abc31dfd10d.png)

Anyone know how to fix this error? I run into this issue and this is the only log i found

### Expected Behavior

should  be working under my mac laptop.
Python 3.7

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by wxywb** [comment]
could you provide the version of PyTorch and the executed pipeline name?

**Comment by xiaofan-luan** [comment]
> could you provide the version of PyTorch and the executed pipeline name?

torch                         1.9.0
torchvision                   0.10.0

 executed pipeline name is image-embedding

**Comment by wxywb** [comment]
since the design of towhee has changed a lot from towhee v0.1.3, please uninstall it and then install the latest towhee(v0.4.0) and remove the cached pipelines and ops manually($HOME/.towhee/), and check whether this issue still remains.
