### ISSUE TITLE
[Bug]: hub.towhee.io is not accessible

### ISSUE THREAD

**Issue by filip-halt** [towhee-io/towhee#403]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

hub.towhee.io is only accessible if towhee.io has been visited and cached by the browser or if https:// is manually added to the start.

### Expected Behavior

With a cleaered cache and history, be able to access hub.towhee.io

### Environment

```markdown
- MacOS
- Safari
```

### Anything else?

This is probably due to the hub not accepting http requests and timing them out. Http requests should be redirected to https communication automatically.

**Comment by GuoRentong** [comment]
from Towhee v0.4, the contents of hub.towhee.io are moved to towhee.io

**Comment by fzliu** [comment]
`hub.towhee.io` and `towhee.io` (this one is preferred) are now effectively identical websites.
