### ISSUE TITLE
[Enhancement]: Better to unify the towhee version whether we install it by pip or conda

### ISSUE THREAD

**Issue by DragonDriver** [towhee-io/towhee#407]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

In the [Get Started page](https://docs.towhee.io/get-started/install), it introduced two ways to install towhee. However, it didn't specify the towhee's version when we want to install towhee by conda. I think it will be better if the doc can unify it.
By the way, generally towhee is very nice in my experience.

### Why is this needed?

Keep consistency to avoid useless explanation when users have problems with getting started with conda.

**Comment by fzliu** [comment]
> By the way, generally towhee is very nice in my experience.

Thanks! Glad you enjoyed using Towhee.

**Comment by fzliu** [comment]
Fixed via https://github.com/towhee-io/towhee-docs/pull/132.
