### ISSUE TITLE
[Enhancement]: How to embedding multiple pictures?

### ISSUE THREAD

**Issue by xiaocai2333** [towhee-io/towhee#408]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

embedding_pipeline supports passing in a list. 
```
img_path = ["aaa.png", "bbb.png"]
embedding = embedding_pipeline(img_path)
```
and the `embedding`  is a list of vectors.

### Why is this needed?

If you use other methods to support embedding multiple pictures, please tell me, thanks.

**Comment by junjiejiangjjj** [comment]
```python
# Do like this
img_path = ["aaa.png", "bbb.png"]
embeddings = []
for im in img_path:
    embeddings.append(embedding_pipeline(im))
```

**Comment by xiaocai2333** [comment]
> ```python
> # Do like this
> img_path = ["aaa.png", "bbb.png"]
> embeddings = []
> for im in img_path:
>     embeddings.append(embedding_pipeline(im))
> ```

ok, thanks
