### ISSUE TITLE
[Bug]: Incorrect script in music recognition tutorial

### ISSUE THREAD

**Issue by yhmo** [towhee-io/towhee#410]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In this page https://docs.towhee.io/tutorials/music-recognition-system, this script has two problems:

```
import numpy as np
import os
from pathlib import Path

dataset_path = './music_dataset/dataset'
music_list = [f for f in Path(dataset_path).glob('*')]
vec_sets = []

for audio_path in music_list:
    vecs = embedding_pipeline(str(audio_path))
    norm_vecs = [vec / np.linalg.norm(vec) for vec in vecs[0][0]]
    vec_sets.append(norm_vecs)
Loading model...
Model is loaded.
```

1. the path './music_dataset/dataset' doesn't exist. after unzip the file, the path is './music_dataset/music_dataset'
2. the 'Loading model...' and 'Model is loaded.' is invalid code, should be commented with "#", or use print() to print them.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jaelgu** [comment]
1. This is fixed in https://github.com/towhee-io/towhee-docs/pull/125 (gdown link is updated but this has not been merged yet.)
2. Fixed in https://github.com/towhee-io/towhee-docs/pull/130

**Comment by jaelgu** [comment]
@yhmo How do you download the test dataset? If using `gdown` from google cloud, the it should be "./music_dataset/dataset"
![image](https://user-images.githubusercontent.com/86251631/148344266-6a88f391-bdcc-4c77-a662-8a1b35139642.png)

**Comment by yhmo** [comment]
I just follow the music recognition tutorial, run this command to download:
`gdown 'https://drive.google.com/uc?id=1gHF8HDzXxeSy8bhtaTVueRFVPdj6ZEZJ'`

It seems the URL has been fixed, now it is correct.
5 hours ago I use the same command but download a file named "data.zip":
![Screenshot from 2022-01-06 15-58-49](https://user-images.githubusercontent.com/2282099/148349455-5f90345e-e5b0-4f41-bdaa-d5b7ed70f0fa.png)
