### ISSUE TITLE
[Bug]: image-embedding cannot process png image

### ISSUE THREAD

**Issue by congqixia** [towhee-io/towhee#413]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When trying example in [homepage example](https://github.com/towhee-io/towhee), png file cannot be loaded

### Expected Behavior

Png image loaded successfully or specify image support type

### Steps To Reproduce

```markdown
Use `image-embedding` on png image
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by yhmo** [comment]
Python cannot recognize "~/", you can use an absolute path.

This line will failed:
`img0_embedding = embedding_pipeline('~/Pictures/Selection_142.png')`
`RuntimeError: Read image ~/Pictures/Selection_142.png failed`

This line can work:
`img0_embedding = embedding_pipeline('/home/xxx/Pictures/Selection_142.png')`

**Comment by junjiejiangjjj** [comment]
Please remove ~/.towhee and retry, then it will update the pipeline. We will update the pipeline atomically in the future version.

**Comment by congqixia** [comment]
Found the problem: the png file was corrupted, I think the error message could be more clear

**Comment by fzliu** [comment]
> Found the problem: the png file was corrupted, I think the error message could be more clear

Ok, closing this issue. #347
