### ISSUE TITLE
[Bug]: Use git -sm to replace git -m for contributing guide

### ISSUE THREAD

**Issue by yhmo** [towhee-io/towhee#415]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In this page: https://docs.towhee.io/developer-guides/contributing/contributing-guide

We tell contributors to submit commit by this command:
`$ git commit -m "My awesome commit message"`

It is better to require a signature when submitting commit, according to github doc:
https://docs.github.com/en/authentication/managing-commit-signature-verification/about-commit-signature-verification

**Using GPG or S/MIME, you can sign tags and commits locally. These tags or commits are marked as verified on GitHub so other people can be confident that the changes come from a trusted source.**

The recommended way:
`$ git commit -s -m 'This is my commit message'`
or
`$ git commit -sm 'This is my commit message'`

More information:
https://dlorenc.medium.com/should-you-sign-git-commits-f068b07e1b1f

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by fzliu** [comment]
Fixed via https://github.com/towhee-io/towhee-docs/pull/132.
