### ISSUE TITLE
[Bug]: Typo in this page

### ISSUE THREAD

**Issue by yhmo** [towhee-io/towhee#419]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

In this page: https://docs.towhee.io/developer-guides/framework/hub-integration-and-caching

"ultimatey" should be "ultimately"
"seperate" should be "separate"

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by Chiiizzzy** [comment]
Fixed in https://github.com/towhee-io/towhee-docs/pull/131
