### ISSUE TITLE
[Enhancement]: Pre-load model without running the pipeline with an input

### ISSUE THREAD

**Issue by jaelgu** [towhee-io/towhee#423]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Add some option to pre-load models in the pipeline when I call the pipeline (but NOT run with an input to call operator)

### Why is this needed?

Here is the problem I got in building demo with multiple pipelines:

1. encode.py includes a function to use different pipelines
2. main.py uses encode.py to get embeddings with the pipeline name as an variable

When I run main.py, it will re-load models each time I switch pipelines. In order to pre-load models to save embedding time, it seems the only option now is running each pipeline&operator at the beginning of the main.py.

**Comment by fzliu** [comment]
> re-load models each time I switch pipelines

I do not quite understand the problem you're facing. You're saying that calling multiple pipelines will result in operators continuously being loaded and unloaded?

**Comment by jaelgu** [comment]
@fzliu Nvm, I just did a quick test and it turns out the script only loads model at the first time running pipeline. Switch pipeline doesn't unload model.
