### ISSUE TITLE
[Bug]:  404 found when click audio-embedding-vggish

### ISSUE THREAD

**Issue by jennyli-z** [towhee-io/towhee#427]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Click the link ` audio embedding ` on page https://hub.towhee.io/towhee/audio-embedding-vggish

it will go https://hub.towhee.io/towhee/audio-embedding-operator-template and show 404 

### Expected Behavior

show the contents instead of 404

### Steps To Reproduce

```markdown
Click the link ` audio embedding ` on page https://hub.towhee.io/towhee/audio-embedding-vggish
```

### Environment

```markdown
- Chrome
```

**Comment by jaelgu** [comment]
Updated README: https://towhee.io/towhee/audio-embedding-vggish
