### ISSUE TITLE
[Documentation]: How to contribute my pipeline for this project ?

### ISSUE THREAD

**Issue by saladcat** [towhee-io/towhee#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

How to contribute a custom pipeline for this project ?

**Comment by Chiiizzzy** [comment]
We will support user registration ASAP. We might be able to provide you a temporary user account if you are interested, please stay tuned.

**Comment by fzliu** [comment]
Thanks for your interest in Towhee! Although we're not yet at the stage where users can upload a pipeline all on their own, we'd love to communicate with you and provide support to allow you to do so.

Join the #support channel on our [Slack](https://slack.towhee.io) - we'll get you set up and walk you through the steps needed to contribute your pipeline.
