### ISSUE TITLE
[Enhancement]: Improve default pipelines

### ISSUE THREAD

**Issue by fzliu** [towhee-io/towhee#438]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

Towhee should maintain a list of along with a description for each default pipeline.
```
from towhee import pipeline
print(pipeline.list_pipelines())
print(pipeline.desc_pipeline(name))
```

**Comment by filip-halt** [comment]
Should we import reimport defaults on each runtime?

**Comment by fzliu** [comment]
Not sure what you mean - the default pipeline are hard-coded as a dict within `__init__.py`.
