### ISSUE TITLE
[Bug]: Run in parallel

### ISSUE THREAD

**Issue by Kencho5** [towhee-io/towhee#480]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i'm trying to run **embedding_pipeline()** function in parallel/async.
```python

for i in pool_inp:
    multiprocessing.Process(
        target=vectorize,
        args=(i,)
    ).run()

def vectorize(data):
    vec = embedding_pipeline(data)
    print(vec)
```
isn't this supposed to run in parallel? instead of it running 1 by 1.

using async version is ran 1 by 1 too, instead of all at once:
```python

async def main():
      vectorize_tasks = []
      for i in pool_inp:
          vectorize_tasks.append(vectorize(i))
      await asyncio.gather(*vectorize_tasks)

async def vectorize(data):
    vec = embedding_pipeline(data)
    print(vec)

if __name__ == '__main__':
    asyncio.run(main())
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): latest
- OS(Ubuntu or CentOS): Ubuntu
- CPU/Memory: i7 9700k/16gb
- GPU: gtx 1080
```

**Comment by fzliu** [comment]
For your first example multiprocessing-based code snippet, it seems you've instantiated only a single `embedding_pipeline` for use across all processes, which will not result in parallelization. With that being said, you should see minimal speedup with multiple processes since Towhee already utilizes multiple cores during embedding computation.

I would avoid using `asyncio` with Towhee.

@junjiejiangjjj Can you confirm?

**Comment by Kencho5** [comment]
```python
for i in pool_inp:
    multiprocessing.Process(
        target=vectorize,
        args=(i,)
    ).run()

def vectorize(data):
    embedding_pipeline = pipeline('image-encoding')
    vec = embedding_pipeline(data)
    print(vec)
```
so would this be correct? also, each image takes 0.04 seconds to convert into vectors, but it takes the script to finish converting 10 images around 1.1 seconds which is not the way it's supposed to be if ran in parallel

**Comment by filip-halt** [comment]
> so would this be correct? also, each image takes 0.04 seconds to convert into vectors, but it takes the script to finish converting 10 images around 1.1 seconds which is not the way it's supposed to be if ran in parallel

How did you test the time for converting each image into vectors? When I run my test code (at the bottom), the two are pretty close but the multi-processed solution is slower. It's expected to be slower as the process is already multithreaded. With the simple pipeline I believe that multiprocessing will add more overhead as the image_embedding pipeline isn't a calculation heavy application, so more time will be wasted setting up the processes and loading the pipeline than saved by running multiple towhee instances at once.

```python
import time
import multiprocessing

from towhee import pipeline

img_path = 'path/to/image'

def test_1(num):
    embedding_pipeline_solo = pipeline('image-encoding')
    for _ in range(num):
        embedding_pipeline_solo(img_path)


def vectorize(data):
    embedding_pipeline = pipeline('image-encoding')
    embedding_pipeline(data)

def test_2(num):
    processes = []
    for _ in range(num):
        p = multiprocessing.Process(
            target=vectorize,
            args=(img_path,)
        )
        processes.append(p)
        p.start()

    for x in processes:
        x.join()


if __name__ == "__main__":
    start = time.time()
    test_1(20)
    end = time.time() - start
    print('Single Pipeline:', end)

    start = time.time()
    test_2(20)
    end = time.time() - start
    print('Multiprocessed:', end)



```

**Comment by junjiejiangjjj** [comment]
Towhee's `engine` is a singleton, and can not run in parallel currently, so, in one process, the pipeline only can run one by one.
But in multiprocess, the pipeline can run in parallel.

```python
import time
import multiprocessing

from towhee import pipeline

img_path = '/Users/jiangjunjie/WorkSpace/images/1.png'


COUNT = 100


def vectorize(data, count):
    embedding_pipeline = pipeline('image-encoding')
    for i in range(count):
        embedding_pipeline(data)


def test_in_multiprcess(num):
    processes = []
    for _ in range(num):
        p = multiprocessing.Process(
            target=vectorize,
            args=(img_path, COUNT // num)
        )
        processes.append(p)
        p.start()

    for x in processes:
        x.join()


if __name__ == "__main__":

    start = time.time()
    test_in_multiprcess(1)
    end = time.time() - start
    print('One process:', end)

    start = time.time()
    test_in_multiprcess(2)
    end = time.time() - start
    print('Two process:', end)
```

![image](https://user-images.githubusercontent.com/14136703/149864519-f8c6ec61-45c8-4d82-94d7-3dfb07467c63.png)

**Comment by junjiejiangjjj** [comment]
We will support pipeline parallelism after Towhee v0.5

**Comment by Kencho5** [comment]
i see. i need parallelism because of the scale that i'm given. i'm trying to transform 170 million 32x32 images into vectors. currently one conversion takes 0.04 seconds and if we could pair it up with multiprocessing it'd be amazing. is there an estimate of when Towhee v0.5 is coming out?

**Comment by fzliu** [comment]
We hope to release v0.5 mid-February. If you have 140 million images, it's probably best to do something distributed - are you limited to a single machine?

**Comment by Kencho5** [comment]
well, kinda yeah and using multiprocessing would speed up things so much that there wouldn’t even be a need to use multiple machines. do you know any other ways to transform images into vectors that support parallelism to search near duplicate images in milvus after?

**Comment by fzliu** [comment]
If you have a GPU, you can try running batching your input images and running the models in Pytorch/Tensorflow. That should result in a pretty hefty speedup.

**Comment by Kencho5** [comment]
i don’t understand what you mean in: “ running batching your input images”. and if you could estimate, what speeds would we be getting? i’ve got a gtx 1080
