### ISSUE TITLE
[Bug]: operator dependency not stable

### ISSUE THREAD

**Issue by reiase** [towhee-io/towhee#512]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

op_a requires numpy==1.19.5
op_a requires numpy==1.20.1

when running a pipeline that uses both op_a and op_b, towhee will switch NumPy version during pipeline running.

### Expected Behavior

NumPy version should be determined by pip. For example:
```
op_a requires numpy==1.19.5
op_a requires numpy==1.20.1
```
op_a and op_b are not compatible with each other, for depending on incompatible numpy version.
```
op_a requires numpy>1.19.5
op_a requires numpy==1.20.1
```
op_a and op_b are compatible with each other, and pip will install numpy==1.20.1.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by reiase** [comment]
pip check can verify installed packages have compatible dependencies:
```shell
pip check
```

**Comment by fzliu** [comment]
The easy solution here would be to modify all operators to use '>=' instead of '=='.

**Comment by reiase** [comment]
> The easy solution here would be to modify all operators to use '>=' instead of '=='.

towhee can not detect dependency conflicts, we should add some check before pipeline running
