### ISSUE TITLE
[DesignProposal]: Run Operator with towhee.op()

### ISSUE THREAD

**Issue by shiyu22** [towhee-io/towhee#526]
### Background and Motivation

There is no way to run op in Towhee directly, so should run Operator with towhee.op() like towhee.pipeline().

### Design

- Run op in hub or local file
```python
from towhee import op

resnet_op = op(operator_src='resnet-image-embedding', init_args={'model_name': 'resnet50'}, tag='main') # tag defaults to 'main'
result = resnet_op(call_args='{image_path': './test.png'})
```
- Run op with class(notebook)
```python
from towhee import op

resnet_op = op(operator_class='ResnetImageEmbedding', init_args={'model_name': 'resnet50'})
result = resnet_op(call_args='{image_path': './test.png'})
```

### Pros and Cons

- Users can run op in hub directly.
- Develop can test op with towhee.op() instead of run their local class file.
- Support to run and test op in notebook directly.

**Comment by reiase** [comment]
It will be much simpler if we drop the metaprogramming tricks:
```python
resnet_op = op(operator_class='ResnetImageEmbedding', model_name=resnet50)
result = resnet_op(image_path ='./test.png')
```

**Comment by shiyu22** [comment]
> metaprogramming tricks:

maybe need to refer to the API [towhee.pipeline()](https://github.com/towhee-io/towhee/blob/main/towhee/__init__.py#L75)
```python 
def pipeline(pipeline_src: str, tag: str = 'main', install_reqs: bool = True):
```

**Comment by reiase** [comment]
> > metaprogramming tricks:
> 
> maybe need to refer to the API [towhee.pipeline()](https://github.com/towhee-io/towhee/blob/main/towhee/__init__.py#L75)
> 
> ```python
> def pipeline(pipeline_src: str, tag: str = 'main', install_reqs: bool = True):
> ```
It's better to have an API `towhee.operator` that aligns with `towhee.pipeline`, but make `towhee.op` a syntax sugar for convenience.

**Comment by shiyu22** [comment]
Done with #549
