### ISSUE TITLE
[Bug]: del pipeline does not free up memory

### ISSUE THREAD

**Issue by filip-halt** [towhee-io/towhee#538]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running multiple pipelines, calling `del pipeline` doesn't remove the loaded in operators from memory. This is due to the fact that operators are cached during runtime for reuse. One possible way to get around it would be to keep a list of all the pipelines and which operators they use. When a pipeline is deleted, we crosscheck all its operators to see which ones arent being used anymore and we delete them to free up memory. 

### Expected Behavior

When deleting a pipeline, delete its operators aswell.

### Steps To Reproduce

```markdown
p = pipeline()
del p
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): main branch
- OS(Ubuntu or CentOS): macos
- CPU/Memory: i7, 32gb
- GPU: none
- Others:
```

**Comment by junjiejiangjjj** [comment]
Currently, we cache all the operators which the pipeline used in memory until the program stopped, we may optimize the cache logic in the future version.

**Comment by filip-halt** [comment]
yep, might be worth doing some kind of operator -> pipeline dependecy map and remove the operators that are safe to remove when a pipeline is deleted.

**Comment by anfeirr** [comment]
this bug is very critical , hope optimized version coming soon
