### ISSUE TITLE
[DesignProposal]: Towhee CMD

### ISSUE THREAD

**Issue by reiase** [towhee-io/towhee#554]
### Background and Motivation

1. better-organized towhee cmd;
2. complete workflow for:
    1. execute pipeline from cmdline;
    2. develop op/pipeline;
    3. publish op/pipeline to hub;

### Design

```shell
$ towhee execute <some pipeline>
$ towhee execute -i <some dataset> -o <new dataset> <some pipeline>
$ towhee install <path for some operator> # install the operator to venv
$ towhee develop <path for some operator> # link the operator to venv for development
$ towhee clone <operator name> # clone operator code from hub
$ towhee push <path for some operator> # publish an operator
$ towhee pull <path for some operator> # sync operator code with hub

$towhee train -i <some dataset> <some operator>
$towhee train -i <some dataset> <some operator>@<some pipeline>
```

### Anything else? (Additional Context)

1. `towhee develop` sounds strange, needs a better name;
2. detail user interface design;

**Comment by shiyu22** [comment]
I think the commands related to git(clone/push/pull) should be ignored and use `git command` directly. In addition, `towhee login/logout` can be developed to push the trained model.
