### ISSUE TITLE
[Bug]:  Other pipeline can't be used

### ISSUE THREAD

**Issue by annisun2020** [towhee-io/towhee#588]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

i wan't use image-embedding-vgg16-bn pipeline, it can't work.

def __init__(self):
     self.embedding_pipeline = pipeline('towhee/image-embedding-vgg16-bn')

i have got this error message:
![image](https://user-images.githubusercontent.com/68275306/153527389-4c410bb8-24b4-44d9-a392-2f053fe6d28a.png)

**Comment by annisun2020** [comment]
why only default pipeline is ok , other pipeline not work

**Comment by shiyu22** [comment]
Which version of towhee are you using? 

When I tried to reproduce it. I can get the [pipeline](https://towhee.io/towhee/image-embedding-vgg16-bn) with towhee0.4.0 but get the error to run with img:
```bash
File "~/.towhee/operators/image_decoder&towhee$main/image_decoder.py", line 5, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
from timm.data.transforms_factory import create_transform
ModuleNotFoundError: No module named 'timm'
```
I think that @filip-halt has lost the requirements.txt in [operator](https://towhee.io/towhee/timm-image-embedding).

**Comment by annisun2020** [comment]
> 

0.2.0

**Comment by annisun2020** [comment]
i update the version to 0.4.0 , it works

**Comment by filip-halt** [comment]
Woops, recently transfered the timm operator to towhee account. Good catch. Let me change it real quick.

**Comment by filip-halt** [comment]
Yes, being that towhee is still in its early stages, we made quite a few changes between 0.2 and 0.4 in regards to the hub, so if you can update towhee the issue should be resolved. @annisun2020

**Comment by annisun2020** [comment]
I have update version to 0.4.0 , but get this error message

2022-02-11 11:02:38,919 - 123145528213504 - runner_base.py-runner_base:133 - ERROR: image_decoder:0 runs failed, error msg: startswith, Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/towhee/engine/operator_runner/runner_base.py", line 160, in _call_op
    outputs = self._op(**inputs)
  File "/Users/liyan/.towhee/operators/image_decoder&towhee$main/image_decoder.py", line 36, in __call__
    if image_path.startswith('http'):
  File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 546, in __getattr__
    raise AttributeError(name)
AttributeError: startswith

**Comment by junjiejiangjjj** [comment]
> I have update version to 0.4.0 , but get this error message
> 
> 2022-02-11 11:02:38,919 - 123145528213504 - runner_base.py-runner_base:133 - ERROR: image_decoder:0 runs failed, error msg: startswith, Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/towhee/engine/operator_runner/runner_base.py", line 160, in _call_op outputs = self._op(**inputs) File "/Users/liyan/.towhee/operators/image_decoder&towhee$main/image_decoder.py", line 36, in **call** if image_path.startswith('http'): File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 546, in **getattr** raise AttributeError(name) AttributeError: startswith

The input must be an image path, it could be a local path or  HTTP URL, not a PIL image.

**Comment by annisun2020** [comment]
> > I have update version to 0.4.0 , but get this error message
> > 2022-02-11 11:02:38,919 - 123145528213504 - runner_base.py-runner_base:133 - ERROR: image_decoder:0 runs failed, error msg: startswith, Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/towhee/engine/operator_runner/runner_base.py", line 160, in _call_op outputs = self._op(**inputs) File "/Users/liyan/.towhee/operators/image_decoder&towhee$main/image_decoder.py", line 36, in **call** if image_path.startswith('http'): File "/usr/local/lib/python3.9/site-packages/PIL/Image.py", line 546, in **getattr** raise AttributeError(name) AttributeError: startswith
> 
> The input must be an image path, it could be a local path or HTTP URL, not a PIL image.

I have change to image path, it works ,thanks

**Comment by shiyu22** [comment]
Hi @annisun2020, would you like to join [towhee slack](https://join.slack.com/t/towheeio/shared_invite/zt-xfdg6n8k-0OImXaHHpzSxiAOj~wTVQw) where people can discuss anything about towhee.
