### ISSUE TITLE
[DesignProposal]: face Blur pipeline

### ISSUE THREAD

**Issue by krishnakatyal** [towhee-io/towhee#665]
### Background and Motivation

A pipeline that  blur the face from an digital image 

### Design

To make an towhee pipeline that wraps around opencv face blur

### Pros and Cons

Pro: Helpful in privacy protection

### Anything else? (Additional Context)

Helpful  links
https://towhee.io/towhee/face-detection-insightface
https://www.geeksforgeeks.org/how-to-blur-faces-in-images-using-opencv-in-python/
https://towhee.io/towhee/retinaface-face-detection

**Comment by krishnakatyal** [comment]
@fzliu kindly assign the label good first issue(Gsoc 2022 purpose)

**Comment by snnipetr** [comment]
Hello I would like to take up this issue for contribution.

**Comment by gaurav879** [comment]
if it is available I would like to work on it.

**Comment by snnipetr** [comment]
Hello @gaurav879 I am working on this issue currently.

**Comment by AniTho** [comment]
If it's available then I would like to work on this issue
