### ISSUE TITLE
[DesignProposal]: Add pipeline that help in text summarisation

### ISSUE THREAD

**Issue by krishnakatyal** [towhee-io/towhee#669]
### Background and Motivation

An pipeline that take the string as input and then returns the summarised version of the same

### Design

Input : String
Output : Vector

start_vector-->summarisation operator-->end_operator

### Anything else? (Additional Context)

https://www.machinelearningplus.com/nlp/text-summarization-approaches-nlp-example/
https://towardsdatascience.com/introduction-to-word-embedding-and-word2vec-652d0c2060fa
https://towardsdatascience.com/word-to-vectors-natural-language-processing-b253dd0b0817

**Comment by krishnakatyal** [comment]
@fzliu  mark as good first issue

**Comment by gaurav879** [comment]
I would like to try.

**Comment by jaelgu** [comment]
To anyone's going to work on this issue, you may try this out: [Towhee nlp-embedding pipelines](https://towhee.io/pipelines?limit=30&page=1&filter=3%3Anlp-embedding) collects and implements most popular nlp Transformers from Huggingface for text embedding.

**Comment by Gaurav7888** [comment]
@krishnakatyal  I have already created the operator for this, now I am going for the pipeline.
