### ISSUE TITLE
[Bug]: Pipeline "towhee/audio-embedding-hubert-asr-xlarge"  when embedding an audio too slowly

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#698]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior
It takes at least half an hour to download the model, and the embedding time last  12s

```
Testing test_embedding_more_times:towhee/audio-embedding-hubert-asr-xlarge
Downloading: "https://download.pytorch.org/torchaudio/models/hubert_fairseq_xlarge_ll60k_asr_ls960.pth" to /Users/jingjing/.cache/torch/hub/checkpoints/hubert_fairseq_xlarge_ll60k_asr_ls960.pth
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.59G/3.59G [12:20<00:00, 5.20MB/s]
embedding audios for 1 round 22.010681867599487
embedding audios for 2 round 12.850822925567627
embedding audios for 3 round 12.820360898971558
embedding audios for 4 round 13.374897003173828
embedding audios for 5 round 14.243759870529175
embedding audios for 6 round 14.030519962310791
embedding audios for 7 round 14.154222965240479
embedding audios for 8 round 14.750566720962524
embedding audios for 9 round 13.149310827255249
embedding audios for 10 round 12.697602033615112
embedding audios for 11 round 13.255967855453491
embedding audios for 12 round 14.431485891342163
embedding audios for 13 round 14.436625242233276
embedding audios for 14 round 13.039997100830078
embedding audios for 15 round 12.660359144210815
embedding audios for 16 round 12.54392385482788
embedding audios for 17 round 12.476114749908447
embedding audios for 18 round 12.496373891830444
embedding audios for 19 round 12.447263956069946
embedding audios for 20 round 12.532696008682251
```

### Expected Behavior

Embedding  Fast

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.4.1dev87
- OS(Ubuntu or CentOS):macos
- CPU/Memory:
- GPU:
- Others:
```

**Comment by fzliu** [comment]
What is the length of the audio file that you are using? This is a 3.5GB model so it's normal to have long runtimes.

**Comment by jingkl** [comment]
> What is the length of the audio file that you are using? This is a 3.5GB model so it's normal to have long runtimes.

442k，1000 vectors embedding  need to  4 hours

**Comment by fzliu** [comment]
442k samples? What's the unit here.

**Comment by jingkl** [comment]
> 442k samples? What's the unit here.

kb

**Comment by fzliu** [comment]
This is normal since such a long audio file will have multiple embeddings.

**Comment by fzliu** [comment]
The recommendation here is to either use a shorter audio file or to reduce the number of runs.

**Comment by binbinlv** [comment]
<img width="1440" alt="origin_img_v2_1ed60ea3-656b-42ea-b088-942be0f572eg" src="https://user-images.githubusercontent.com/83755740/155651327-24df9e16-7079-4d4f-b8a2-08c2d1d6cfe0.png">

@fzliu 
The first two running costs more than 1200s, is it normal?

**Comment by binbinlv** [comment]
> The recommendation here is to either use a shorter audio file or to reduce the number of runs.

@fzliu 
an audio 442k is big in AI field?

From normal respective, 442k is not a big file I think.

**Comment by fzliu** [comment]
Convolutional models require fixed-length inputs. This pipeline does this by splitting the input audio file into multiple audio segments. In general, an audio segment is extremely short; this means that long audio files can require as many as hundreds of subsegments.

In addition, HuBERT models are transformer-based, which are known for having long runtimes. The one used here (x-large) has nearly 1 billion parameters. Combine all of these factors together and you get long runtimes for each audio snippet.

So the answer to your question is yes, 442k (~0.5MB) is very big.

**Comment by jingkl** [comment]
Testing test_embedding_more_times:towhee/audio-embedding-wav2vec2-asr-large-10m
```
embedding audios for 1 round 615.8760628700256
embedding audios for 2 round 5.632572889328003
embedding audios for 3 round 5.596276044845581
embedding audios for 4 round 5.384315729141235
embedding audios for 5 round 5.037677049636841
embedding audios for 6 round 5.049297094345093
embedding audios for 7 round 5.070215225219727
embedding audios for 8 round 5.142498970031738
embedding audios for 9 round 5.130724906921387
embedding audios for 10 round 5.033764123916626
embedding audios for 11 round 4.938369989395142
embedding audios for 12 round 5.11371111869812
embedding audios for 13 round 5.091061115264893
embedding audios for 14 round 5.090001821517944
embedding audios for 15 round 5.065070152282715
embedding audios for 16 round 6.457149982452393
embedding audios for 17 round 5.702432155609131
embedding audios for 18 round 4.835651159286499
embedding audios for 19 round 6.302109956741333
embedding audios for 20 round 15.081677913665771
embedding audios for 21 round 4.813914060592651
embedding audios for 22 round 4.8724448680877686
embedding audios for 23 round 4.787246942520142
embedding audios for 24 round 4.801171064376831
embedding audios for 25 round 4.793724060058594
embedding audios for 26 round 4.809042930603027
embedding audios for 27 round 879.5525782108307
embedding audios for 28 round 5.218812942504883
embedding audios for 29 round 5.499580144882202
embedding audios for 30 round 5.650732040405273
```
@fzliu  What is the reason for the big difference in embedding time, some 5s and some 800s
