### ISSUE TITLE
[Bug]: Model is not re-downloaded automatically when the model download failed, which would leads to towhee crash

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#728]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

The image pipeline fails to download the model automatically

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by jingkl** [comment]
@fzliu

**Comment by binbinlv** [comment]
/assign @fzliu 

Could you please help to assign to who could fix this?

**Comment by binbinlv** [comment]
@jingkl 

I think the title is better to be "Model is not re-downloaded automatically when the model download failed, which would leads to towhee crash"

**Comment by binbinlv** [comment]
this issue is from #653

**Comment by oneseer** [comment]
Timm does not re-download model is net connection is not ok. This issue is beyond towhee.

**Comment by binbinlv** [comment]
Are there any way to handle this scenario?

And at least crash should be stoped and reporting an error like "download fail, please clear *** and try again"?

**Comment by jingkl** [comment]
keep it open
