### ISSUE TITLE
[Bug]: towhee installs its tests to the `site-packages` path

### ISSUE THREAD

**Issue by reiase** [towhee-io/towhee#740]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

when installing towhee with `python setup.py install`, it also installs unit tests into the `site-packages` path.

### Expected Behavior

the tests files and packages should be ignored during install.

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by reiase** [comment]
The released package on pypi is around 42M, which also includes tests and docs. @binbinlv @Chiiizzzy

**Comment by binbinlv** [comment]
assign @Chiiizzzy
