### ISSUE TITLE
[Bug]: towhee/inceptionresnetv1-face-embedding has no requirements

### ISSUE THREAD

**Issue by krishnakatyal** [towhee-io/towhee#746]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

have to manually install the requirements

### Expected Behavior

automatically download

### Steps To Reproduce

```markdown
from towhee import pipeline

embedding_pipeline = pipeline('towhee/face-embedding-retinaface-inceptionresnetv1')
embedding = embedding_pipeline('face.jpeg')
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.4
- OS(Ubuntu or CentOS):colab 
- CPU/Memory:
- GPU:
- Others:
```

**Comment by wxywb** [comment]
@krishnakatyal ,hi, Krishna, I uploaded this pipeline and I will add the requirement.

**Comment by wxywb** [comment]
requirement has been added.
