### ISSUE TITLE
Quick start

### ISSUE THREAD

**Issue by rebel2019** [towhee-io/towhee#796]
![image](https://user-images.githubusercontent.com/53045945/157633703-b7b9fd19-96b1-471a-8484-73a8e2f1e467.png)
use local path cause error as :
![image](https://user-images.githubusercontent.com/53045945/157633846-5dbf0794-e775-4e6f-a003-19620d134670.png)

**Comment by rebel2019** [comment]
![image](https://user-images.githubusercontent.com/53045945/157634528-3933c454-0956-4443-ae36-ffeda04ab610.png)
there is  not path https://github.com/towhee-io/towhee-docs/raw/main/docs/get-started/towhee.jpeg

**Comment by fzliu** [comment]
#811 This should fix the second issue.

**Comment by fzliu** [comment]
> ![image](https://user-images.githubusercontent.com/53045945/157633703-b7b9fd19-96b1-471a-8484-73a8e2f1e467.png) use local path cause error as : ![image](https://user-images.githubusercontent.com/53045945/157633846-5dbf0794-e775-4e6f-a003-19620d134670.png)

I just tried it and it seems to work for me. What version of `towhee` are you using and can you paste the full exception log?

**Comment by soulteary** [comment]
I tried running towhee in docker over the weekend, and it looked fine, both local and network images could be parsed smoothly.

If anyone needs it, I can organize and share how I run the project in the docker, I believe it can reduce many unnecessary running problems caused by environmental differences and network problems.

**Comment by omartarek206** [comment]
> I tried running towhee in docker over the weekend, and it looked fine, both local and network images could be parsed smoothly.
> 
> If anyone needs it, I can organize and share how I run the project in the docker, I believe it can reduce many unnecessary running problems caused by environmental differences and network problems.

Hello @soulteary, if you can still share it it would be great.
