### ISSUE TITLE
[DesignProposal]: Auto-Batching in towhee pipeline inference.

### ISSUE THREAD

**Issue by wxywb** [towhee-io/towhee#801]
### Background and Motivation

Modern machine learning framework(e.g. PyTorch, Tensorflow) could utilize batch inferencing to improve the throughout. While towhee only support inference the data sequentially, leads to a lower GPU occupancy, we need to add batch inferencing to increase the throughout when we need inference a bunch of data.

### Design

Generally batch mode would consider in two situations.

#### 1 inference a list of data
```python
ppl = pipeline('image-embedding')
outs = ppl(['1.jpg','2.jpg','3.jpg'])
```

#### 2 inference several data in a period
```python
results = []

def callback(output):
  lock()
  results.append(output)

ppl = pipeline('image-embedding')
with ppl.batch_inference(max_latency=100, max_batch_size=4,callback):  
  for i in range(10000):
     ppl('{}.jpg'.format(i))
```

**Comment by toncho11** [comment]
Maybe this is related to my problem #805

**Comment by wxywb** [comment]
@toncho11, hi, this issue is a design for inference a batch of data in an efficient way and not implemented yet. It seems that you encounter a bug after thousands single-inferencing from a large dataset. Filip has been working on your issue and we will check out what happened :)

**Comment by reiase** [comment]
```python
with ppl.batch_inference(max_latency=100, max_batch_size=4,callback):  
  for i in range(10000):
     ppl('{}.jpg'.format(i))
```
How to get pipeline output?

**Comment by wxywb** [comment]
@reiase , there is a callback which should handle how to deal with the output data.

**Comment by junjiejiangjjj** [comment]
`Auto-batch` will not change the interface of `pipeline`, it is an internal feature to improve the model performance.
