### ISSUE TITLE
[Bug]: IndexError

### ISSUE THREAD

**Issue by toncho11** [towhee-io/towhee#805]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Hi,

I am getting error here:

```
 File "C:\Work\python38\lib\site-packages\towhee\__init__.py", line 77, in __call__
    return format_handler(out_df)

  File "C:\Work\python38\lib\site-packages\towhee\pipeline_format.py", line 48, in __call__
    data = next(it)

  File "C:\Work\python38\lib\site-packages\towhee\dataframe\iterators.py", line 107, in __next__
    raise IndexError
```

This happens when I process a lot of images one by one with:

`embedding = embedding_pipeline(file_path)`

After 4500 images it gives this error and before that it is OK. I do not think it is a memroy issue. I still have free memory left on my 16GB system. 

### Expected Behavior

Generate a correct embedding without error. 

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 0.5.0
- OS(Ubuntu or CentOS): Windows
- CPU/Memory: Core I7, 16GB
- GPU:
- Others:
```

**Comment by filip-halt** [comment]
Any chance I can get the full pipeline details?

**Comment by toncho11** [comment]
Yes. This is how I use it:

```
    images_loaded = 0
    embedding_pipeline = pipeline('image-embedding')
    for filename in os.listdir(folder):
        if filename.endswith(".jpeg"): 
            
            #print(os.path.join(folder, filename))
            base_name = os.path.basename(filename)
            
            parts = base_name.split("_")
            #print(parts)
            label = int(parts[4].split(".")[0])
            subject = int(parts[1])
            #print("Subject: ", subject, " Label: ", label)
            
            if (subject < n_max_subjects):

                if (label == 0 and samples_class1[subject] < n_max_samples) or (label == 1 and samples_class2[subject] < n_max_samples):
                    
                    images_loaded = images_loaded + 1
                    file_path = os.path.join(folder, filename)
                    print(file_path)

                    if label == 0:
                        samples_class1[subject] = samples_class1[subject] + 1
                    elif label == 1:
                        samples_class2[subject] = samples_class2[subject] + 1

                    embedding = embedding_pipeline(file_path)
                    
                    #print(embedding[0])

                    epochs_all_subjects.append(embedding[0])

                    label_all_subjects.append(label)
                    
                    
                    print(images_loaded)
            
        else:
            continue
```

**Comment by filip-halt** [comment]
Hey, just wanted to give you a quick update. I found out where the error is coming from and need a little bit of time to figure out what the best fix would be. Thanks for the great catch! Turns out this error can happen at any time and is up to chance of when two threads run in different order.

**Comment by filip-halt** [comment]
@junjiejiangjjj This error is coming from the fact that we are creating the final df reader in OutputFormat (pipeline_format.py). Because the map iterator is created outside of the graph_context, we break the guarantee that all iterators/readers that will exist are created at graph_context creation. This in turn causes garbage collection to sometimes delete the output data before the iterator can access it as it sees that there are no iterators currently reading its data.

**Comment by toncho11** [comment]
Hi,

I installed your fork with your potential fix. Unfortunately it did not work. 
One temporary solution is not to trigger the garbage collector, right? I will try to free at maximum my RAM. 
Would doing things in batches will help?

**Comment by filip-halt** [comment]
> Hi,
> 
> Your fix did work one time.

Is it failing the other times? I wasn't able to trigger the problem after 10,000 images while before it was triggering within 1200.
