### ISSUE TITLE
[Feature]: towhee has golang sdk ?

### ISSUE THREAD

**Issue by zhuyaguang** [towhee-io/towhee#845]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

towhee has golang sdk ?

**Comment by fzliu** [comment]
Not yet, we probably won't have bindings for other languages for a while, but you can always call a pipeline using the Towhee command line tool: https://github.com/towhee-io/towhee/tree/main/towhee/command.

As always, contributions are welcome.
