### ISSUE TITLE
[Feature]: API for the animegan pipeline

### ISSUE THREAD

**Issue by krishnakatyal** [towhee-io/towhee#851]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

The first phase of this project involves building a single-instance version of the API.

### Describe the solution you'd like.

An Api ( Fastapi based) for animeGan pipeline

**Comment by AniTho** [comment]
I can take this issue, if possible.

**Comment by GuoRentong** [comment]
> I can take this issue, if possible.

please join our slack for detail discussion :)

**Comment by GuoRentong** [comment]
> I can take this issue, if possible.
Hi, Ani
Thanks for taking this issue! We are planning to make an image style translation demo, and #851 is closely related to this work. If you are interested in developing this fancy demo, please find RT Guo, Frank, or Shiyu on our slack, so that we can discuss the details.

**Comment by harsh2ai** [comment]
Is this issue still open? I would like to contribute to this as well

**Comment by krishnakatyal** [comment]
> Is this issue still open? I would like to contribute to this as well

Hello harsh kindly join our slack https://slack.towhee.io/

**Comment by shiyu22** [comment]
@harsh2ai Hi, I think Aniket has submitted a PR #1065 for it, maybe you can take another GFI.
