### ISSUE TITLE
[Enhancement]: Automatically load latest pipelines and operators from hub

### ISSUE THREAD

**Issue by fzliu** [towhee-io/towhee#867]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

The most up-to-date pipelines and operators should be loaded from hub automatically, if `tag: main` is specified.

### Why is this needed?

This allows users to automatically keep up-to-date with pipeline and operator versions without needing to delete the `~/.towhee` folder manually. This also has the side-effect of making debugging significantly easier.

**Comment by reiase** [comment]
This behavior should not be the default, for loading operators and pipelines from the hub every time may cause some trouble if the user is running towhee in their production environment.

I think we can use a `tag: latest` for operators and pipelines that we want to reload automatically.  And there should be an offline-mode/online-mode switcher that enables the automatical reloading.

**Comment by fzliu** [comment]
If the user does not wish to automatically pull the latest pipelines/operators from the hub, they should specify `tag: <commit_id>` or something of the sort. `tag: main` implies that they want to use the latest.
