### ISSUE TITLE
[Bug]: git-lfs stored files incorrect download on colab without git-lfs installed

### ISSUE THREAD

**Issue by filip-halt** [towhee-io/towhee#876]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Using towhee on google colab notebook without git-lfs installed and setuo causes errors due to towhee downloading the pointer lfs file instead of the file being pointed to. 

### Expected Behavior

Downloading without lfs should still work. 

### Steps To Reproduce

```markdown
https://colab.research.google.com/drive/1E4UtJZYNwvOgWgN7LDNXS27bwQVwhlBD?usp=sharing

Removing the lfs install step in first cell will cause issue.
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by shiyu22** [comment]
Because of the large files are downloading with git-lfs. 

I think we can report an error when git-lfs is not installed on the system, which means that git-lfs needs to be installed before using towhee hub.
