### ISSUE TITLE
[Bug]:  test_develop UT failed

### ISSUE THREAD

**Issue by junjiejiangjjj** [towhee-io/towhee#877]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![jl0L35swkg](https://user-images.githubusercontent.com/14136703/159411600-cd1d0468-69ad-40a9-b8df-2f64089eb77c.png)
Run UT failed

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93): 
- OS(Ubuntu or CentOS):
- CPU/Memory:
- GPU:
- Others:
```

**Comment by reiase** [comment]
The test try  to create an egg-link in the site-package path, which the user has no writing permission.

1. towhee develop should support creating the link in user's path instread of system path;
2. the unittest should use user's path by default;
