### ISSUE TITLE
[Bug]: Found a documentation error about get started

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#888]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://towhee.readthedocs.io/en/main/data_collection/get_started.html

The second line of the code in the figure is formatted incorrectly, causing the code not to take effect
<img width="787" alt="截屏2022-03-22 18 47 03" src="https://user-images.githubusercontent.com/34296482/159465171-dcf94ce0-8983-4aa9-a987-0f20b6aceb05.png">

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.5.1.dev69
- OS(Ubuntu or CentOS):macos
- CPU/Memory:
- GPU:
- Others:
```

**Comment by binbinlv** [comment]
Reopen for verification.
@jingkl

**Comment by jingkl** [comment]
Not fixed, I think this example still lacks reliance
`from towhee import param_scope`
