### ISSUE TITLE
[Enhancement]: The format of the documented cases needs to be improved

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#889]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What would you like to be added?

https://towhee.readthedocs.io/en/main/data_collection/mixins.html
The code in this section is incorrectly formatted
<img width="732" alt="截屏2022-03-22 18 50 49" src="https://user-images.githubusercontent.com/34296482/159465784-f19dd3a3-517f-4e12-9703-90e0c8163f48.png">

**Comment by binbinlv** [comment]
Reopen for verification.
@jingkl

**Comment by jingkl** [comment]
Already verified, fixed
