### ISSUE TITLE
[Bug]: Tried towhee example, found an error"NameError: name 'param_scope' is not defined"

### ISSUE THREAD

**Issue by jingkl** [towhee-io/towhee#891]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

https://towhee.readthedocs.io/en/main/data_collection/data_collection.html
```
>>> import towhee
>>> from towhee.functional import DataCollection
>>> class my_add:
...     def __init__(self, val):
...         self.val = val
...     def __call__(self, x):
...         return x+self.val
...
>>> class my_mul:
...     def __init__(self, val):
...         self.val = val
...     def __call__(self, x):
...         return x*self.val
...
>>> with param_scope(dispatcher={
...         'add': my_add, # register `my_add` as `dc.add`
...         'mul': my_mul  # register `my_mul` as `dc.mul`
... }):
...     dc = DataCollection([1,2,3,4])
...     dc.add(1).mul(2).to_list() # call registered operator
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'param_scope' is not defined
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):0.5.1.dev69
- OS(Ubuntu or CentOS):macos
- CPU/Memory:
- GPU:
- Others:
```

**Comment by reiase** [comment]
@jingkl the code example is from `option.py` which contains the `Some` and `Empty`. So the code example can pass the unittest, but failed if the user uses this code directly.

We should also include import statement in our doctest code examples.

**Comment by binbinlv** [comment]
Reopen for verification.
@jingkl

**Comment by jingkl** [comment]
Verified, not fixed

**Comment by jingkl** [comment]
```
>>> import towhee
>>> from towhee.functional import DataCollection
>>>
>>> dataset = DataCollection.from_zip('https://towhee.io/towhee/image-dataset/media/branch/main/image_dataset.zip', '*/dataset/*.JPEG').unstream()
>>> query = DataCollection.from_zip('https://towhee.io/towhee/image-dataset/media/branch/main/image_dataset.zip', '*/query/*.JPEG').unstream()
>>> dc_data = dataset.image_load().towhee.resnet_image_embedding(model_name='resnet50').select('feature_vector')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/hparam/hyperparameter.py", line 205, in __call__
    return self._callback(self._path, self._index, *args, **kwds)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 652, in wrapper
    return self.map(op)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 26, in wrapper
    return self.factory(func(self, *arg, **kws))
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 216, in wrapper
    return creator(*arg, **kws)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 171, in unstream
    iterable = list(iterable)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 389, in inner
    return unary_op(x)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/factory.py", line 93, in __call__
    res = self._op(*arg, **kws)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_registry.py", line 199, in wrapper_call
    return old_call(self, *args, **kws)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_registry.py", line 183, in __call__
    return old_cls(*arg, **kws)
  File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/hub/builtin/operators/computer_vision.py", line 44, in image_load
    import cv2
ModuleNotFoundError: No module named 'cv2'
```

**Comment by filip-halt** [comment]
> Verified, not fixed @reiase
> 
> ```
> >>> import towhee
> >>> from towhee.functional import DataCollection
> >>> with param_scope() as hp:
> ...     hp().dispatcher.as_str = str
> ...     dc = (
> ...        DataCollection.range(10)
> ...         .filter(is_prime)
> ...         .as_str() # map(str)
> ...     )
> ...
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> NameError: name 'param_scope' is not defined
> ```

needs a `from towhee.hparam.hyperparameter import param_scope` if you are running it locally.

**Comment by filip-halt** [comment]
> >>> import towhee
> >>> from towhee.functional import DataCollection
> >>>
> >>> dataset = DataCollection.from_zip('https://towhee.io/towhee/image-dataset/media/branch/main/image_dataset.zip', '*/dataset/*.JPEG').unstream()
> >>> query = DataCollection.from_zip('https://towhee.io/towhee/image-dataset/media/branch/main/image_dataset.zip', '*/query/*.JPEG').unstream()
> >>> dc_data = dataset.image_load().towhee.resnet_image_embedding(model_name='resnet50').select('feature_vector')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/hparam/hyperparameter.py", line 205, in __call__
>     return self._callback(self._path, self._index, *args, **kwds)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 652, in wrapper
>     return self.map(op)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 26, in wrapper
>     return self.factory(func(self, *arg, **kws))
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 216, in wrapper
>     return creator(*arg, **kws)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 171, in unstream
>     iterable = list(iterable)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 389, in inner
>     return unary_op(x)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/factory.py", line 93, in __call__
>     res = self._op(*arg, **kws)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_registry.py", line 199, in wrapper_call
>     return old_call(self, *args, **kws)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_registry.py", line 183, in __call__
>     return old_cls(*arg, **kws)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/hub/builtin/operators/computer_vision.py", line 44, in image_load
>     import cv2
> ModuleNotFoundError: No module named 'cv2'

I believe that we moved away from cv2 being a requiremnet. We might need to add checks with messages to prompt cv2 install.

**Comment by reiase** [comment]
> > > > > import towhee
> > > > > from towhee.functional import DataCollection
> > > > > dataset = DataCollection.from_zip('https://towhee.io/towhee/image-dataset/media/branch/main/image_dataset.zip', '_/dataset/_.JPEG').unstream()
> > > > > query = DataCollection.from_zip('https://towhee.io/towhee/image-dataset/media/branch/main/image_dataset.zip', '_/query/_.JPEG').unstream()
> > > > > dc_data = dataset.image_load().towhee.resnet_image_embedding(model_name='resnet50').select('feature_vector')
> > > > > Traceback (most recent call last):
> > > > > File "", line 1, in 
> > > > > File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/hparam/hyperparameter.py", line 205, in **call**
> > > > > return self._callback(self._path, self._index, *args, **kwds)
> > > > > File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 652, in wrapper
> > > > > return self.map(op)
> > > > > File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 26, in wrapper
> > > > > return self.factory(func(self, *arg, **kws))
> > > > > File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 216, in wrapper
> > > > > return creator(*arg, **kws)
> > > > > File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 171, in unstream
> > > > > iterable = list(iterable)
> > > > > File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 389, in inner
> > > > > return unary_op(x)
> > > > > File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/factory.py", line 93, in **call**
> > > > > res = self._op(*arg, **kws)
> > > > > File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_registry.py", line 199, in wrapper_call
> > > > > return old_call(self, *args, **kws)
> > > > > File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_registry.py", line 183, in **call**
> > > > > return old_cls(*arg, **kws)
> > > > > File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/hub/builtin/operators/computer_vision.py", line 44, in image_load
> > > > > import cv2
> > > > > ModuleNotFoundError: No module named 'cv2'
> 
> I believe that we moved away from cv2 being a requiremnet. We might need to add checks with messages to prompt cv2 install. I saw that a few of our mixins still use it @reiase

There should be some standard method for handling inner import and module not found, I will move this problem to another issue.

**Comment by binbinlv** [comment]
@jingkl 
need verify, so reopen this issue.

**Comment by binbinlv** [comment]
@jingkl 
How about this issue? Is it fixed?

**Comment by jingkl** [comment]
> @jingkl How about this issue? Is it fixed?

They removed the example from the documentation, so turn off the issue
