### ISSUE TITLE
[Feature]: Api for the "img_object_embedding" pipeline

### ISSUE THREAD

**Issue by krishnakatyal** [towhee-io/towhee#894]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

Make Api for any object detection pipeline " towhee/img_object_embedding"

### Describe the solution you'd like.

An api which return the output similar to the https://towhee.io/towhee/img_object_embedding

### Anything else? (Additional Context)

Working on this issue is highly encouraged for Google summer of code 2022 aspirants (Project 1)

**Comment by fzliu** [comment]
Just to clarify, this is not a Towhee-level API, but a hosted API based on Flask/FastAPI/etc.

**Comment by anukaal** [comment]
we can use Region-Based Convolutional Neural Networks (RCNN) because RCNN utilizes a selective search algorithm to propose region of interest in an image and, after that, uses a convolutional neural network to detect the presence of the object of interest within the proposed region.

**Comment by omartarek206** [comment]
Hello, can I work on this issue?

**Comment by aadityasinha-dotcom** [comment]
Hey can I work on this issue?
