### ISSUE TITLE
[Documentation]: Add about towhee page in the get stated document 

### ISSUE THREAD

**Issue by krishnakatyal** [towhee-io/towhee#905]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What kind of documentation would you like added or changed?

A documentation which provides basic towhee information ( similar to the GSoC 22 page )

**Comment by filip-halt** [comment]
What more info is needed? Seems like the getting started page for gsoc is a combo of overview, gettings started, and developer guide/contribution_guide

**Comment by fzliu** [comment]
Closing this issue (subset of #948).
