### ISSUE TITLE
[DesignProposal]: Towhee API interface design

### ISSUE THREAD

**Issue by reiase** [towhee-io/towhee#912]
### Background and Motivation

1. There lacks a well-organized API document;
 
2. A lot of APIs have been added since v0.4, but they are not well-designed; 

#### conceptions:

1. key modules: towhee modules that the user have to know when using towhee;

2. key APIs: towhee APIs that are exposed to the users via key modules;

3. user interface: a group of files that defines which API should be exposed to the users;

#### design details

1. key modules:

    - `towhee`: including all user APIs;
    - `towhee.operator`: including all operator developer APIs;

    - `towhee.types`: data types in towhee; 

2. key APIs

##### core APIs 

    - `towhee.ops`: support both operator and pipeline

    - `towhee.DataCollection`:

    - `towhee.Entity`:

Examples:

```python
op = towhee.ops.some_ns.some_name(some_key=some_value)

```
 

##### data collection APs

A group of factory constructors of `DataCollection`:

    - `towhee.DataCollection`;

    - `towhee.glob`;

    - `towhee.read_csv`;

    - `towhee.read_json`;

    - `towhee.read_camera`; 

    - `towhee.from_pandas`;

    - `towhee.from_zip`;

Examples:

```python

dc = towhee.DataCollection([1, 2, 3, 4])

dc = towhee.glob('some_pattern')

dc = towhee.glob['path']('some_pattern')

dc = towhee.read_csv('some_filename')

dc = towhee.read_camera['image'](device_id=0)

``` 
    

4. user interface: the user interface file should only include the `import` statement, detailed implementations should be put into other files:

    - `towhee/__init__.py`:

    - `towhee/operator/__init__.py` 

    - `towhee/types/__init__.py`

**Comment by GuoRentong** [comment]
is that possible that towhee.ops covers the API of towhee.op?
These two modules looks so similiar

**Comment by reiase** [comment]
> is that possible that towhee.ops covers the API of towhee.op?
> These two modules looks so similiar

`towhee.op` is originally considered as an operator API that is similar to `towhee.pipeline`.

Another option is we keep `towhee.pipeline`, but suggest using `towhee.ops` and `towhee.pipes` in our documents.

**Comment by shiyu22** [comment]
I think `towhee.pips` makes sense because we always emphasize operator and pipeline in our documentation, it will be confused without an interface for pipeline.
