### ISSUE TITLE
import guard for missing modules

### ISSUE THREAD

**Issue by reiase** [towhee-io/towhee#935]
> >>> import towhee
> >>> from towhee.functional import DataCollection
> >>>
> >>> dataset = DataCollection.from_zip('https://towhee.io/towhee/image-dataset/media/branch/main/image_dataset.zip', '*/dataset/*.JPEG').unstream()
> >>> query = DataCollection.from_zip('https://towhee.io/towhee/image-dataset/media/branch/main/image_dataset.zip', '*/query/*.JPEG').unstream()
> >>> dc_data = dataset.image_load().towhee.resnet_image_embedding(model_name='resnet50').select('feature_vector')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/hparam/hyperparameter.py", line 205, in __call__
>     return self._callback(self._path, self._index, *args, **kwds)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 652, in wrapper
>     return self.map(op)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 26, in wrapper
>     return self.factory(func(self, *arg, **kws))
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 216, in wrapper
>     return creator(*arg, **kws)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 171, in unstream
>     iterable = list(iterable)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/functional/data_collection.py", line 389, in inner
>     return unary_op(x)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/factory.py", line 93, in __call__
>     res = self._op(*arg, **kws)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_registry.py", line 199, in wrapper_call
>     return old_call(self, *args, **kws)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/engine/operator_registry.py", line 183, in __call__
>     return old_cls(*arg, **kws)
>   File "/Users/jingjing/miniconda3/envs/tw/lib/python3.9/site-packages/towhee/hub/builtin/operators/computer_vision.py", line 44, in image_load
>     import cv2
> ModuleNotFoundError: No module named 'cv2'

I believe that we moved away from cv2 being a requiremnet. We might need to add checks with messages to prompt cv2 install. I saw that a few of our mixins still use it @reiase

_Originally posted by @filip-halt in https://github.com/towhee-io/towhee/issues/891#issuecomment-1081204276_

**Comment by shiyu22** [comment]
#981
