### ISSUE TITLE
[Bug]: no module named numpy

### ISSUE THREAD

**Issue by pravee42** [towhee-io/towhee#952]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current Behavior

When I use 
```py
from towhee import pipeline
``` 
it throws me an error 
```txt
no module name numpy
```

### Expected Behavior

```py
from towhee import pipeline
```
It should not throw an error when I use 
`from towhee import pipeline`

### Steps To Reproduce

```markdown
1. Install NumPy when installing the towhee module can fix this issue

in the requirements.txt file add the NumPy dependency
```

### Environment

```markdown
- Towhee version(e.g. v0.1.3 or 8b23a93):
- OS(Windows): Windows 11
- CPU/Memory:1.76 GHz
```

### Anything else?

**Reproduce Steps**

1. Install NumPy when installing the towhee module can fix this issue

in the **requirements.txt** file add the **NumPy** dependency.

Assign me to fix this issue

**Comment by fzliu** [comment]
First off, welcome to the Towhee community.

Regarding your issue, did install `towhee` via pip? `pip install towhee`

**Comment by pravee42** [comment]
> First off, welcome to the Towhee community.
> 
> Regarding your issue, did install `towhee` via pip? `pip install towhee`

Yes I have installed this via pip

**Comment by pravee42** [comment]
There is no numPy module dependency in requirements.txt

without numPy 
```
from towhee import pipeline
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ABIPRAVI\AppData\Local\Programs\Python\Python310\lib\site-packages\towhee\__init__.py", line 17, in <module>
    from towhee.dataframe import DataFrame
  File "C:\Users\ABIPRAVI\AppData\Local\Programs\Python\Python310\lib\site-packages\towhee\dataframe\__init__.py", line 15, in <module>
    from towhee.dataframe.dataframe import DataFrame
  File "C:\Users\ABIPRAVI\AppData\Local\Programs\Python\Python310\lib\site-packages\towhee\dataframe\dataframe.py", line 22, in <module>
    from towhee.types._frame import _Frame, FRAME
  File "C:\Users\ABIPRAVI\AppData\Local\Programs\Python\Python310\lib\site-packages\towhee\types\__init__.py", line 15, in <module>
    from towhee.types.image import Image
  File "C:\Users\ABIPRAVI\AppData\Local\Programs\Python\Python310\lib\site-packages\towhee\types\image.py", line 16, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

**Comment by fzliu** [comment]
I just tried it in a virtual environment on my machine as well and ran into the same problem. I'll escalate it with the team and we'll deploy a patch ASAP.

**Comment by pravee42** [comment]
> I just tried it in a virtual environment on my machine as well and ran into the same problem. I'll escalate it with the team and we'll deploy a patch ASAP.

It is very easy to fix just may I do it

**Comment by krishnakatyal** [comment]
@fzliu is it the same virtual environment error?

**Comment by pravee42** [comment]
> @fzliu is it the same virtual environment error?

no refer here
https://github.com/towhee-io/towhee/issues/952#issuecomment-1082650291

**Comment by pravee42** [comment]
> @fzliu is it the same virtual environment error?

![image](https://user-images.githubusercontent.com/65100038/160761695-9c097208-6a2a-48cc-8ccf-f8ce37acb472.png)

**Comment by pravee42** [comment]
@junjiejiangjjj the change in this pr has no effect.
update the change in Pypi website also

**Comment by pravee42** [comment]
This Issue has been fixed

**Comment by binbinlv** [comment]
Will release 0.5.1 before tonight to have this fix.

**Comment by fzliu** [comment]
@pravee42 Thanks for pointing out this bug. As @binbinlv mentioned, we'll have this fix in very soon.

Any interest in [joining our Slack](https://slack.towhee.io/)?

**Comment by pravee42** [comment]
> @pravee42 Thanks for pointing out this bug. As @binbinlv mentioned, we'll have this fix in very soon.
> 
> Any interest in [joining our Slack](https://slack.towhee.io/)?

Yeah sure

**Comment by binbinlv** [comment]
0.5.1 has been released, thanks.

**Comment by pravee42** [comment]
> 0.5.1 has been released, thanks.

Thanks for repy
