### ISSUE TITLE
[question]: towhee/image-embedding-resnet50 vector dimension

### ISSUE THREAD

**Issue by emmataobao** [towhee-io/towhee#978]
### Is there an existing issue for this?

- [X] I have searched the existing issues.

### Is your feature request related to a problem? Please describe.

I use image-embedding-resnet50b  But I don't know the vector dimension。
image-embedding-resnet50b   vector dimension Can it be configured

**Comment by emmataobao** [comment]
thank you, 
I need to reduce the vector dimension because the amount of my images is in tens of millions of vector dimensions and the retrieval efficiency is very low。
image-embedding-resnet50b 1000  vector dimension ，Each vector is about 20K, I think the storage pressure will hit。
I want to compare and test the following, the difference between high-dimensional vector and low-dimensional vector results。
Our program logic is to upload pictures and return to retrieve articles, and the retrieval time is as low as possible

**Comment by fzliu** [comment]
Try any of our `xcit-nano` pipelines, e.g. `image-embedding-xcit-nano-12-p8-224-dist`. These have low-dimensional penultimate layers, which should result in much faster retrieval.

**Comment by emmataobao** [comment]
thank you
